/***************************************************
 *Model source version: 2.4
 ***************************************************/

/***************************************************
 * DO NOT EDIT MANUALLY!
 * Automatically generated by Maple.
 * Created On: Thu May 05 12:16:13 2022.
***************************************************/

/* PLATFORM SPECIFICATION (Both commented out for Linux/Mac) */
/* 32-bit Windows */
/*#define WMI_WINNT 1*/
/* 64-bit Windows */
#define X86_64_WINDOWS 1

#define S_FUNCTION_NAME cbpm_dq_S_noH_noD_RL_Dyno_16k_high_speed
#define S_FUNCTION_LEVEL 2

#include "simstruc.h"
#include "math.h"

/***************************************************
* Variable Definition for System:

* Discrete state variable(s):
*    x[ 0] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.bPM_motor_complete.Inductance_saturation.abs1.u`(t)
*    x[ 1] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.bPM_motor_complete.Inductance_saturation.abs2.u`(t)
*    x[ 2] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.bPM_motor_complete.mechanical_Dynamics_flange.omega_m`(t)
*    x[ 3] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.otheta_m`(t)
*
* Output variable(s):
*    y[ 0] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.bPM_motor_complete.bpm_core_model.iLd_var`(t)
*    y[ 1] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.bPM_motor_complete.bpm_core_model.iLq_var`(t)
*    y[ 2] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.oea`(t)
*    y[ 3] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.oeb`(t)
*    y[ 4] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.oec`(t)
*    y[ 5] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.oia`(t)
*    y[ 6] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.oib`(t)
*    y[ 7] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.oic`(t)
*    y[ 8] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.bPM_motor_complete.Inductance_saturation.abs2.u`(t)
*    y[ 9] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.bPM_motor_complete.Inductance_saturation.abs1.u`(t)
*    y[10] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.oomega_e`(t)
*    y[11] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.bPM_motor_complete.mechanical_Dynamics_flange.omega_m`(t)
*    y[12] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.op_e_b`(t)
*    y[13] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.op_e_dq`(t)
*    y[14] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.op_rot_loss`(t)
*    y[15] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.op_shaft`(t)
*    y[16] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.ot_rot_loss`(t)
*    y[17] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.ot_shaft`(t)
*    y[18] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.ote`(t)
*    y[19] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.otheta_e`(t)
*    y[20] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.otheta_m`(t)
*
* Input variable(s):
*    u[ 0] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.iTr`(t)
*    u[ 1] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.iTs`(t)
*    u[ 2] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.itload`(t)
*    u[ 3] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.iva`(t)
*    u[ 4] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.ivb`(t)
*    u[ 5] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.ivc`(t)
*
* Parameter(s):
*    p[ 0] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.B` (default = .1e-3)
*    p[ 1] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.I_pk0` (default = 0.)
*    p[ 2] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.I_pk1` (default = 1.)
*    p[ 3] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.I_pk2` (default = 2.)
*    p[ 4] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.I_pk3` (default = 3.)
*    p[ 5] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.I_pk4` (default = 4.)
*    p[ 6] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.I_pk5` (default = 5.)
*    p[ 7] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.I_pk6` (default = 6.)
*    p[ 8] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.I_pk7` (default = 7.)
*    p[ 9] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Jrotor` (default = .515e-3)
*    p[10] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Ld0` (default = .884e-1)
*    p[11] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Ld_a0` (default = .2117e-1)
*    p[12] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Ld_a1` (default = .2117e-1)
*    p[13] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Ld_a2` (default = .2117e-1)
*    p[14] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Ld_a3` (default = .2117e-1)
*    p[15] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Ld_a4` (default = .2117e-1)
*    p[16] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Ld_a5` (default = .2117e-1)
*    p[17] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Ld_a6` (default = .2117e-1)
*    p[18] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Ld_a7` (default = .2117e-1)
*    p[19] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Lq0` (default = .972e-1)
*    p[20] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Lq_b0` (default = .2744e-1)
*    p[21] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Lq_b1` (default = .2777e-1)
*    p[22] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Lq_b2` (default = .2742e-1)
*    p[23] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Lq_b3` (default = .2646e-1)
*    p[24] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Lq_b4` (default = .2426e-1)
*    p[25] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Lq_b5` (default = .2329e-1)
*    p[26] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Lq_b6` (default = .2241e-1)
*    p[27] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Lq_b7` (default = .2241e-1)
*    p[28] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.NPP` (default = 3.)
*    p[29] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Rot_Loss_Power0` (default = 0.)
*    p[30] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Rot_Loss_Power1` (default = 1.)
*    p[31] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Rot_Loss_Power2` (default = 12.)
*    p[32] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Rot_Loss_Power3` (default = 19.)
*    p[33] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Rot_Loss_Power4` (default = 26.)
*    p[34] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Rot_Loss_Power5` (default = 35.)
*    p[35] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Rot_Loss_Power6` (default = 41.)
*    p[36] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Rot_Loss_Power7` (default = 56.)
*    p[37] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Rot_Loss_Speed0` (default = 0.)
*    p[38] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Rot_Loss_Speed1` (default = .5e3)
*    p[39] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Rot_Loss_Speed2` (default = .3e4)
*    p[40] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Rot_Loss_Speed3` (default = .4e4)
*    p[41] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Rot_Loss_Speed4` (default = .5e4)
*    p[42] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Rot_Loss_Speed5` (default = .7e4)
*    p[43] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Rot_Loss_Speed6` (default = .12e5)
*    p[44] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Rot_Loss_Speed7` (default = .18e5)
*    p[45] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Rot_Loss_enable` (default = 1.)
*    p[46] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Rot_Loss_omega_th` (default = .1e2)
*    p[47] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Rs0` (default = 9.15)
*    p[48] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.TrRef` (default = 22.)
*    p[49] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.TsRef` (default = 22.)
*    p[50] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.alpha_s` (default = .4e-2)
*    p[51] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.d_magnet` (default = .206e-2)
*    p[52] = `Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.phiPM1` (default = .1151)
*
* Options:
* Table handling:
*    Export lookup as csv: false
* Optimization:
*    Code optimization level: 3
* Constraint handling:
*    Max projection iterations: 50
*    Error tolerance: .1e-4
*    Apply during events: true
* Event handling:
*    Max event iter: 100
*    Width of event hysteresis band: .1e-6
* Baumgarte constraint stabilization:
*    Apply Baumgarte: false
* Fixed-step integrator:
*    Optimize for fixed-step: true
*    Add failure handling: false
* Discretization:
*    Export as discrete: true
*    Embedded solver: ImplicitEuler
*    Discrete step size: .625e-4
*    Allow intermediate steps: false
* Diagnostics:
*    Add outputs for log: false
*
* MapleSim version: 1539851
*
************************************************/

#define TIMESTEP 6.250000e-05
#define INCONTOL 1e200

/* Fixed parameters */
#define NDIFF 4
#define NDFA 4
#define NEQ 60
#define NPAR 53
#define NDPAR 2
#define NINP 6
#define NDISC 1
#define NIX1 55
#define NOUT 21
#define NCON 0
#define NEVT 0
#ifdef EVTHYST
#define NZC 2*NEVT
#else
#define NZC NEVT
#endif
#define INIDREF (2*NEVT+2*NZC)

#define MAXSTRLENGTH 1000
#define WARNNUMDATPTS 100000
#define IS_PARAM_DOUBLE(pVal) (mxIsNumeric(pVal) && !mxIsLogical(pVal) &&\
!mxIsEmpty(pVal) && !mxIsSparse(pVal) && !mxIsComplex(pVal) && mxIsDouble(pVal))

static FILE *fptr = NULL;
static char_T fstr[MAXSTRLENGTH];
static real_T nData[2] = {1.0*NEQ,1.0*NPAR};
static real_T lastsampletime;
static real_T minsamplestep;
static int_T numpts;

static void writeErrorToFile(FILE *fptr, const char_T *errstr)
{
	const char_T *err, uerr[]="unknown error";
	int_T i;
	real_T d;

	if (errstr)
		err = errstr;
	else
	err = uerr;

	d = -1e10; /*terminate value*/
	fwrite(&d,sizeof(real_T),1,fptr);
	for(i=0;;i++) {
		d = (real_T)err[i];
		fwrite(&d,sizeof(real_T),1,fptr);
		if (!err[i]) break;
	}

	fclose(fptr);
}

static real_T dsn_zero=0.0;
static unsigned char dsn_undefC[8] = { 0, 0, 0, 0, 0, 0, 0xF8, 0x7F };
static real_T *dsn_undef = (real_T *)&dsn_undefC;
static unsigned char dsn_posinfC[8] = { 0, 0, 0, 0, 0, 0, 0xF0, 0x7F };
static real_T *dsn_posinf = (real_T *)&dsn_posinfC;
static unsigned char dsn_neginfC[8] = { 0, 0, 0, 0, 0, 0, 0xF0, 0xFF };
static real_T *dsn_neginf = (real_T *)&dsn_neginfC;
#define trunc(v) ( (v>0.0) ? floor(v) : ceil(v) )
#define IS_UNDEF(a) (a-a!=0. || (a!=0. && a-2.*a==0.))
#define UNUSED(a) ((void)(a))
static double avoidcompilerwarn() { return(dsn_zero+*dsn_undef+*dsn_posinf+*dsn_neginf); }
#ifndef M_INT
# if defined _MINGW64 || defined X86_64_WINDOWS
#  define M_INT long long
# elif defined __x86_64__ || defined __ppc64__
#  define M_INT long
# elif defined _M_X64
#  define M_INT long long
# else
#  define M_INT long
# endif
#endif

static real_T D_U_1_U_dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_Rotational_U_Losses_U_46_U_Rot_U_Los977557812489(real_T omega_U_m, real_T omega_U_m_U_th, real_T P_U_rot_U_loss);

static real_T D_U_3_U_dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_Rotational_U_Losses_U_46_U_Rot_U_Los700160257958(real_T omega_U_m, real_T omega_U_m_U_th, real_T P_U_rot_U_loss);

static real_T dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_LUT_U_46_U_LUT_U_row_U_selector_U_46_U_proc(real_T ix, real_T x0, real_T x1, real_T x2, real_T x3, real_T x4, real_T x5, real_T x6, real_T x7, real_T y0, real_T y1, real_T y2, real_T y3, real_T y4, real_T y5, real_T y6, real_T y7, real_T *_U_ox0_U_out, real_T *_U_ox1_U_out, real_T *_U_oy0_U_out, real_T *_U_oy1_U_out);

static real_T dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_Rotational_U_Losses_U_46_U_Rot_U_Loss_U_tau_U_46_U_proc(real_T omega_U_m, real_T omega_U_m_U_th, real_T P_U_rot_U_loss);



#ifdef MSVC
#pragma optimize( "gty", on)
#endif
#ifndef INCONTOL
#define INCONTOL 1e-14
#endif

static void LSQDecompSolve(M_INT n, real_T *A, M_INT Ainc, M_INT *ip, real_T *b)
{
	M_INT i,j,k,r,c,lsq,cp;
	real_T s,t;

	for(i=0;i<n;i++) {
		if(b[i]-b[i]!=0.0 || (b[i]!=0. && b[i]-2.*b[i]==0.)) { ip[n-1]=0; A[0]=1.; for(j=0;j<n;j++) b[j]=*dsn_undef; return; }
		t = fabs(A[i*Ainc]);
		for(j=1;j<n;j++) {
			s = fabs(A[i*Ainc+j]);
			if(s>t) t = s;
		}
		if( t==0.0 )
			A[i*Ainc+n] = 1.0;
		else {
			t = 1.0/t;
			for(j=0;j<n;j++) A[i*Ainc+j] *= t;
			b[i] *= t;
			A[i*Ainc+n] = t;
		}
	}

	for(j=0;j<n;j++) {
		t = fabs(A[j]);
		for(i=1;i<n;i++) {
			s = fabs(A[i*Ainc+j]);
			if(s>t) t = s;
		}
		if( t==0.0 )
			A[n*Ainc+j] = 1.0;
		else {
			t = 1.0/t;
			for(i=0;i<n;i++) A[i*Ainc+j] *= t;
			A[n*Ainc+j] = t;
		}
	}

	ip[n-1] = 0;
	lsq = 0;
	cp = 0;
	for(k=0;k<n;k++) {
		r = 0; c = 0; t = 0.0;
		if( cp<n ) {
			for(cp=cp+1;cp<n;cp++) {
				for(i=k;i<n;i++) {
					s = fabs(A[i*Ainc+cp]);
					if(s>t) { r = i; c = cp; t = s; }
				}
				if( t>0.5 ) break;
			}
		}
		if( cp>=n ) {
			for(i=k;i<n;i++)
				for(j=k;j<n;j++) {
					s = fabs(A[i*Ainc+j]);
					if(s>t) { r = i; c = j; t = s; }
				}
		}
		if( t<1e-10 ) {
			if( k==0 ) { ip[n-1]=0; A[0]=2.; for(j=0;j<n;j++) b[j]=*dsn_undef; return; }
			if( lsq ) { ip[n-1]=0; A[0]=3.; for(j=0;j<n;j++) b[j]=*dsn_undef; return; }
			lsq = 1;
			t = 1e-16;
			for(i=0;i<k;i++) {
				s = fabs(b[i]);
				if(s>t) t = s;
			}
			for(i=k;i<n;i++) {
				if( fabs(b[i])/t>INCONTOL*n ) { ip[n-1]=0; A[0]=4.; for(j=0;j<n;j++) b[j]=*dsn_undef; return; }
				b[i] = 0.0;
			}

			for(r=k;r<n;r++) {
				for(i=k;i<n;i++) A[i*Ainc+n+r] = 0.0;
				A[r*Ainc+n+r] = 1.0;
				A[(k-1)*Ainc+n+r] = -A[(k-1)*Ainc+r]/A[(k-1)*Ainc+k-1];
				for(i=k-1;i>=0;i--) {
					A[i*Ainc+n+r] = A[i*Ainc+r];
					for(j=i+1;j<k;j++)
						A[i*Ainc+n+r] += A[i*Ainc+j]*A[j*Ainc+n+r];
					A[i*Ainc+n+r] = -A[i*Ainc+n+r]/A[i*(Ainc+1)];
				}
			}
			for(r=0;r<k;r++) {
				s = -1.0/A[r*(Ainc+1)];
				for(i=k;i<n;i++)
					if( A[r*Ainc+n+i]!=0.0 ) {
						t = s*A[r*Ainc+n+i];
						A[i*Ainc+r] += t;
						for(j=r+1;j<n;j++)
							A[j*Ainc+n+i] += t*A[r*Ainc+j];
						b[i] += t*b[r];
					}
			}
			for(i=k;i<n;i++)
				for(j=k;j<n;j++)
					A[i*Ainc+j] = A[j*Ainc+n+i];
			r = 0; c = 0; t = 0.0;
			for(i=k;i<n;i++)
				for(j=k;j<n;j++) {
					s = fabs(A[i*Ainc+j]);
					if(s>t) { r = i; c = j; t = s; }
				}
			if( t<1e-10 ) { ip[n-1]=0; A[0]=3.; for(j=0;j<n;j++) b[j]=*dsn_undef; return; }
		}
		if( !lsq ) ip[n-1]++;
		if( k==n-1 ) break;
		ip[k] = r;
		ip[n+k] = c;
		if( r>k ) {
			for(j=0;j<n;j++) {
				t = A[r*Ainc+j]; A[r*Ainc+j] = A[k*Ainc+j]; A[k*Ainc+j] = t;
			}
			t = b[r]; b[r] = b[k]; b[k] = t;
		}
		if( c>k )
			for(i=0;i<n;i++) {
				t = A[i*Ainc+c]; A[i*Ainc+c] = A[i*Ainc+k]; A[i*Ainc+k] = t;
			}
		s = -1.0/A[k*(Ainc+1)];
		for(i=k+1;i<n;i++)
			if( A[i*Ainc+k]!=0.0 ) {
				t = s*A[i*Ainc+k];
				A[i*Ainc+k] = t;
				for(j=k+1;j<n;j++)
					A[i*Ainc+j] += t*A[k*Ainc+j];
				b[i] += t*b[k];
			}
	}
	for(j=n-1;j>0;j--) {
		b[j] = b[j]/A[j*(Ainc+1)];
		t = -b[j];
		for(i=0;i<j;i++)
			b[i] += t*A[i*Ainc+j];
	}
	b[0] = b[0]/A[0];
	for(j=n-2;j>=0;j--) {
		i = ip[n+j];
		if(i!=j) {
			t = b[i]; b[i] = b[j]; b[j] = t;
		}
	}
	for(j=0;j<n;j++) b[j] *= A[n*Ainc+j];
}
#ifdef MSVC
#pragma optimize( "", on)
#endif

#ifdef MSVC
#pragma optimize( "gty", on)
#endif
static void LSQMultiSolve(M_INT n, real_T *A, M_INT Ainc, M_INT *ip, M_INT nb,
	real_T *b, M_INT binc)
{
	M_INT i,j,k,m;
	real_T t,s;

	if( ip[n-1]==0 ) {
		for(i=0;i<n;i++) for(k=0;k<nb;k++) b[i*binc+k]=*dsn_undef;
		return;
	}
	for(i=0;i<n;i++) for(k=0;k<nb;k++) b[i*binc+k] *= A[i*Ainc+n];
	for(i=0;i<n-1;i++) {
		m = ip[i];
		if( m!=i )
			for(k=0;k<nb;k++) {
				t = b[m*binc+k]; b[m*binc+k] = b[i*binc+k]; b[i*binc+k] = t;
			}
	}
	for(j=0;j<n-1;j++)
		for(k=0;k<nb;k++) {
			t = b[j*binc+k];
			for(i=j+1;i<n;i++)
				b[i*binc+k] += t*A[i*Ainc+j];
		}
	for(j=n-1;j>0;j--) {
		s = 1.0/A[j*(Ainc+1)];
		for(k=0;k<nb;k++) {
			b[j*binc+k] = s*b[j*binc+k];
			t = -b[j*binc+k];
			for(i=0;i<j;i++)
				b[i*binc+k] += t*A[i*Ainc+j];
		}
	}
	for(k=0;k<nb;k++) b[k] = b[k]/A[0];
	for(j=n-2;j>=0;j--) {
		m = ip[n+j];
		if(m!=j)
			for(k=0;k<nb;k++) {
				t = b[m*binc+k]; b[m*binc+k] = b[j*binc+k]; b[j*binc+k] = t;
			}
	}
	for(j=0;j<n;j++) for(k=0;k<nb;k++) b[j*binc+k] *= A[n*Ainc+j];
}
#ifdef MSVC
#pragma optimize( "", on)
#endif

#ifdef MSVC
#pragma optimize( "gty", on)
#endif
static void DecompCInc(M_INT n, real_T *A, M_INT Ainc, M_INT *ip)
{
	M_INT i,j,k,m;
	real_T t;

	ip[n-1]=1;
	for(k=0;k<n-1;k++) {
		m=k;
		for(i=k+1;i<n;i++)
			if( fabs(A[i*Ainc+k])>fabs(A[m*Ainc+k]) ) m=i;
		ip[k]=m;
		if( m!=k ) ip[n-1]=-ip[n-1];
		t=A[m*Ainc+k]; A[m*Ainc+k]=A[(Ainc+1)*k]; A[(Ainc+1)*k]=t;
		if( t==0.0 ) { ip[n-1]=0; return; }
		t=-1.0/t;
		for(i=k+1;i<n;i++) A[i*Ainc+k]=A[i*Ainc+k]*t;
		for(j=k+1;j<n;j++) {
			t=A[m*Ainc+j]; A[m*Ainc+j]=A[k*Ainc+j]; A[k*Ainc+j]=t;
			if( t!=0.0 )
				for(i=k+1;i<n;i++) A[i*Ainc+j]+=A[i*Ainc+k]*t;
		}
	}
	if(A[(n-1)*(Ainc+1)]==0.0) ip[n-1]=0;
}
#ifdef MSVC
#pragma optimize( "", on)
#endif

#ifdef MSVC
#pragma optimize( "gty", on)
#endif
static void SolveCInc(M_INT n, real_T *A, M_INT Ainc, M_INT *ip, real_T *b)
{
	M_INT i,j,m;
	real_T t;

	if( n>1 ) {
		for(j=0;j<n-1;j++) {
			m=ip[j];
			t=b[m]; b[m]=b[j]; b[j]=t;
			for(i=j+1;i<n;i++) b[i]+=A[i*Ainc+j]*t;
		}
		for(j=n-1;j>0;j--) {
			b[j]=b[j]/A[(Ainc+1)*j];
			t=-b[j];
			for(i=0;i<=j-1;i++) b[i]+=A[i*Ainc+j]*t;
		}
	}
	b[0]=b[0]/A[0];
}
#ifdef MSVC
#pragma optimize( "", on)
#endif

static real_T dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_LUT_U_46_U_LUT_U_row_U_selector_U_46_U_proc(real_T ix, real_T x0, real_T x1, real_T x2, real_T x3, real_T x4, real_T x5, real_T x6, real_T x7, real_T y0, real_T y1, real_T y2, real_T y3, real_T y4, real_T y5, real_T y6, real_T y7, real_T *_U_ox0_U_out, real_T *_U_ox1_U_out, real_T *_U_oy0_U_out, real_T *_U_oy1_U_out)
{
	real_T row, ox0, ox1, oy0, oy1;

	if( ( (ix==x0) || (x0<ix) ) && (ix<x1) ) {
		row = 1.;
		ox0 = x0;
		ox1 = x1;
		oy0 = y0;
		oy1 = y1;
	}
	else if( ( (ix==x1) || (x1<ix) ) && (ix<x2) ) {
		row = 2.;
		ox0 = x1;
		ox1 = x2;
		oy0 = y1;
		oy1 = y2;
	}
	else if( ( (ix==x2) || (x2<ix) ) && (ix<x3) ) {
		row = 3.;
		ox0 = x2;
		ox1 = x3;
		oy0 = y2;
		oy1 = y3;
	}
	else if( ( (ix==x3) || (x3<ix) ) && (ix<x4) ) {
		row = 4.;
		ox0 = x3;
		ox1 = x4;
		oy0 = y3;
		oy1 = y4;
	}
	else if( ( (ix==x4) || (x4<ix) ) && (ix<x5) ) {
		row = 5.;
		ox0 = x4;
		ox1 = x5;
		oy0 = y4;
		oy1 = y5;
	}
	else if( ( (ix==x5) || (x5<ix) ) && (ix<x6) ) {
		row = 6.;
		ox0 = x5;
		ox1 = x6;
		oy0 = y5;
		oy1 = y6;
	}
	else if( ( (ix==x6) || (x6<ix) ) && ( (ix<x7) || (ix==x7) ) ) {
		row = 7.;
		ox0 = x6;
		ox1 = x7;
		oy0 = y6;
		oy1 = y7;
	}
	else {
		row = 8.;
		ox0 = x7;
		ox1 = x7+0.1;
		oy0 = y7;
		oy1 = y7+0.1;
	}
	*_U_ox0_U_out = ox0;
	*_U_ox1_U_out = ox1;
	*_U_oy0_U_out = oy0;
	*_U_oy1_U_out = oy1;
	return(row);
}

static real_T dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_Rotational_U_Losses_U_46_U_Rot_U_Loss_U_tau_U_46_U_proc(real_T omega_U_m, real_T omega_U_m_U_th, real_T P_U_rot_U_loss)
{
	real_T t_U_rot_U_loss;

	if( fabs(omega_U_m)<=omega_U_m_U_th )
		t_U_rot_U_loss = 0.;
	else
		t_U_rot_U_loss = P_U_rot_U_loss/omega_U_m;
	return(t_U_rot_U_loss);
}

static real_T D_U_3_U_dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_Rotational_U_Losses_U_46_U_Rot_U_Los700160257958(real_T omega_U_m, real_T omega_U_m_U_th, real_T P_U_rot_U_loss)
{
	real_T t_U_rot_U_loss, t_U_rot_U_lossP_U_rot_U_loss;

	if( fabs(omega_U_m)<=omega_U_m_U_th ) {
		t_U_rot_U_lossP_U_rot_U_loss = 0.;
		t_U_rot_U_loss = 0.;
	}
	else {
		t_U_rot_U_lossP_U_rot_U_loss = 1.0/omega_U_m;
		t_U_rot_U_loss = P_U_rot_U_loss/omega_U_m;
	}
	return(t_U_rot_U_lossP_U_rot_U_loss);
}

static real_T D_U_1_U_dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_Rotational_U_Losses_U_46_U_Rot_U_Los977557812489(real_T omega_U_m, real_T omega_U_m_U_th, real_T P_U_rot_U_loss)
{
	real_T t_U_rot_U_loss, t_U_rot_U_lossomega_U_m;

	if( fabs(omega_U_m)<=omega_U_m_U_th ) {
		t_U_rot_U_lossomega_U_m = 0.;
		t_U_rot_U_loss = 0.;
	}
	else {
		t_U_rot_U_lossomega_U_m = -P_U_rot_U_loss/(omega_U_m*omega_U_m);
		t_U_rot_U_loss = P_U_rot_U_loss/omega_U_m;
	}
	return(t_U_rot_U_lossomega_U_m);
}

static void fp(int_T N, real_T T, real_T *Y, real_T *YP)
{
	real_T M[60], V[5], Z[24], td1;
	int_T ti1, ti2;
	M_INT P[9];

	UNUSED(N);
	UNUSED(T);
	if( Y[0]>=0. )
		Y[22] = Y[0];
	else
		Y[22] = -Y[0];
	YP[3] = Y[2];
	if( Y[68]<Y[22] )
		Y[23] = Y[68];
	else if( Y[22]<Y[61] )
		Y[23] = Y[61];
	else
		Y[23] = Y[22];
	for(ti1=0;ti1<=4;ti1++)
		for(ti2=0;ti2<=4;ti2++)
			M[ti1*10+ti2] = 0.;
	for(ti1=0;ti1<=4;ti1++)
		V[ti1] = 0.;
	M[4] = 1.;
	Z[13] = dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_LUT_U_46_U_LUT_U_row_U_selector_U_46_U_proc(Y[23],Y[61],Y[62],Y[63],Y[64],Y[65],Y[66],Y[67],Y[68],Y[80],Y[81],Y[82],Y[83],Y[84],Y[85],Y[86],Y[87],&Z[9],&Z[10],&Z[11],&Z[12]);
	V[0] = Z[13];
	M[10] = 1.;
	V[1] = Z[9];
	M[21] = 1.;
	V[2] = Z[10];
	M[32] = 1.;
	V[3] = Z[11];
	M[43] = 1.;
	V[4] = Z[12];
	LSQDecompSolve(5,M,10,P,V);
	if( P[4]==0 ) {
		YP[0] = (*dsn_undef);
		return;
	}
	Y[9] = V[0];
	Y[10] = V[1];
	Y[11] = V[2];
	Y[12] = V[3];
	Y[13] = V[4];
	if( Y[1]>=0. )
		Y[20] = Y[1];
	else
		Y[20] = -Y[1];
	Z[0] = Y[9]-Y[10];
	Z[0] = 1.0/Z[0];
	Y[25] = Y[11]-(Y[11]-Y[12])*Z[0]*(Y[9]-Y[23]);
	if( Y[68]<Y[20] )
		Y[21] = Y[68];
	else if( Y[20]<Y[61] )
		Y[21] = Y[61];
	else
		Y[21] = Y[20];
	for(ti1=0;ti1<=4;ti1++)
		for(ti2=0;ti2<=4;ti2++)
			M[ti1*10+ti2] = 0.;
	for(ti1=0;ti1<=4;ti1++)
		V[ti1] = 0.;
	M[4] = 1.;
	Z[18] = dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_LUT_U_46_U_LUT_U_row_U_selector_U_46_U_proc(Y[21],Y[61],Y[62],Y[63],Y[64],Y[65],Y[66],Y[67],Y[68],Y[71],Y[72],Y[73],Y[74],Y[75],Y[76],Y[77],Y[78],&Z[14],&Z[15],&Z[16],&Z[17]);
	V[0] = Z[18];
	M[10] = 1.;
	V[1] = Z[14];
	M[21] = 1.;
	V[2] = Z[15];
	M[32] = 1.;
	V[3] = Z[16];
	M[43] = 1.;
	V[4] = Z[17];
	LSQDecompSolve(5,M,10,P,V);
	if( P[4]==0 ) {
		YP[0] = (*dsn_undef);
		return;
	}
	Y[4] = V[0];
	Y[5] = V[1];
	Y[6] = V[2];
	Y[7] = V[3];
	Y[8] = V[4];
	Z[0] = Y[4]-Y[5];
	Z[0] = 1.0/Z[0];
	Y[24] = Y[6]-(Y[6]-Y[7])*Z[0]*(Y[4]-Y[21]);
	Y[26] = Y[112]*((Y[108]-Y[53])*Y[111]+1.)+Y[24]*Y[1];
	Z[0] = Y[88]*Y[3];
	Z[1] = sin(Z[0]);
	Z[2] = Y[56];
	Z[3] = Y[57];
	Z[4] = Y[58];
	Z[0] = cos(Z[0]);
	Z[5] = Z[3]+Z[4];
	Z[3] = Z[3]-Z[4];
	Z[4] = 0.3333333333333333333;
	Z[6] = 0.577350269189625763;
	Y[29] = Z[0]*Z[3]*Z[6]+Z[1]*Z[4]*Z[5]-0.6666666666666666667*Z[1]*Z[2];
	Z[7] = (Y[54]-Y[109])*Y[110]+1.;
	Z[8] = Y[88]*Y[2];
	YP[0] = (1.*(Y[29]-Z[7]*Y[0]*Y[107]-Z[8]*Y[26]))/Y[25];
	Y[27] = Y[25]*Y[0];
	Y[28] = Z[1]*Z[3]*Z[6]-Z[0]*Z[4]*Z[5]+0.6666666666666666667*Z[0]*Z[2];
	YP[1] = (1.*(Z[8]*Y[27]+Y[28]-Z[7]*Y[1]*Y[107]))/Y[24];
	if( Y[2]>=0. )
		td1 = Y[2];
	else
		td1 = -Y[2];
	Y[31] = 9.5493*td1;
	Y[34] = 1.5*Y[88]*(Y[0]*Y[26]-Y[1]*Y[27]);
	if( Y[104]<Y[31] )
		Y[32] = Y[104];
	else if( Y[31]<Y[97] )
		Y[32] = Y[97];
	else
		Y[32] = Y[31];
	for(ti1=0;ti1<=4;ti1++)
		for(ti2=0;ti2<=4;ti2++)
			M[ti1*10+ti2] = 0.;
	for(ti1=0;ti1<=4;ti1++)
		V[ti1] = 0.;
	M[4] = 1.;
	Z[23] = dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_LUT_U_46_U_LUT_U_row_U_selector_U_46_U_proc(Y[32],Y[97],Y[98],Y[99],Y[100],Y[101],Y[102],Y[103],Y[104],Y[89],Y[90],Y[91],Y[92],Y[93],Y[94],Y[95],Y[96],&Z[19],&Z[20],&Z[21],&Z[22]);
	V[0] = Z[23];
	M[10] = 1.;
	V[1] = Z[19];
	M[21] = 1.;
	V[2] = Z[20];
	M[32] = 1.;
	V[3] = Z[21];
	M[43] = 1.;
	V[4] = Z[22];
	LSQDecompSolve(5,M,10,P,V);
	if( P[4]==0 ) {
		YP[0] = (*dsn_undef);
		return;
	}
	Y[14] = V[0];
	Y[15] = V[1];
	Y[16] = V[2];
	Y[17] = V[3];
	Y[18] = V[4];
	Z[0] = Y[14]-Y[15];
	Z[0] = 1.0/Z[0];
	Y[33] = -((Y[15]-Y[32])*Y[16]+(Y[32]-Y[14])*Y[17])*Z[0]*Y[105];
	Y[19] = (dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_Rotational_U_Losses_U_46_U_Rot_U_Loss_U_tau_U_46_U_proc(Y[2],Y[106],Y[33]));
	Y[30] = -(Y[55]+Y[19]);
	YP[2] = (1.*(Y[30]+Y[34]-Y[2]*Y[60]))/Y[69];
}

static void otp(real_T T, real_T *Y, real_T *YP)
{
	real_T Z[5];

	UNUSED(T);
	Y[35] = 0.;
	Y[36] = 0.;
	Y[37] = 0.;
	Z[0] = Y[88]*Y[3];
	Z[1] = sin(Z[0]);
	Z[2] = cos(Z[0]);
	Z[3] = Z[1]*Y[0]-Z[2]*Y[1];
	Y[38] = -Z[3];
	Z[4] = 0.866025403784438645;
	Z[3] = 0.5*Z[3];
	Z[1] = Z[4]*(Z[2]*Y[0]+Z[1]*Y[1]);
	Y[39] = Z[3]+Z[1];
	Y[40] = Z[3]-Z[1];
	Z[1] = Y[19]-Y[34];
	Z[2] = Z[1]*Y[2];
	Y[41] = Y[33]-Z[2]+1.5*Y[107]*((Y[54]-Y[109])*Y[110]+1.)*(Y[0]*Y[0]+Y[1]*Y[1]);
	Y[42] = Y[88]*Y[2];
	Y[43] = 1.5*(Y[28]*Y[1]+Y[29]*Y[0]);
	Y[44] = -Z[2];
	Y[45] = -Z[1];
	Y[46] = Z[0];
}

static void Dfp(real_T T, real_T *Y, real_T *FX, real_T *FY)
{
	real_T B[25], M[60], V[5], YP[4], Z[94], Mr1, Mr2, Mr3, Mr4, Mr5, Mt1[2], td1;
	int_T ti1, ti2, ti3;
	M_INT P[9];

	UNUSED(T);
	for(ti2=0;ti2<=3;ti2++)
		for(ti3=0;ti3<=3;ti3++)
			FY[ti2*4+ti3] = 0.;
	for(ti2=0;ti2<=3;ti2++)
		FX[ti2] = 0.;
	if( Y[0]>=0. )
		Y[22] = Y[0];
	else
		Y[22] = -Y[0];
	if( Y[0]>=0. )
		Z[18] = 1.;
	else
		Z[18] = -1.;
	YP[3] = Y[2];
	FY[14] = 1.;
	if( Y[68]<Y[22] )
		Y[23] = Y[68];
	else if( Y[22]<Y[61] )
		Y[23] = Y[61];
	else
		Y[23] = Y[22];
	if( Y[68]<Y[22] )
		Z[19] = 0.;
	else if( Y[22]<Y[61] )
		Z[19] = 0.;
	else
		Z[19] = Z[18];
	for(ti2=0;ti2<=4;ti2++)
		for(ti3=0;ti3<=4;ti3++)
			M[ti2*10+ti3] = 0.;
	for(ti2=0;ti2<=4;ti2++)
		V[ti2] = 0.;
	M[4] = 1.;
	Z[83] = dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_LUT_U_46_U_LUT_U_row_U_selector_U_46_U_proc(Y[23],Y[61],Y[62],Y[63],Y[64],Y[65],Y[66],Y[67],Y[68],Y[80],Y[81],Y[82],Y[83],Y[84],Y[85],Y[86],Y[87],&Z[79],&Z[80],&Z[81],&Z[82]);
	V[0] = Z[83];
	M[10] = 1.;
	V[1] = Z[79];
	M[21] = 1.;
	V[2] = Z[80];
	M[32] = 1.;
	V[3] = Z[81];
	M[43] = 1.;
	V[4] = Z[82];
	LSQDecompSolve(5,M,10,P,V);
	if( P[4]==0 ) {
		FX[0] = (*dsn_undef);
		return;
	}
	Y[9] = V[0];
	Y[10] = V[1];
	Y[11] = V[2];
	Y[12] = V[3];
	Y[13] = V[4];
	for(ti2=0;ti2<=4;ti2++)
		for(ti3=0;ti3<=0;ti3++)
			B[ti2*5+ti3] = 0.;
	Z[79] = 0.;
	Z[80] = 0.;
	Z[81] = 0.;
	Z[82] = 0.;
	Z[83] = 0.;
	Mt1[0] = ( (0.00001*fabs(Y[23])<1e-07) ? 1e-07 : 0.00001*fabs(Y[23]) );
	Mt1[1] = Z[19]/(2.*Mt1[0]);
	Mr5 = dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_LUT_U_46_U_LUT_U_row_U_selector_U_46_U_proc(Y[23]+Mt1[0],Y[61],Y[62],Y[63],Y[64],Y[65],Y[66],Y[67],Y[68],Y[80],Y[81],Y[82],Y[83],Y[84],Y[85],Y[86],Y[87],&Mr1,&Mr2,&Mr3,&Mr4);
	Z[79] = Mt1[1]*Mr1+Z[79];
	Z[80] = Mt1[1]*Mr2+Z[80];
	Z[81] = Mt1[1]*Mr3+Z[81];
	Z[82] = Mt1[1]*Mr4+Z[82];
	Z[83] = Mt1[1]*Mr5+Z[83];
	Mr5 = dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_LUT_U_46_U_LUT_U_row_U_selector_U_46_U_proc(Y[23]-Mt1[0],Y[61],Y[62],Y[63],Y[64],Y[65],Y[66],Y[67],Y[68],Y[80],Y[81],Y[82],Y[83],Y[84],Y[85],Y[86],Y[87],&Mr1,&Mr2,&Mr3,&Mr4);
	Z[79] = Z[79]-Mt1[1]*Mr1;
	Z[80] = Z[80]-Mt1[1]*Mr2;
	Z[81] = Z[81]-Mt1[1]*Mr3;
	Z[82] = Z[82]-Mt1[1]*Mr4;
	Z[83] = Z[83]-Mt1[1]*Mr5;
	B[0] = Z[83];
	B[5] = Z[79];
	B[10] = Z[80];
	B[15] = Z[81];
	B[20] = Z[82];
	LSQMultiSolve(5,M,10,P,1,B,5);
	Z[20] = B[0];
	Z[21] = B[5];
	Z[22] = B[10];
	Z[23] = B[15];
	Z[24] = B[20];
	if( Y[1]>=0. )
		Y[20] = Y[1];
	else
		Y[20] = -Y[1];
	if( Y[1]>=0. )
		Z[25] = 1.;
	else
		Z[25] = -1.;
	Z[0] = Y[11]-Y[12];
	Z[1] = Y[9]-Y[10];
	Z[2] = Y[9]-Y[23];
	Z[1] = 1.0/Z[1];
	Z[3] = Z[0]*Z[1];
	Y[25] = Y[11]-Z[2]*Z[3];
	Z[26] = Z[1]*(Z[2]*(Z[3]*(Z[20]-Z[21])+Z[23]-Z[22])-Z[0]*(Z[20]-Z[19]))+Z[22];
	if( Y[68]<Y[20] )
		Y[21] = Y[68];
	else if( Y[20]<Y[61] )
		Y[21] = Y[61];
	else
		Y[21] = Y[20];
	if( Y[68]<Y[20] )
		Z[27] = 0.;
	else if( Y[20]<Y[61] )
		Z[27] = 0.;
	else
		Z[27] = Z[25];
	for(ti2=0;ti2<=4;ti2++)
		for(ti3=0;ti3<=4;ti3++)
			M[ti2*10+ti3] = 0.;
	for(ti2=0;ti2<=4;ti2++)
		V[ti2] = 0.;
	M[4] = 1.;
	Z[88] = dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_LUT_U_46_U_LUT_U_row_U_selector_U_46_U_proc(Y[21],Y[61],Y[62],Y[63],Y[64],Y[65],Y[66],Y[67],Y[68],Y[71],Y[72],Y[73],Y[74],Y[75],Y[76],Y[77],Y[78],&Z[84],&Z[85],&Z[86],&Z[87]);
	V[0] = Z[88];
	M[10] = 1.;
	V[1] = Z[84];
	M[21] = 1.;
	V[2] = Z[85];
	M[32] = 1.;
	V[3] = Z[86];
	M[43] = 1.;
	V[4] = Z[87];
	LSQDecompSolve(5,M,10,P,V);
	if( P[4]==0 ) {
		FX[0] = (*dsn_undef);
		return;
	}
	Y[4] = V[0];
	Y[5] = V[1];
	Y[6] = V[2];
	Y[7] = V[3];
	Y[8] = V[4];
	for(ti2=0;ti2<=4;ti2++)
		for(ti3=0;ti3<=0;ti3++)
			B[ti2*5+ti3] = 0.;
	Z[84] = 0.;
	Z[85] = 0.;
	Z[86] = 0.;
	Z[87] = 0.;
	Z[88] = 0.;
	Mt1[0] = ( (0.00001*fabs(Y[21])<1e-07) ? 1e-07 : 0.00001*fabs(Y[21]) );
	Mt1[1] = Z[27]/(2.*Mt1[0]);
	Mr5 = dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_LUT_U_46_U_LUT_U_row_U_selector_U_46_U_proc(Y[21]+Mt1[0],Y[61],Y[62],Y[63],Y[64],Y[65],Y[66],Y[67],Y[68],Y[71],Y[72],Y[73],Y[74],Y[75],Y[76],Y[77],Y[78],&Mr1,&Mr2,&Mr3,&Mr4);
	Z[84] = Mt1[1]*Mr1+Z[84];
	Z[85] = Mt1[1]*Mr2+Z[85];
	Z[86] = Mt1[1]*Mr3+Z[86];
	Z[87] = Mt1[1]*Mr4+Z[87];
	Z[88] = Mt1[1]*Mr5+Z[88];
	Mr5 = dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_LUT_U_46_U_LUT_U_row_U_selector_U_46_U_proc(Y[21]-Mt1[0],Y[61],Y[62],Y[63],Y[64],Y[65],Y[66],Y[67],Y[68],Y[71],Y[72],Y[73],Y[74],Y[75],Y[76],Y[77],Y[78],&Mr1,&Mr2,&Mr3,&Mr4);
	Z[84] = Z[84]-Mt1[1]*Mr1;
	Z[85] = Z[85]-Mt1[1]*Mr2;
	Z[86] = Z[86]-Mt1[1]*Mr3;
	Z[87] = Z[87]-Mt1[1]*Mr4;
	Z[88] = Z[88]-Mt1[1]*Mr5;
	B[0] = Z[88];
	B[5] = Z[84];
	B[10] = Z[85];
	B[15] = Z[86];
	B[20] = Z[87];
	LSQMultiSolve(5,M,10,P,1,B,5);
	Z[28] = B[0];
	Z[29] = B[5];
	Z[30] = B[10];
	Z[31] = B[15];
	Z[32] = B[20];
	Z[0] = Y[6]-Y[7];
	Z[1] = Y[4]-Y[5];
	Z[2] = Y[4]-Y[21];
	Z[1] = 1.0/Z[1];
	Z[3] = Z[0]*Z[1];
	Y[24] = Y[6]-Z[2]*Z[3];
	Z[33] = Z[1]*(Z[2]*(Z[3]*(Z[28]-Z[29])+Z[31]-Z[30])-Z[0]*(Z[28]-Z[27]))+Z[30];
	Y[26] = Y[112]*((Y[108]-Y[53])*Y[111]+1.)+Y[24]*Y[1];
	Z[34] = Z[33]*Y[1]+Y[24];
	Z[35] = -Y[47]*Y[112]*Y[111];
	Z[0] = Y[88]*Y[3];
	Z[1] = sin(Z[0]);
	Z[2] = Y[56];
	Z[3] = Y[57];
	Z[4] = Y[58];
	Z[0] = cos(Z[0]);
	Z[5] = Z[3]+Z[4];
	Z[6] = Z[1]*Z[5];
	Z[3] = Z[3]-Z[4];
	Z[4] = Z[0]*Z[3];
	Z[7] = 0.3333333333333333333;
	Z[8] = 0.577350269189625763;
	Z[9] = 0.6666666666666666667*Z[1];
	Z[10] = Z[9]*Z[2];
	Y[29] = Z[4]*Z[8]+Z[6]*Z[7]-Z[10];
	Z[5] = Z[0]*Z[5];
	Z[3] = Z[1]*Z[3];
	Z[36] = Y[88]*Z[5]*Z[7]-Y[88]*Z[3]*Z[8]-0.6666666666666666667*Y[88]*Z[0]*Z[2];
	Z[11] = Y[51]+Y[52];
	Z[12] = Y[51]-Y[52];
	Z[37] = Z[0]*Z[8]*Z[12]+Z[1]*Z[7]*Z[11]-Z[9]*Y[50];
	Z[9] = Y[54];
	Z[13] = (Z[9]-Y[109])*Y[110]+1.;
	Z[14] = Y[88]*Y[2];
	Z[15] = Y[107]*Y[0];
	Z[16] = 1.0/Y[25];
	Z[17] = (Z[14]*Y[26]+Z[13]*Z[15]-Y[29])*Z[16];
	YP[0] = -Z[17];
	Z[9] = Y[107]*((Z[9]-Y[109])*Y[110]+1.);
	FY[0] = Z[16]*(Z[17]*Z[26]-Z[9]);
	FY[1] = -Z[14]*Z[34]*Z[16];
	FY[2] = -Y[88]*Y[26]*Z[16];
	FY[3] = Z[36]*Z[16];
	FX[0] = 1.*(Z[37]-Z[15]*Y[48]*Y[110]-Z[14]*Z[35])*Z[16];
	Y[27] = Y[25]*Y[0];
	Z[38] = Z[26]*Y[0]+Y[25];
	Z[15] = 0.6666666666666666667*Z[0];
	Y[28] = Z[2]*Z[15]+Z[3]*Z[8]-Z[5]*Z[7];
	Z[39] = Z[4]*Z[8]*Y[88]+Z[6]*Z[7]*Y[88]-Z[10]*Y[88];
	Z[40] = Z[1]*Z[8]*Z[12]+Z[15]*Y[50]-Z[0]*Z[7]*Z[11];
	Z[0] = Y[107]*Y[1];
	Z[1] = 1.0/Y[24];
	Z[2] = (Z[0]*Z[13]-Z[14]*Y[27]-Y[28])*Z[1];
	YP[1] = -Z[2];
	FY[4] = Z[14]*Z[38]*Z[1];
	FY[5] = Z[1]*(Z[2]*Z[33]-Z[9]);
	FY[6] = Y[88]*Y[27]*Z[1];
	FY[7] = Z[39]*Z[1];
	FX[1] = (Z[40]-Z[0]*Y[48]*Y[110])*Z[1];
	if( Y[2]>=0. )
		td1 = Y[2];
	else
		td1 = -Y[2];
	Y[31] = 9.5493*td1;
	if( Y[2]>=0. )
		ti1 = 1;
	else
		ti1 = -1;
	Z[41] = 9.5493*((real_T)ti1);
	Z[0] = 1.5*Y[88];
	Y[34] = Z[0]*(Y[0]*Y[26]-Y[1]*Y[27]);
	Z[42] = 1.*Z[0]*(Y[26]-Z[38]*Y[1]);
	Z[43] = Z[0]*(Z[34]*Y[0]-Y[27]);
	Z[44] = Z[0]*Z[35]*Y[0];
	if( Y[104]<Y[31] )
		Y[32] = Y[104];
	else if( Y[31]<Y[97] )
		Y[32] = Y[97];
	else
		Y[32] = Y[31];
	if( Y[104]<Y[31] )
		Z[45] = 0.;
	else if( Y[31]<Y[97] )
		Z[45] = 0.;
	else
		Z[45] = Z[41];
	for(ti2=0;ti2<=4;ti2++)
		for(ti3=0;ti3<=4;ti3++)
			M[ti2*10+ti3] = 0.;
	for(ti2=0;ti2<=4;ti2++)
		V[ti2] = 0.;
	M[4] = 1.;
	Z[93] = dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_LUT_U_46_U_LUT_U_row_U_selector_U_46_U_proc(Y[32],Y[97],Y[98],Y[99],Y[100],Y[101],Y[102],Y[103],Y[104],Y[89],Y[90],Y[91],Y[92],Y[93],Y[94],Y[95],Y[96],&Z[89],&Z[90],&Z[91],&Z[92]);
	V[0] = Z[93];
	M[10] = 1.;
	V[1] = Z[89];
	M[21] = 1.;
	V[2] = Z[90];
	M[32] = 1.;
	V[3] = Z[91];
	M[43] = 1.;
	V[4] = Z[92];
	LSQDecompSolve(5,M,10,P,V);
	if( P[4]==0 ) {
		FX[0] = (*dsn_undef);
		return;
	}
	Y[14] = V[0];
	Y[15] = V[1];
	Y[16] = V[2];
	Y[17] = V[3];
	Y[18] = V[4];
	for(ti2=0;ti2<=4;ti2++)
		for(ti3=0;ti3<=0;ti3++)
			B[ti2*5+ti3] = 0.;
	Z[89] = 0.;
	Z[90] = 0.;
	Z[91] = 0.;
	Z[92] = 0.;
	Z[93] = 0.;
	Mt1[0] = ( (0.00001*fabs(Y[32])<1e-07) ? 1e-07 : 0.00001*fabs(Y[32]) );
	Mt1[1] = Z[45]/(2.*Mt1[0]);
	Mr5 = dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_LUT_U_46_U_LUT_U_row_U_selector_U_46_U_proc(Y[32]+Mt1[0],Y[97],Y[98],Y[99],Y[100],Y[101],Y[102],Y[103],Y[104],Y[89],Y[90],Y[91],Y[92],Y[93],Y[94],Y[95],Y[96],&Mr1,&Mr2,&Mr3,&Mr4);
	Z[89] = Mt1[1]*Mr1+Z[89];
	Z[90] = Mt1[1]*Mr2+Z[90];
	Z[91] = Mt1[1]*Mr3+Z[91];
	Z[92] = Mt1[1]*Mr4+Z[92];
	Z[93] = Mt1[1]*Mr5+Z[93];
	Mr5 = dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_LUT_U_46_U_LUT_U_row_U_selector_U_46_U_proc(Y[32]-Mt1[0],Y[97],Y[98],Y[99],Y[100],Y[101],Y[102],Y[103],Y[104],Y[89],Y[90],Y[91],Y[92],Y[93],Y[94],Y[95],Y[96],&Mr1,&Mr2,&Mr3,&Mr4);
	Z[89] = Z[89]-Mt1[1]*Mr1;
	Z[90] = Z[90]-Mt1[1]*Mr2;
	Z[91] = Z[91]-Mt1[1]*Mr3;
	Z[92] = Z[92]-Mt1[1]*Mr4;
	Z[93] = Z[93]-Mt1[1]*Mr5;
	B[0] = Z[93];
	B[5] = Z[89];
	B[10] = Z[90];
	B[15] = Z[91];
	B[20] = Z[92];
	LSQMultiSolve(5,M,10,P,1,B,5);
	Z[46] = B[0];
	Z[47] = B[5];
	Z[48] = B[10];
	Z[49] = B[15];
	Z[50] = B[20];
	Z[0] = Y[32]-Y[14];
	Z[1] = Y[15]-Y[32];
	Z[2] = Y[14]-Y[15];
	Z[2] = 1.0/Z[2];
	Z[3] = (Z[1]*Y[16]+Z[0]*Y[17])*Z[2];
	Y[33] = -Z[3]*Y[105];
	Z[51] = Z[2]*Y[105]*(Z[3]*(Z[46]-Z[47])+(Z[45]-Z[47])*Y[16]+(Z[46]-Z[45])*Y[17]-Z[0]*Z[49]-Z[1]*Z[48]);
	Y[19] = (dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_Rotational_U_Losses_U_46_U_Rot_U_Loss_U_tau_U_46_U_proc(Y[2],Y[106],Y[33]));
	Z[52] = (D_U_1_U_dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_Rotational_U_Losses_U_46_U_Rot_U_Los977557812489(Y[2],Y[106],Y[33]))+(D_U_3_U_dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_Rotational_U_Losses_U_46_U_Rot_U_Los700160257958(Y[2],Y[106],Y[33]))*Z[51];
	Y[30] = -(Y[55]+Y[19]);
	Z[53] = -Z[52];
	Z[54] = -Y[49];
	Z[0] = 1.0/Y[69];
	YP[2] = 1.*(Y[30]+Y[34]-Y[2]*Y[60])*Z[0];
	FY[8] = Z[42]*Z[0];
	FY[9] = Z[43]*Z[0];
	FY[10] = 1.*(Z[53]-Y[60])*Z[0];
	FX[2] = (Z[54]+Z[44])*Z[0];
}

static int_T eex(int_T N, real_T T, real_T *Y, real_T *Ypre)
{
	UNUSED(T);
	UNUSED(Ypre);
	if( N==1 ) {
		if( !(Y[61]<=Y[68]) ) {
			Y[59] = 1.;
			return(1);
		}
		if( !(Y[61]<=Y[68]) ) {
			Y[59] = 2.;
			return(1);
		}
		if( !(Y[97]<=Y[104]) ) {
			Y[59] = 3.;
			return(1);
		}
	}
	return(0);
}

static void terminate(SimStruct *S, real_T T, real_T *Y, int_T j)
{
	char buf[10000];

	if(j==1) {
		sprintf(buf,"Modelica assertion (Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.I_pk0 <= Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.I_pk7) failed in Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.bPM_motor_complete.Inductance_saturation.LUT_Ld.limiter: Limiter: Limits must be consistent. However, uMax (=%0.6g) < uMin (=%0.6g)",Y[68],Y[61]);
		ssSetErrorStatus(S,buf);
	}
	if(j==2) {
		sprintf(buf,"Modelica assertion (Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.I_pk0 <= Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.I_pk7) failed in Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.bPM_motor_complete.Inductance_saturation.LUT_Lq.limiter: Limiter: Limits must be consistent. However, uMax (=%0.6g) < uMin (=%0.6g)",Y[68],Y[61]);
		ssSetErrorStatus(S,buf);
	}
	if(j==3) {
		sprintf(buf,"Modelica assertion (Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Rot_Loss_Speed0 <= Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.Rot_Loss_Speed7) failed in Main.bpm_dq_S_noH_noD_RL_Dyno_high_speed.bPM_motor_complete.rot_loss_power.LUT_Rot_Loss.limiter: Limiter: Limits must be consistent. However, uMax (=%0.6g) < uMin (=%0.6g)",Y[104],Y[97]);
		ssSetErrorStatus(S,buf);
	}
}

static void numdiffinp(real_T *w, int_T initial)
{
	real_T dt1,dt2,idt1,idt2,idt12,*nd1,*nd2;

	nd1=w+1+2*NEQ+NPAR+NDFA+NEVT;
	nd2=nd1+7;
	if(!initial && w[0]-nd1[0]==0.0) {
		nd1[1]=w[54];
		nd1[2]=w[55];
		nd1[3]=w[56];
		nd1[4]=w[57];
		nd1[5]=w[58];
		nd1[6]=w[59];
	}
	if(!initial && w[0]-nd1[0]>0.0) {
		dt1=w[0]-nd1[0]; idt1=1.0/dt1;
		if(nd1[0]-nd2[0]>0.0) {
			dt2=w[0]-nd2[0]; idt2=1.0/dt2;
			idt12=1.0/(nd2[0]-nd1[0]);
			w[48]=(idt1+idt2)*w[54]+idt12*(dt2*idt1*nd1[1]-dt1*idt2*nd2[1]);
			w[49]=(idt1+idt2)*w[55]+idt12*(dt2*idt1*nd1[2]-dt1*idt2*nd2[2]);
			w[50]=(idt1+idt2)*w[56]+idt12*(dt2*idt1*nd1[3]-dt1*idt2*nd2[3]);
			w[51]=(idt1+idt2)*w[57]+idt12*(dt2*idt1*nd1[4]-dt1*idt2*nd2[4]);
			w[52]=(idt1+idt2)*w[58]+idt12*(dt2*idt1*nd1[5]-dt1*idt2*nd2[5]);
			w[53]=(idt1+idt2)*w[59]+idt12*(dt2*idt1*nd1[6]-dt1*idt2*nd2[6]);
		}
		else {
			w[48]=idt1*(w[54]-nd1[1]);
			w[49]=idt1*(w[55]-nd1[2]);
			w[50]=idt1*(w[56]-nd1[3]);
			w[51]=idt1*(w[57]-nd1[4]);
			w[52]=idt1*(w[58]-nd1[5]);
			w[53]=idt1*(w[59]-nd1[6]);
		}
	}
	if(initial || w[0]-nd1[0]>1e-10) {
		nd2[0]=nd1[0]; nd1[0]=w[0];
		nd2[1]=nd1[1]; nd1[1]=w[54];
		nd2[2]=nd1[2]; nd1[2]=w[55];
		nd2[3]=nd1[3]; nd1[3]=w[56];
		nd2[4]=nd1[4]; nd1[4]=w[57];
		nd2[5]=nd1[5]; nd1[5]=w[58];
		nd2[6]=nd1[6]; nd1[6]=w[59];
	}
}

static void mdlCheckParameters(SimStruct *S)
{
	const mxArray *dpar1 = ssGetSFcnParam(S,1);

	if ( mxGetNumberOfElements(ssGetSFcnParam(S,1))!=1 || !IS_PARAM_DOUBLE(dpar1) ) {
		ssSetErrorStatus(S, "Minimum sample step must be a scalar");
		return;
	}
	else if (mxGetPr(ssGetSFcnParam(S,1))[0]<0) {
		ssSetErrorStatus(S, "Minimum sample step must be non-negative");
		return;
	}
}

static void mdlInitializeSizes(SimStruct *S)
{
	ssSetNumSFcnParams(S, NDPAR);
	if( ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S) ) {
		return;
	}
	else {
		mdlCheckParameters(S);
		if (ssGetErrorStatus(S) != NULL) return;
	}
	ssSetNumContStates(S, 0);
	ssSetNumDiscStates(S, NDIFF);

	if( !ssSetNumInputPorts(S, 3) ) return;
	ssSetInputPortWidth(S, 0, NDIFF);
	ssSetInputPortDirectFeedThrough(S, 0, 1);
	ssSetInputPortWidth(S, 1, NPAR);
	ssSetInputPortDirectFeedThrough(S, 1, 1);
	ssSetInputPortWidth(S, 2, NINP);
	ssSetInputPortDirectFeedThrough(S, 2, 1);

	if( !ssSetNumOutputPorts(S, 1) ) return;
	ssSetOutputPortWidth(S, 0, NOUT);

	ssSetNumSampleTimes(S, 1);
	ssSetNumRWork(S, 15+2*NEQ+NPAR+NDFA+NEVT);
	ssSetNumIWork(S, 2*NEVT+2*NZC+1);
	ssSetNumPWork(S, 0);
	ssSetNumModes(S, 0);
	ssSetNumNonsampledZCs(S, 0);

	ssSetOptions(S, SS_OPTION_EXCEPTION_FREE_CODE);
	ssSetOptions(S, SS_OPTION_CALL_TERMINATE_ON_EXIT);
}

/*Enabling multiple execution instances*/
#define MDL_SET_WORK_WIDTHS
static void mdlSetWorkWidths(SimStruct *S)
{   
    /*Enabling multiple execution instances*/
    ssSupportsMultipleExecInstances(S, true);
}


static void mdlInitializeSampleTimes(SimStruct *S)
{
	ssSetSampleTime(S, 0, TIMESTEP);
	ssSetOffsetTime(S, 0, 0.0);
	ssSetModelReferenceSampleTimeDefaultInheritance(S);
}

static void InitializeConditions(SimStruct *S)
{
	real_T *w = ssGetRWork(S);
	real_T *x = ssGetDiscStates(S);
	InputRealPtrsType i = ssGetInputPortRealSignalPtrs(S,2);
	InputRealPtrsType p = ssGetInputPortRealSignalPtrs(S,1);
	int_T j;

	if (fptr) {
		fclose(fptr);
		fptr = NULL;
	}
	mxGetString(ssGetSFcnParam(S,0),fstr,MAXSTRLENGTH);
	if (fstr!="\0")
		fptr = fopen(fstr,"wb");
	minsamplestep = (mxGetPr(ssGetSFcnParam(S,1)))[0];
	lastsampletime = -1e10;
	numpts = 0;

	w[0] =  0.0;
	w[1] =  0.00000000000000000e+00;
	w[2] =  0.00000000000000000e+00;
	w[3] =  0.00000000000000000e+00;
	w[4] =  0.00000000000000000e+00;
	w[5] =  0.00000000000000000e+00;
	w[6] =  1.00000000000000000e+00;
	w[7] =  2.11700000000000010e-02;
	w[8] =  2.11700000000000010e-02;
	w[9] =  1.00000000000000000e+00;
	w[10] =  0.00000000000000000e+00;
	w[11] =  1.00000000000000000e+00;
	w[12] =  2.74399999999999990e-02;
	w[13] =  2.77700000000000000e-02;
	w[14] =  1.00000000000000000e+00;
	w[15] =  0.00000000000000000e+00;
	w[16] =  5.00000000000000000e+02;
	w[17] =  0.00000000000000000e+00;
	w[18] =  1.00000000000000000e+00;
	w[19] =  1.00000000000000000e+00;
	w[20] =  0.00000000000000000e+00;
	w[21] =  0.00000000000000000e+00;
	w[22] =  0.00000000000000000e+00;
	w[23] =  0.00000000000000000e+00;
	w[24] =  0.00000000000000000e+00;
	w[25] =  2.11700000000000010e-02;
	w[26] =  2.74399999999999990e-02;
	w[27] =  1.20079226000000000e-01;
	w[28] =  0.00000000000000000e+00;
	w[29] =  0.00000000000000000e+00;
	w[30] =  0.00000000000000000e+00;
	w[31] = -1.00000000000000000e+00;
	w[32] =  0.00000000000000000e+00;
	w[33] =  0.00000000000000000e+00;
	w[34] =  0.00000000000000000e+00;
	w[35] =  0.00000000000000000e+00;
	w[36] =  0.00000000000000000e+00;
	w[37] =  0.00000000000000000e+00;
	w[38] =  0.00000000000000000e+00;
	w[39] = -0.00000000000000000e+00;
	w[40] =  0.00000000000000000e+00;
	w[41] =  0.00000000000000000e+00;
	w[42] =  0.00000000000000000e+00;
	w[43] =  0.00000000000000000e+00;
	w[44] =  0.00000000000000000e+00;
	w[45] =  0.00000000000000000e+00;
	w[46] =  0.00000000000000000e+00;
	w[47] =  0.00000000000000000e+00;
	w[48] =  0.00000000000000000e+00;
	w[49] =  0.00000000000000000e+00;
	w[50] =  0.00000000000000000e+00;
	w[51] =  0.00000000000000000e+00;
	w[52] =  0.00000000000000000e+00;
	w[53] =  0.00000000000000000e+00;
	w[54] =  1.00000000000000000e+00;
	w[55] =  1.00000000000000000e+00;
	w[56] =  1.00000000000000000e+00;
	w[57] =  1.00000000000000000e+00;
	w[58] =  1.00000000000000000e+00;
	w[59] =  1.00000000000000000e+00;
	w[60] =  0.00000000000000000e+00;
	w[61] =  1.00000000000000000e-04;
	w[62] =  0.00000000000000000e+00;
	w[63] =  1.00000000000000000e+00;
	w[64] =  2.00000000000000000e+00;
	w[65] =  3.00000000000000000e+00;
	w[66] =  4.00000000000000000e+00;
	w[67] =  5.00000000000000000e+00;
	w[68] =  6.00000000000000000e+00;
	w[69] =  7.00000000000000000e+00;
	w[70] =  5.15000000000000050e-04;
	w[71] =  8.84000000000000060e-02;
	w[72] =  2.11700000000000010e-02;
	w[73] =  2.11700000000000010e-02;
	w[74] =  2.11700000000000010e-02;
	w[75] =  2.11700000000000010e-02;
	w[76] =  2.11700000000000010e-02;
	w[77] =  2.11700000000000010e-02;
	w[78] =  2.11700000000000010e-02;
	w[79] =  2.11700000000000010e-02;
	w[80] =  9.71999999999999950e-02;
	w[81] =  2.74399999999999990e-02;
	w[82] =  2.77700000000000000e-02;
	w[83] =  2.74200000000000000e-02;
	w[84] =  2.64600000000000010e-02;
	w[85] =  2.42600000000000000e-02;
	w[86] =  2.32900000000000020e-02;
	w[87] =  2.24099999999999990e-02;
	w[88] =  2.24099999999999990e-02;
	w[89] =  3.00000000000000000e+00;
	w[90] =  0.00000000000000000e+00;
	w[91] =  1.00000000000000000e+00;
	w[92] =  1.20000000000000000e+01;
	w[93] =  1.90000000000000000e+01;
	w[94] =  2.60000000000000000e+01;
	w[95] =  3.50000000000000000e+01;
	w[96] =  4.10000000000000000e+01;
	w[97] =  5.60000000000000000e+01;
	w[98] =  0.00000000000000000e+00;
	w[99] =  5.00000000000000000e+02;
	w[100] =  3.00000000000000000e+03;
	w[101] =  4.00000000000000000e+03;
	w[102] =  5.00000000000000000e+03;
	w[103] =  7.00000000000000000e+03;
	w[104] =  1.20000000000000000e+04;
	w[105] =  1.80000000000000000e+04;
	w[106] =  1.00000000000000000e+00;
	w[107] =  1.00000000000000000e+01;
	w[108] =  9.15000000000000040e+00;
	w[109] =  2.20000000000000000e+01;
	w[110] =  2.20000000000000000e+01;
	w[111] =  4.00000000000000010e-03;
	w[112] =  2.06000000000000020e-03;
	w[113] =  1.15099999999999990e-01;

	for(j=0;j<NDIFF;j++) w[NEQ+NPAR+j+1]=0.0;

	for(j=0;j<NINP;j++) w[j+NDIFF+NIX1-NINP+1]=i[j][0];
	numdiffinp(w,1);
	numdiffinp(w,1);
	for(j=0;j<NDIFF;j++) w[j+1]=x[j];
	for(j=0;j<NPAR;j++) w[j+NEQ+1]=p[j][0];
	if (fptr) {
		fwrite(nData,sizeof(real_T),2,fptr);
		fwrite(&w[NEQ+1],sizeof(real_T),NPAR,fptr);
	}

	w[NEQ+NPAR+1]=0.0;
	if(NIX1>0) {
		fp(NEQ,w[0],&w[1],&w[NEQ+NPAR+1]);
		if( IS_UNDEF(w[NEQ+NPAR+1]) ) {
			ssSetErrorStatus(S,"index-1 and derivative evaluation failure");
			if (fptr) {
				writeErrorToFile(fptr,ssGetErrorStatus(S));
				fptr = NULL;
			}
			return;
		}
	}
	for(j=0;j<NEQ;j++) w[1+NEQ+NPAR+NDFA+j]=w[1+j];
	eex(1,w[0],&w[1],&w[1+NEQ+NPAR+NDFA]);
	if( w[60]>0.0 )
		terminate(S,w[0],&w[1],(int_T)(w[60]));
	for(j=0;j<NEQ;j++) w[1+NEQ+NPAR+NDFA+j]=w[1+j];
	eex(1,w[0],&w[1],&w[1+NEQ+NPAR+NDFA]);
	if(NIX1>0) {
		fp(NEQ,w[0],&w[1],&w[NEQ+NPAR+1]);
		if( IS_UNDEF(w[NEQ+NPAR+1]) ) {
			ssSetErrorStatus(S,"index-1 and derivative evaluation failure");
			if (fptr) {
				writeErrorToFile(fptr,ssGetErrorStatus(S));
				fptr = NULL;			}
			return;
		}
	}
	for(j=0;j<NDIFF;j++) x[j]=w[j+1];
}

#define MDL_INITIALIZE_CONDITIONS
static void mdlInitializeConditions(SimStruct *S)
{
	InputRealPtrsType ic = ssGetInputPortRealSignalPtrs(S,0);
	real_T *x = ssGetDiscStates(S);
	int_T *iw = ssGetIWork(S);
	int_T j;

	iw[INIDREF]=0;
	for(j=0;j<NDIFF;j++) x[j]=ic[j][0];
}

static real_T *GetUpdatedWork(SimStruct *S, int_T getnofeed)
{
	int_T j,flag;

	real_T *w = ssGetRWork(S);
	real_T t = ssGetT(S);
	real_T *x = ssGetDiscStates(S);
	InputRealPtrsType i;
	InputRealPtrsType p = ssGetInputPortRealSignalPtrs(S,1);

	flag=0;
	if( fabs(w[0]-t)>1e-6*TIMESTEP ) flag=1;
	w[0]=t;
	for(j=0;j<NDIFF;j++) if( w[j+1]!=x[j] ) { flag=1; w[j+1]=x[j]; }
	i = ssGetInputPortRealSignalPtrs(S,2);
	for(j=0;j<NINP;j++) if( w[j+NDIFF+NIX1-NINP+1]!=i[j][0] ) { flag=1; w[j+NDIFF+NIX1-NINP+1]=i[j][0]; }
	for(j=0;j<NPAR;j++) if( w[j+NEQ+1]!=p[j][0] ) { flag=1; w[j+NEQ+1]=p[j][0]; }
	if(flag) numdiffinp(w,0);

	if(flag) {
		fp(NEQ,w[0],&w[1],&w[NEQ+NPAR+1]);
		if( IS_UNDEF(w[NEQ+NPAR+1]) ) {
			if( NDIFF>0 && ssIsVariableStepSolver(S) )
				for(j=1;j<NDIFF;j++) w[NEQ+NPAR+1+j] = w[NEQ+NPAR+1];
			else
			{
				ssSetErrorStatus(S,"index-1 and derivative evaluation failure");
				if (fptr) {
					writeErrorToFile(fptr,ssGetErrorStatus(S));
					fptr = NULL;				}
			}
		}
	}

	return(w);
}

static void ImplicitEulerStep(real_T *w)
{
	M_INT ip[NDFA];
	int_T i,j;
	real_T ft[NDFA],fy[NDFA*NDFA];

	Dfp(w[0],&w[1],ft,fy);
	for(i=0;i<NDIFF;i++) {
		for(j=0;j<NDIFF;j++) fy[i*NDIFF+j]=-fy[i*NDIFF+j];
		fy[i*(NDIFF+1)]+=1.0/TIMESTEP;
		ft[i]=w[1+NEQ+NPAR+i]+TIMESTEP*ft[i];
	}
	DecompCInc(NDIFF,fy,NDIFF,ip);
	SolveCInc(NDIFF,fy,NDIFF,ip,ft);
	w[0]+=TIMESTEP;
	for(i=0;i<NDIFF;i++) w[i+1]+=ft[i];
}


#define MDL_UPDATE
static void mdlUpdate(SimStruct *S, int_T tid)
{
	real_T *w, *x = ssGetDiscStates(S);
	int_T i;

	UNUSED_ARG(tid);

	w=GetUpdatedWork(S,1);
	ImplicitEulerStep(w);

	fp(NEQ,w[0],&w[1],&w[NEQ+NPAR+1]);
	if( IS_UNDEF(w[NEQ+NPAR+1]) )
		{
			ssSetErrorStatus(S,"index-1 and derivative evaluation failure");
			if (fptr) {
				writeErrorToFile(fptr,ssGetErrorStatus(S));
				fptr = NULL;
			}
			return;
		}
	for(i=0;i<NDIFF;i++) x[i]=w[i+1];
}

static void mdlOutputs(SimStruct *S, int_T tid)
{
	real_T *w, *y = ssGetOutputPortRealSignal(S,0);
	int_T *iw = ssGetIWork(S);

	UNUSED_ARG(tid);

	if(!iw[INIDREF]) {
		InitializeConditions(S);
		iw[INIDREF]=1;
	}
	if( ssIsVariableStepSolver(S) ) {
		ssSetErrorStatus(S,"code generated for fixed step, cannot be used with variable step");
		if (fptr) {
			writeErrorToFile(fptr,ssGetErrorStatus(S));
			fptr = NULL;
		}
		return;
	}
	w=GetUpdatedWork(S,0);
	otp(w[0],&w[1],&w[NEQ+NPAR+1]);
	y[ 0]=w[25];
	y[ 1]=w[26];
	y[ 2]=w[36];
	y[ 3]=w[37];
	y[ 4]=w[38];
	y[ 5]=w[39];
	y[ 6]=w[40];
	y[ 7]=w[41];
	y[ 8]=w[ 2];
	y[ 9]=w[ 1];
	y[10]=w[43];
	y[11]=w[ 3];
	y[12]=w[42];
	y[13]=w[44];
	y[14]=w[34];
	y[15]=w[45];
	y[16]=w[20];
	y[17]=w[46];
	y[18]=w[35];
	y[19]=w[47];
	y[20]=w[ 4];
 	if ( fptr && ssIsMajorTimeStep(S) )
		if ( w[0]>=(lastsampletime+minsamplestep)*(1-1e-15) ) {
			fwrite(w,sizeof(real_T),NEQ+1,fptr);
			lastsampletime=w[0];
			if ( numpts++ == WARNNUMDATPTS )
				ssPrintf("Warning: At time t=%.16g, %d data points were written into file %s; consider increasing the minimum sample step, %.16g, to limit file size.\n",
						w[0],WARNNUMDATPTS,fstr,minsamplestep);
		}
}

static void mdlTerminate(SimStruct *S) {
	if (fptr) {
		fclose(fptr);
		fptr = NULL;
	}
}

#ifdef  MATLAB_MEX_FILE    /* Being compiled as a MEX-file? */
#include "simulink.c"      /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"       /* Code generation registration function */
#endif
