function run_motor_bpm_xml(filename)
c=xmlread(filename);

%--- Electrical Parameters-----%
s1={ 'Rs_a_Ref'...
    'Rs_b_Ref'...
    'Rs_c_Ref'...
    'p_Pole_Pairs'...
    'PM_Flux_f01'...
    'PM_Flux_f02'...
    'PM_Flux_f03'...
    'PM_Flux_f04'...
    'PM_Flux_f05'...
    'PM_Flux_f06'...
    'PM_Flux_f07'...
    'PM_Flux_f08'...
    'PM_Flux_f09'...
    'PM_Flux_f10'...
    'PM_Flux_f11'...
    'PM_Flux_f12'...
    'PM_Flux_f13'...
    'ajust'...
    'alpha_s'};

%--Mechanical Parameters-----%
s2={'Jrotor'...
    'B'...
    'Jadd'...
    'Rs_Temperature_Ref'...
    'PM_Temperature_Ref'...
    'TR'};

%---Power Loss Parameters-----%
s3={'Rot_Loss_Flag'...
    'Rot_Loss_Speed0'...
    'Rot_Loss_Speed1'...
    'Rot_Loss_Speed2'...
    'Rot_Loss_Speed3'...
    'Rot_Loss_Speed4'...
    'Rot_Loss_Speed5'...
    'Rot_Loss_Speed6'...
    'Rot_Loss_Speed7'...
    'Rot_Loss_Power0'...
    'Rot_Loss_Power1'...
    'Rot_Loss_Power2'...
    'Rot_Loss_Power3'...
    'Rot_Loss_Power4'...
    'Rot_Loss_Power5'...    
    'Rot_Loss_Power6'...
    'Rot_Loss_Power7'};

%-- Inductance Variation Parameters----%
s4={'Ld_a0'...
    'Ld_a1'...
    'Ld_a2'...
    'Ld_a3'...
    'Ld_a4'...
    'Ld_a5'...
    'Ld_a6'...
    'Ld_a7'...
    'Lq_b0'...
    'Lq_b1'...
    'Lq_b2'...
    'Lq_b3'...
    'Lq_b4'...
    'Lq_b5'...
    'Lq_b6'...
    'Lq_b7'...
    'I_pk0'...
    'I_pk1'...
    'I_pk2'...
    'I_pk3'...
    'I_pk4'...
    'I_pk5'...
    'I_pk6'...
    'I_pk7'};

%---Motor Variant Details----%
s5={'MotorVariant'};

[a1 b1]=size(s1);
[a2 b2]=size(s2);
[a3 b3]=size(s3);
[a4 b4]=size(s4);
[a5 b5]=size(s5);

z={'0'};
evalin('base','Motor=struct;');
entries =c.getChildNodes;
friendlyInfo = entries.item(0).getChildNodes;
node = friendlyInfo.getFirstChild;
%% Loading Electrical Parameter Structure
for i=1:1:b1
    m(i)=s1(i);
    friendlyInfo = entries.item(0).getChildNodes;
    node = friendlyInfo.getFirstChild;
    while ~isempty(node)
        if strcmpi(node.getNodeName, s1(i))
            break;
        else
            node = node.getNextSibling;
        end
    end
    h(i)= str2double(char(node.getTextContent));
    assignin('base','temp',h(i));
    m(i)= node.getNodeName;
    assignin('base','temp_string',m(i));
    evalin('base','Motor.Electrical.(char(temp_string))=temp;');
    
end
evalin('base','clear temp');
evalin('base','clear temp_string');
%% Loading Mechanical Parameter Structure

for i=1:1:b2
    m(i)=s2(i);
    friendlyInfo = entries.item(0).getChildNodes;
    node = friendlyInfo.getFirstChild;
    while ~isempty(node)
        if strcmpi(node.getNodeName, s2(i))
            break;
        else
            node = node.getNextSibling;
        end
    end
    h(i)= str2double(char(node.getTextContent));
    assignin('base','temp',h(i));
    m(i)= node.getNodeName;
    assignin('base','temp_string',m(i));
    evalin('base','Motor.Mechanical.(char(temp_string))=temp;');
    
end
evalin('base','clear temp');
evalin('base','clear temp_string');
%% Loading Power Loss Parameter Structure
for i=1:1:b3
    m(i)=s3(i);
    friendlyInfo = entries.item(0).getChildNodes;
    node = friendlyInfo.getFirstChild;
    while ~isempty(node)
        if strcmpi(node.getNodeName, s3(i))
            break;
        else
            node = node.getNextSibling;
        end
    end
    h(i)= str2double(char(node.getTextContent));
    assignin('base','temp',h(i));
    m(i)= node.getNodeName;
    assignin('base','temp_string',m(i));
    evalin('base','Motor.Power_Loss.(char(temp_string))=temp;');
    
end
evalin('base','clear temp');
evalin('base','clear temp_string');
%% loading Inductance Variation Parameter Structure
for i=1:1:b4
    m(i)=s4(i);
    friendlyInfo = entries.item(0).getChildNodes;
    node = friendlyInfo.getFirstChild;
    while ~isempty(node)
        if strcmpi(node.getNodeName, s4(i))
            break;
        else
            node = node.getNextSibling;
        end
    end
    if isempty(node)
        error(['Variable ' s4{i} ' is expected for simulation, but was not found in XML database']);
    end
    h(i)= str2double(char(node.getTextContent));
    assignin('base','temp',h(i));
    m(i)= node.getNodeName;
    assignin('base','temp_string',m(i));
    evalin('base','Motor.Inductance_Variation.(char(temp_string))=temp;');
    
end
evalin('base','clear temp');
evalin('base','clear temp_string');

%% Loading Motor Variant Information
for i=1:1:b5
    m(i)=s5(i);
    friendlyInfo = entries.item(0).getChildNodes;
    node = friendlyInfo.getFirstChild;
    while ~isempty(node)
        if strcmpi(node.getNodeName, s5(i))
            break;
        else
            node = node.getNextSibling;
        end
    end
    z(i)= node.getTextContent;
    assignin('base','temp',char(z(i)));
    m(i)= node.getNodeName;
    assignin('base','temp_string',m(i));
    evalin('base','config.(char(temp_string))=temp;');
    
end
evalin('base','clear temp');
evalin('base','clear temp_string');

end


