/***************************************************
 * DO NOT EDIT MANUALLY!
 * Automatically generated by Maple.
 * Created On: Tue Feb 14 10:43:32 2023.
***************************************************/

/* PLATFORM SPECIFICATION (Both commented out for Linux/Mac) */
/* 32-bit Windows */
/*#define WMI_WINNT 1*/
/* 64-bit Windows */
#define X86_64_WINDOWS 1

#define S_FUNCTION_NAME cHVPS_AC120V_PFC_sfun_xk
#define S_FUNCTION_LEVEL 2

#include "simstruc.h"
#include "math.h"

/***************************************************
* Variable Definition for System:

* Discrete state variable(s):
*    x[ 0] = `Main.AC120VPFC1.C_BusCap1.v`(t) (unit = [V])
*    x[ 1] = `Main.AC120VPFC1.C_BusCap2.v`(t) (unit = [V])
*    x[ 2] = `Main.AC120VPFC1.L_PFC.i`(t) (unit = [A])
*    x[ 3] = `Main.AC120VPFC1.slewRateLimiter.y`(t)   (*)
*
* (*) state with fixed initial condition based upon initial equations
*
* Output variable(s):
*    y[ 0] = `Main.AC120VPFC1.SensorIbuscap1.p.v`(t) (unit = [V])
*    y[ 1] = `Main.AC120VPFC1.Ibuscap1`(t)
*    y[ 2] = `Main.AC120VPFC1.SensorIbuscap2.p.i`(t) (unit = [A])
*    y[ 3] = `Main.AC120VPFC1.Id1`(t)
*    y[ 4] = `Main.AC120VPFC1.SensorId2.p.i`(t) (unit = [A])
*    y[ 5] = `Main.AC120VPFC1.SensorId3.p.i`(t) (unit = [A])
*    y[ 6] = `Main.AC120VPFC1.SensorId4.p.i`(t) (unit = [A])
*    y[ 7] = `Main.AC120VPFC1.L_PFC.i`(t) (unit = [A])
*
* Input variable(s):
*    u[ 0] = `Main.AC120VPFC1.AC_Main`(t)
*    u[ 1] = `Main.AC120VPFC1.I_RMS`(t)
*
* Parameter(s):
*    p[ 0] = `Main.AC120VPFC1.C_buscap` (default = .1e-2)
*    p[ 1] = `Main.AC120VPFC1.G_off` (default = .83e-8)
*    p[ 2] = `Main.AC120VPFC1.L_line` (default = .5e-4)
*    p[ 3] = `Main.AC120VPFC1.L_pfc` (default = .3e-2)
*    p[ 4] = `Main.AC120VPFC1.R_buscap` (default = .1)
*    p[ 5] = `Main.AC120VPFC1.R_diode` (default = .5e-2)
*    p[ 6] = `Main.AC120VPFC1.R_line` (default = .6)
*    p[ 7] = `Main.AC120VPFC1.R_pfc` (default = .403)
*    p[ 8] = `Main.AC120VPFC1.ID1.T` (default = 298.15, unit = [K])
*    p[ 9] = `Main.AC120VPFC1.ID1.Vknee` (default = 0., unit = [V])
*    p[10] = `Main.AC120VPFC1.ID2.T` (default = 298.15, unit = [K])
*    p[11] = `Main.AC120VPFC1.ID2.Vknee` (default = 0., unit = [V])
*    p[12] = `Main.AC120VPFC1.ID3.T` (default = 298.15, unit = [K])
*    p[13] = `Main.AC120VPFC1.ID3.Vknee` (default = 0., unit = [V])
*    p[14] = `Main.AC120VPFC1.ID4.T` (default = 298.15, unit = [K])
*    p[15] = `Main.AC120VPFC1.ID4.Vknee` (default = 0., unit = [V])
*    p[16] = `Main.AC120VPFC1.R3.R` (default = .1e-1, unit = [Ohm])
*    p[17] = `Main.AC120VPFC1.R3.T_ref` (default = 298.15, unit = [K])
*    p[18] = `Main.AC120VPFC1.R3.T` (default = 298.15, unit = [K])
*    p[19] = `Main.AC120VPFC1.R4.R` (default = .1e8, unit = [Ohm])
*    p[20] = `Main.AC120VPFC1.R4.T_ref` (default = 298.15, unit = [K])
*    p[21] = `Main.AC120VPFC1.R4.T` (default = 298.15, unit = [K])
*    p[22] = `Main.AC120VPFC1.R_BusCap1.T_ref` (default = 298.15, unit = [K])
*    p[23] = `Main.AC120VPFC1.R_BusCap1.T` (default = 298.15, unit = [K])
*    p[24] = `Main.AC120VPFC1.R_BusCap1.alpha` (default = .4041e-2, unit = [1/K])
*    p[25] = `Main.AC120VPFC1.R_BusCap2.T_ref` (default = 298.15, unit = [K])
*    p[26] = `Main.AC120VPFC1.R_BusCap2.T` (default = 298.15, unit = [K])
*    p[27] = `Main.AC120VPFC1.R_BusCap2.alpha` (default = .4041e-2, unit = [1/K])
*    p[28] = `Main.AC120VPFC1.R_Line.T_ref` (default = 298.15, unit = [K])
*    p[29] = `Main.AC120VPFC1.R_Line.T` (default = 298.15, unit = [K])
*    p[30] = `Main.AC120VPFC1.R_PFC.T_ref` (default = 298.15, unit = [K])
*    p[31] = `Main.AC120VPFC1.R_PFC.T` (default = 298.15, unit = [K])
*    p[32] = `Main.AC120VPFC1.R_PFC.alpha` (default = .4041e-2, unit = [1/K])
*    p[33] = `Main.AC120VPFC1.add.k1` (default = 1.)
*    p[34] = `Main.AC120VPFC1.add.k2` (default = 1.)
*    p[35] = `Main.AC120VPFC1.const.k` (default = .3e-2)
*    p[36] = `Main.AC120VPFC1.slewRateLimiter.Rising` (default = .1e4)
*    p[37] = `Main.AC120VPFC1.slewRateLimiter.Td` (default = .625e-4, unit = [s])
*
* Options:
* Table handling:
*    Export lookup as csv: false
* Optimization:
*    Code optimization level: 3
* Constraint handling:
*    Max projection iterations: 50
*    Error tolerance: .1e-4
*    Apply during events: true
* Event handling:
*    Max event iter: 100
*    Width of event hysteresis band: .1e-6
* Baumgarte constraint stabilization:
*    Apply Baumgarte: false
* Fixed-step integrator:
*    Optimize for fixed-step: true
*    Add failure handling: false
* Discretization:
*    Export as discrete: true
*    Embedded solver: ImplicitEuler
*    Discrete step size: .625e-4
*    Allow intermediate steps: true
*    Number of intermediate steps: 3
*    Tolerance: .1e-8
* Diagnostics:
*    Add outputs for log: false
*
* MapleSim version: 1539851
*
************************************************/

/* Set up visible initial condition mask */
int_T icvis[4] = {
	1,1,1,0};

/* Configurable parameters */
//#define TIMESTEP 6.250000e-05
#define EVTITER 100
#define EVTHYST 1.000000e-07
#define MAXEVENTPERSTEP 20
#define SHORTEVENTRATIO 1.000000e-09
#define INCONTOL 1e200

/* Fixed parameters */
#define NDIFF 4
#define NDFA 4
#define NSDIFF 3
#define NEQ 30
#define NPAR 38
#define NDPAR 3 //Increase from 2 to 3 to enable TIMESTEP propagation from the mask
#define NINP 2
#define NDISC 7
#define NIX1 19
#define NOUT 8
#define NCON 0
#define NEVT 6
#ifdef EVTHYST
#define NZC 2*NEVT
#else
#define NZC NEVT
#endif
#define INIDREF (2*NEVT+2*NZC)
#define DODERREF (2*NEVT+2*NZC+1)

#define MAXSTRLENGTH 1000
#define WARNNUMDATPTS 100000
#define IS_PARAM_DOUBLE(pVal) (mxIsNumeric(pVal) && !mxIsLogical(pVal) &&\
!mxIsEmpty(pVal) && !mxIsSparse(pVal) && !mxIsComplex(pVal) && mxIsDouble(pVal))

static FILE *fptr = NULL;
static char_T fstr[MAXSTRLENGTH];
static real_T nData[2] = {1.0*NEQ,1.0*NPAR};
static real_T lastsampletime;
static real_T minsamplestep;
static int_T numpts;

static real_T TIMESTEP; // Define TIMESTEP

static void writeErrorToFile(FILE *fptr, const char_T *errstr)
{
	const char_T *err, uerr[]="unknown error";
	int_T i;
	real_T d;

	if (errstr)
		err = errstr;
	else
	err = uerr;

	d = -1e10; /*terminate value*/
	fwrite(&d,sizeof(real_T),1,fptr);
	for(i=0;;i++) {
		d = (real_T)err[i];
		fwrite(&d,sizeof(real_T),1,fptr);
		if (!err[i]) break;
	}

	fclose(fptr);
}

static real_T dsn_zero=0.0;
static unsigned char dsn_undefC[8] = { 0, 0, 0, 0, 0, 0, 0xF8, 0x7F };
static real_T *dsn_undef = (real_T *)&dsn_undefC;
static unsigned char dsn_posinfC[8] = { 0, 0, 0, 0, 0, 0, 0xF0, 0x7F };
static real_T *dsn_posinf = (real_T *)&dsn_posinfC;
static unsigned char dsn_neginfC[8] = { 0, 0, 0, 0, 0, 0, 0xF0, 0xFF };
static real_T *dsn_neginf = (real_T *)&dsn_neginfC;
#define trunc(v) ( (v>0.0) ? floor(v) : ceil(v) )
#define IS_UNDEF(a) (a-a!=0. || (a!=0. && a-2.*a==0.))
#define UNUSED(a) ((void)(a))
static double avoidcompilerwarn() { return(dsn_zero+*dsn_undef+*dsn_posinf+*dsn_neginf); }
#ifndef M_INT
# if defined _MINGW64 || defined X86_64_WINDOWS
#  define M_INT long long
# elif defined __x86_64__ || defined __ppc64__
#  define M_INT long
# elif defined _M_X64
#  define M_INT long long
# else
#  define M_INT long
# endif
#endif


#ifdef MSVC
#pragma optimize( "gty", on)
#endif
#ifndef INCONTOL
#define INCONTOL 1e-14
#endif

static void LSQDecompSolve(M_INT n, real_T *A, M_INT Ainc, M_INT *ip, real_T *b)
{
	M_INT i,j,k,r,c,lsq,cp;
	real_T s,t;

	for(i=0;i<n;i++) {
		if(b[i]-b[i]!=0.0 || (b[i]!=0. && b[i]-2.*b[i]==0.)) { ip[n-1]=0; A[0]=1.; for(j=0;j<n;j++) b[j]=*dsn_undef; return; }
		t = fabs(A[i*Ainc]);
		for(j=1;j<n;j++) {
			s = fabs(A[i*Ainc+j]);
			if(s>t) t = s;
		}
		if( t==0.0 )
			A[i*Ainc+n] = 1.0;
		else {
			t = 1.0/t;
			for(j=0;j<n;j++) A[i*Ainc+j] *= t;
			b[i] *= t;
			A[i*Ainc+n] = t;
		}
	}

	for(j=0;j<n;j++) {
		t = fabs(A[j]);
		for(i=1;i<n;i++) {
			s = fabs(A[i*Ainc+j]);
			if(s>t) t = s;
		}
		if( t==0.0 )
			A[n*Ainc+j] = 1.0;
		else {
			t = 1.0/t;
			for(i=0;i<n;i++) A[i*Ainc+j] *= t;
			A[n*Ainc+j] = t;
		}
	}

	ip[n-1] = 0;
	lsq = 0;
	cp = 0;
	for(k=0;k<n;k++) {
		r = 0; c = 0; t = 0.0;
		if( cp<n ) {
			for(cp=cp+1;cp<n;cp++) {
				for(i=k;i<n;i++) {
					s = fabs(A[i*Ainc+cp]);
					if(s>t) { r = i; c = cp; t = s; }
				}
				if( t>0.5 ) break;
			}
		}
		if( cp>=n ) {
			for(i=k;i<n;i++)
				for(j=k;j<n;j++) {
					s = fabs(A[i*Ainc+j]);
					if(s>t) { r = i; c = j; t = s; }
				}
		}
		if( t<1e-10 ) {
			if( k==0 ) { ip[n-1]=0; A[0]=2.; for(j=0;j<n;j++) b[j]=*dsn_undef; return; }
			if( lsq ) { ip[n-1]=0; A[0]=3.; for(j=0;j<n;j++) b[j]=*dsn_undef; return; }
			lsq = 1;
			t = 1e-16;
			for(i=0;i<k;i++) {
				s = fabs(b[i]);
				if(s>t) t = s;
			}
			for(i=k;i<n;i++) {
				if( fabs(b[i])/t>INCONTOL*n ) { ip[n-1]=0; A[0]=4.; for(j=0;j<n;j++) b[j]=*dsn_undef; return; }
				b[i] = 0.0;
			}

			for(r=k;r<n;r++) {
				for(i=k;i<n;i++) A[i*Ainc+n+r] = 0.0;
				A[r*Ainc+n+r] = 1.0;
				A[(k-1)*Ainc+n+r] = -A[(k-1)*Ainc+r]/A[(k-1)*Ainc+k-1];
				for(i=k-1;i>=0;i--) {
					A[i*Ainc+n+r] = A[i*Ainc+r];
					for(j=i+1;j<k;j++)
						A[i*Ainc+n+r] += A[i*Ainc+j]*A[j*Ainc+n+r];
					A[i*Ainc+n+r] = -A[i*Ainc+n+r]/A[i*(Ainc+1)];
				}
			}
			for(r=0;r<k;r++) {
				s = -1.0/A[r*(Ainc+1)];
				for(i=k;i<n;i++)
					if( A[r*Ainc+n+i]!=0.0 ) {
						t = s*A[r*Ainc+n+i];
						A[i*Ainc+r] += t;
						for(j=r+1;j<n;j++)
							A[j*Ainc+n+i] += t*A[r*Ainc+j];
						b[i] += t*b[r];
					}
			}
			for(i=k;i<n;i++)
				for(j=k;j<n;j++)
					A[i*Ainc+j] = A[j*Ainc+n+i];
			r = 0; c = 0; t = 0.0;
			for(i=k;i<n;i++)
				for(j=k;j<n;j++) {
					s = fabs(A[i*Ainc+j]);
					if(s>t) { r = i; c = j; t = s; }
				}
			if( t<1e-10 ) { ip[n-1]=0; A[0]=3.; for(j=0;j<n;j++) b[j]=*dsn_undef; return; }
		}
		if( !lsq ) ip[n-1]++;
		if( k==n-1 ) break;
		ip[k] = r;
		ip[n+k] = c;
		if( r>k ) {
			for(j=0;j<n;j++) {
				t = A[r*Ainc+j]; A[r*Ainc+j] = A[k*Ainc+j]; A[k*Ainc+j] = t;
			}
			t = b[r]; b[r] = b[k]; b[k] = t;
		}
		if( c>k )
			for(i=0;i<n;i++) {
				t = A[i*Ainc+c]; A[i*Ainc+c] = A[i*Ainc+k]; A[i*Ainc+k] = t;
			}
		s = -1.0/A[k*(Ainc+1)];
		for(i=k+1;i<n;i++)
			if( A[i*Ainc+k]!=0.0 ) {
				t = s*A[i*Ainc+k];
				A[i*Ainc+k] = t;
				for(j=k+1;j<n;j++)
					A[i*Ainc+j] += t*A[k*Ainc+j];
				b[i] += t*b[k];
			}
	}
	for(j=n-1;j>0;j--) {
		b[j] = b[j]/A[j*(Ainc+1)];
		t = -b[j];
		for(i=0;i<j;i++)
			b[i] += t*A[i*Ainc+j];
	}
	b[0] = b[0]/A[0];
	for(j=n-2;j>=0;j--) {
		i = ip[n+j];
		if(i!=j) {
			t = b[i]; b[i] = b[j]; b[j] = t;
		}
	}
	for(j=0;j<n;j++) b[j] *= A[n*Ainc+j];
}
#ifdef MSVC
#pragma optimize( "", on)
#endif

#ifdef MSVC
#pragma optimize( "gty", on)
#endif
static void LSQMultiSolve(M_INT n, real_T *A, M_INT Ainc, M_INT *ip, M_INT nb,
	real_T *b, M_INT binc)
{
	M_INT i,j,k,m;
	real_T t,s;

	if( ip[n-1]==0 ) {
		for(i=0;i<n;i++) for(k=0;k<nb;k++) b[i*binc+k]=*dsn_undef;
		return;
	}
	for(i=0;i<n;i++) for(k=0;k<nb;k++) b[i*binc+k] *= A[i*Ainc+n];
	for(i=0;i<n-1;i++) {
		m = ip[i];
		if( m!=i )
			for(k=0;k<nb;k++) {
				t = b[m*binc+k]; b[m*binc+k] = b[i*binc+k]; b[i*binc+k] = t;
			}
	}
	for(j=0;j<n-1;j++)
		for(k=0;k<nb;k++) {
			t = b[j*binc+k];
			for(i=j+1;i<n;i++)
				b[i*binc+k] += t*A[i*Ainc+j];
		}
	for(j=n-1;j>0;j--) {
		s = 1.0/A[j*(Ainc+1)];
		for(k=0;k<nb;k++) {
			b[j*binc+k] = s*b[j*binc+k];
			t = -b[j*binc+k];
			for(i=0;i<j;i++)
				b[i*binc+k] += t*A[i*Ainc+j];
		}
	}
	for(k=0;k<nb;k++) b[k] = b[k]/A[0];
	for(j=n-2;j>=0;j--) {
		m = ip[n+j];
		if(m!=j)
			for(k=0;k<nb;k++) {
				t = b[m*binc+k]; b[m*binc+k] = b[j*binc+k]; b[j*binc+k] = t;
			}
	}
	for(j=0;j<n;j++) for(k=0;k<nb;k++) b[j*binc+k] *= A[n*Ainc+j];
}
#ifdef MSVC
#pragma optimize( "", on)
#endif

#ifdef MSVC
#pragma optimize( "gty", on)
#endif
static void DecompCInc(M_INT n, real_T *A, M_INT Ainc, M_INT *ip)
{
	M_INT i,j,k,m;
	real_T t;

	ip[n-1]=1;
	for(k=0;k<n-1;k++) {
		m=k;
		for(i=k+1;i<n;i++)
			if( fabs(A[i*Ainc+k])>fabs(A[m*Ainc+k]) ) m=i;
		ip[k]=m;
		if( m!=k ) ip[n-1]=-ip[n-1];
		t=A[m*Ainc+k]; A[m*Ainc+k]=A[(Ainc+1)*k]; A[(Ainc+1)*k]=t;
		if( t==0.0 ) { ip[n-1]=0; return; }
		t=-1.0/t;
		for(i=k+1;i<n;i++) A[i*Ainc+k]=A[i*Ainc+k]*t;
		for(j=k+1;j<n;j++) {
			t=A[m*Ainc+j]; A[m*Ainc+j]=A[k*Ainc+j]; A[k*Ainc+j]=t;
			if( t!=0.0 )
				for(i=k+1;i<n;i++) A[i*Ainc+j]+=A[i*Ainc+k]*t;
		}
	}
	if(A[(n-1)*(Ainc+1)]==0.0) ip[n-1]=0;
}
#ifdef MSVC
#pragma optimize( "", on)
#endif

#ifdef MSVC
#pragma optimize( "gty", on)
#endif
static void SolveCInc(M_INT n, real_T *A, M_INT Ainc, M_INT *ip, real_T *b)
{
	M_INT i,j,m;
	real_T t;

	if( n>1 ) {
		for(j=0;j<n-1;j++) {
			m=ip[j];
			t=b[m]; b[m]=b[j]; b[j]=t;
			for(i=j+1;i<n;i++) b[i]+=A[i*Ainc+j]*t;
		}
		for(j=n-1;j>0;j--) {
			b[j]=b[j]/A[(Ainc+1)*j];
			t=-b[j];
			for(i=0;i<=j-1;i++) b[i]+=A[i*Ainc+j]*t;
		}
	}
	b[0]=b[0]/A[0];
}
#ifdef MSVC
#pragma optimize( "", on)
#endif

static void fp(int_T N, real_T T, real_T *Y, real_T *YP)
{
	real_T M[220], V[10], Z[4];
	int_T ti1, ti2;
	M_INT P[19];

	UNUSED(N);
	UNUSED(T);
	for(ti1=0;ti1<=9;ti1++)
		for(ti2=0;ti2<=9;ti2++)
			M[ti1*20+ti2] = 0.;
	for(ti1=0;ti1<=9;ti1++)
		V[ti1] = 0.;
	M[7] = -1.;
	V[0] = Y[39];
	if( Y[24]==1. ) {
		M[0] = -1.;
		M[140] = -Y[31];
	}
	else {
		M[0] = -Y[35];
		M[140] = -1.;
	}
	M[144] = 1.;
	M[145] = -1.;
	M[146] = 1.;
	V[7] = Y[31]*Y[39]+Y[2];
	M[27] = -1.;
	V[1] = Y[43];
	if( Y[26]==1. ) {
		M[22] = -1.;
		M[62] = -Y[31];
	}
	else {
		M[22] = -Y[35];
		M[62] = -1.;
	}
	M[65] = 1.;
	V[3] = Y[31]*Y[43];
	M[44] = 1.;
	if( Y[25]==1. ) {
		M[41] = -Y[31];
		V[2] = Y[31]*Y[41];
		M[121] = -1.;
	}
	else {
		M[41] = -1.;
		V[2] = Y[31]*Y[41];
		M[121] = -Y[35];
	}
	M[127] = 1.;
	M[128] = -1.;
	V[6] = Y[41];
	M[86] = 1.;
	if( Y[27]==1. ) {
		M[83] = -Y[31];
		V[4] = Y[31]*Y[45];
		M[103] = -1.;
	}
	else {
		M[83] = -1.;
		V[4] = Y[31]*Y[45];
		M[103] = -Y[35];
	}
	M[107] = 1.;
	M[108] = -1.;
	V[5] = Y[45];
	Z[0] = 1.+Y[54]*(Y[53]-Y[52]);
	Z[0] = 1.0/Z[0];
	Z[1] = Z[0]/Y[34];
	M[168] = -Z[1];
	Z[0] = (1.+Y[57]*(Y[56]-Y[55]))*Z[0];
	M[169] = 1.+Z[0];
	Z[2] = Z[1]*(Y[0]+Y[1]);
	V[8] = -(Z[2]+Y[2]);
	M[184] = -1.;
	M[186] = -1.;
	Z[3] = 1.0/Y[49];
	M[188] = (Z[1]*Y[49]+1.)*Z[3];
	M[189] = -Z[0];
	V[9] = 1.*(Z[2]-Y[3]*Y[63]-Y[64]*Y[65])*Y[49]*Z[3];
	LSQDecompSolve(10,M,20,P,V);
	if( P[9]==0 ) {
		YP[0] = (*dsn_undef);
		return;
	}
	Y[4] = V[0];
	Y[5] = V[1];
	Y[6] = V[2];
	Y[7] = V[3];
	Y[9] = V[4];
	Y[10] = V[5];
	Y[11] = V[6];
	Y[16] = V[7];
	Y[14] = V[8];
	Y[15] = V[9];
	Z[0] = 1.+Y[57]*(Y[56]-Y[55]);
	Y[13] = Z[0]*Y[15]*Y[34]+Y[1]+Y[21];
	Z[1] = Y[37]*Y[2]*(1.+Y[62]*(Y[61]-Y[60]));
	Z[2] = Y[32]+Y[33];
	Z[2] = 1.0/Z[2];
	Y[12] = ((Y[16]+Z[1])*Y[32]+(Y[13]-Y[2]*Y[36])*Y[33])*Z[2];
	Z[2] = 1.+Y[54]*(Y[53]-Y[52]);
	Z[2] = 1.0/Z[2];
	Z[3] = 1.0/Y[30];
	YP[0] = -Z[2]*(Y[15]*Z[0]+(Y[0]+Y[1]-Y[14])/Y[34])*Z[3];
	YP[2] = (1.*(Y[12]-Y[16]-Z[1]))/Y[33];
	Y[8] = (Y[22]-Y[3])/Y[67];
	YP[1] = Y[15]*Z[3];
	if( Y[29]==1. )
		YP[3] = -1000.;
	else if( Y[28]==1. )
		YP[3] = 1000.;
	else
		YP[3] = Y[8];
}

static void otp(real_T T, real_T *Y, real_T *YP)
{
	real_T Z[1];

	UNUSED(T);
	Y[17] = Y[9]+Y[11]-Y[2]-Y[10];
	Z[0] = 1.+Y[54]*(Y[53]-Y[52]);
	Z[0] = 1.0/Z[0];
	Y[18] = -Z[0]*((1.+Y[57]*(Y[56]-Y[55]))*Y[15]+(Y[0]+Y[1]-Y[14])/Y[34]);
}

static void Dfp(real_T T, real_T *Y, real_T *FX, real_T *FY)
{
	real_T B[50], M[220], V[10], YP[4], Z[67];
	int_T ti1, ti2;
	M_INT P[19];

	UNUSED(T);
	for(ti1=0;ti1<=3;ti1++)
		for(ti2=0;ti2<=3;ti2++)
			FY[ti1*4+ti2] = 0.;
	for(ti1=0;ti1<=3;ti1++)
		FX[ti1] = 0.;
	for(ti1=0;ti1<=9;ti1++)
		for(ti2=0;ti2<=9;ti2++)
			M[ti1*20+ti2] = 0.;
	for(ti1=0;ti1<=9;ti1++)
		V[ti1] = 0.;
	M[7] = -1.;
	V[0] = Y[39];
	if( Y[24]==1. ) {
		M[0] = -1.;
		M[140] = -Y[31];
	}
	else {
		M[0] = -Y[35];
		M[140] = -1.;
	}
	M[144] = 1.;
	M[145] = -1.;
	M[146] = 1.;
	V[7] = Y[31]*Y[39]+Y[2];
	M[27] = -1.;
	V[1] = Y[43];
	if( Y[26]==1. ) {
		M[22] = -1.;
		M[62] = -Y[31];
	}
	else {
		M[22] = -Y[35];
		M[62] = -1.;
	}
	M[65] = 1.;
	V[3] = Y[31]*Y[43];
	M[44] = 1.;
	if( Y[25]==1. ) {
		M[41] = -Y[31];
		V[2] = Y[31]*Y[41];
		M[121] = -1.;
	}
	else {
		M[41] = -1.;
		V[2] = Y[31]*Y[41];
		M[121] = -Y[35];
	}
	M[127] = 1.;
	M[128] = -1.;
	V[6] = Y[41];
	M[86] = 1.;
	if( Y[27]==1. ) {
		M[83] = -Y[31];
		V[4] = Y[31]*Y[45];
		M[103] = -1.;
	}
	else {
		M[83] = -1.;
		V[4] = Y[31]*Y[45];
		M[103] = -Y[35];
	}
	M[107] = 1.;
	M[108] = -1.;
	V[5] = Y[45];
	Z[0] = 1.+Y[54]*(Y[53]-Y[52]);
	Z[0] = 1.0/Z[0];
	Z[1] = Z[0]/Y[34];
	M[168] = -Z[1];
	Z[0] = (1.+Y[57]*(Y[56]-Y[55]))*Z[0];
	M[169] = Z[0]+1.;
	Z[2] = Z[1]*(Y[0]+Y[1]);
	V[8] = -(Z[2]+Y[2]);
	M[184] = -1.;
	M[186] = -1.;
	Z[3] = 1.0/Y[49];
	M[188] = (Z[1]*Y[49]+1.)*Z[3];
	M[189] = -Z[0];
	V[9] = 1.*(Z[2]-Y[3]*Y[63]-Y[64]*Y[65])*Y[49]*Z[3];
	LSQDecompSolve(10,M,20,P,V);
	if( P[9]==0 ) {
		FX[0] = (*dsn_undef);
		return;
	}
	Y[4] = V[0];
	Y[5] = V[1];
	Y[6] = V[2];
	Y[7] = V[3];
	Y[9] = V[4];
	Y[10] = V[5];
	Y[11] = V[6];
	Y[16] = V[7];
	Y[14] = V[8];
	Y[15] = V[9];
	for(ti1=0;ti1<=9;ti1++)
		for(ti2=0;ti2<=3;ti2++)
			B[ti1*5+ti2] = 0.;
	Z[0] = 1.+Y[54]*(Y[53]-Y[52]);
	Z[0] = 1.0/Z[0];
	Z[0] = Z[0]/Y[34];
	B[40] = -Z[0];
	B[45] = Z[0];
	B[41] = -Z[0];
	B[46] = Z[0];
	B[37] = 1.;
	B[42] = -1.;
	B[48] = -Y[63];
	LSQMultiSolve(10,M,20,P,4,B,5);
	Z[6] = B[0];
	Z[7] = B[5];
	Z[8] = B[10];
	Z[9] = B[15];
	Z[10] = B[20];
	Z[11] = B[25];
	Z[12] = B[30];
	Z[13] = B[35];
	Z[14] = B[40];
	Z[15] = B[45];
	Z[16] = B[1];
	Z[17] = B[6];
	Z[18] = B[11];
	Z[19] = B[16];
	Z[20] = B[21];
	Z[21] = B[26];
	Z[22] = B[31];
	Z[23] = B[36];
	Z[24] = B[41];
	Z[25] = B[46];
	Z[26] = B[2];
	Z[27] = B[7];
	Z[28] = B[12];
	Z[29] = B[17];
	Z[30] = B[22];
	Z[31] = B[27];
	Z[32] = B[32];
	Z[33] = B[37];
	Z[34] = B[42];
	Z[35] = B[47];
	Z[36] = B[3];
	Z[37] = B[8];
	Z[38] = B[13];
	Z[39] = B[18];
	Z[40] = B[23];
	Z[41] = B[28];
	Z[42] = B[33];
	Z[43] = B[38];
	Z[44] = B[43];
	Z[45] = B[48];
	Z[0] = 1.+Y[57]*(Y[56]-Y[55]);
	Y[13] = Z[0]*Y[15]*Y[34]+Y[1]+Y[21];
	Z[1] = 1.+Y[57]*(Y[56]-Y[55]);
	Z[46] = Y[34]*Z[15]*Z[1];
	Z[47] = Z[0]*Z[25]*Y[34]+1.;
	Z[48] = Y[34]*Z[35]*Z[1];
	Z[49] = Y[34]*Z[45]*Z[1];
	Z[50] = Y[19];
	Z[1] = Y[37]*(1.+Y[62]*(Y[61]-Y[60]));
	Z[2] = Z[1]*Y[2];
	Z[3] = Y[32]+Y[33];
	Z[3] = 1.0/Z[3];
	Y[12] = ((Y[16]+Z[2])*Y[32]+(Y[13]-Y[2]*Y[36])*Y[33])*Z[3];
	Z[51] = (Z[13]*Y[32]+Z[46]*Y[33])*Z[3];
	Z[52] = (Z[23]*Y[32]+Z[47]*Y[33])*Z[3];
	Z[53] = (Y[32]*(Z[33]+Z[1])+(Z[48]-Y[36])*Y[33])*Z[3];
	Z[54] = (Z[43]*Y[32]+Z[49]*Y[33])*Z[3];
	Z[55] = Z[50]*Y[33]*Z[3];
	Z[3] = 1.+Y[54]*(Y[53]-Y[52]);
	Z[3] = 1.0/Z[3];
	Z[4] = 1.0/Y[34];
	Z[5] = 1.0/Y[30];
	YP[0] = -Z[3]*(Y[15]*Z[0]+Z[4]*(Y[0]+Y[1]-Y[14]))*Z[5];
	FY[0] = -Z[3]*(Z[0]*Z[15]+Z[4]*(1.-Z[14]))*Z[5];
	FY[1] = -Z[3]*(Z[0]*Z[25]+Z[4]*(1.-Z[24]))*Z[5];
	FY[2] = Z[3]*(Z[4]*Z[34]-Z[0]*Z[35])*Z[5];
	FY[3] = Z[3]*(Z[4]*Z[44]-Z[0]*Z[45])*Z[5];
	Z[0] = 1.0/Y[33];
	YP[2] = 1.*(Y[12]-Y[16]-Z[2])*Z[0];
	FY[8] = (Z[51]-Z[13])*Z[0];
	FY[9] = (Z[52]-Z[23])*Z[0];
	FY[10] = 1.*(Z[53]-Z[33]-Z[1])*Z[0];
	FY[11] = (Z[54]-Z[43])*Z[0];
	FX[2] = Z[55]*Z[0];
	Z[0] = 1.0/Y[67];
	Y[8] = 1.*(Y[22]-Y[3])*Z[0];
	Z[56] = -Z[0];
	Z[57] = Y[20]*Z[0];
	YP[1] = Y[15]*Z[5];
	FY[4] = Z[15]*Z[5];
	FY[5] = Z[25]*Z[5];
	FY[6] = Z[35]*Z[5];
	FY[7] = Z[45]*Z[5];
	if( Y[29]==1. )
		YP[3] = -1000.;
	else if( Y[28]==1. )
		YP[3] = 1000.;
	else
		YP[3] = Y[8];
	if( Y[29]==1. ) {
		Z[0] = 0.;
		Z[1] = 0.;
	}
	else {
		if( Y[28]==1. ) {
			Z[0] = 0.;
			Z[1] = 0.;
		}
		else {
			Z[0] = -Z[56];
			Z[1] = -Z[57];
		}
	}
	FY[15] = -Z[0];
	FX[3] = -Z[1];
}

static void eev(real_T T, real_T *Y, real_T *Ypre, real_T *EA)
{
	real_T Z[1];

	UNUSED(T);
	UNUSED(Ypre);
	EA[0] = -Y[4];
	EA[1] = -Y[5];
	EA[2] = -Y[6];
	EA[3] = -Y[7];
	Z[0] = 0.001*Y[8];
	EA[4] = Z[0]-1.;
	EA[5] = -(1.+Z[0]);
}

static int_T eex(int_T N, real_T T, real_T *Y, real_T *Ypre)
{
	UNUSED(T);
	UNUSED(Ypre);
	if( N==1 )
		Y[24] = 1.-Y[24];
	else if( N==2 )
		Y[25] = 1.-Y[25];
	else if( N==3 )
		Y[26] = 1.-Y[26];
	else if( N==4 )
		Y[27] = 1.-Y[27];
	else if( N==5 )
		Y[28] = 1.-Y[28];
	else if( N==6 )
		Y[29] = 1.-Y[29];
	else if( N==7 ) {
		if( !(1.*Y[54]*(Y[52]-Y[53])-1.<=0.) ) {
			Y[23] = 1.;
			return(1);
		}
		if( !(1.*Y[57]*(Y[55]-Y[56])-1.<=0.) ) {
			Y[23] = 2.;
			return(1);
		}
		if( !(1.*Y[62]*(Y[60]-Y[61])-1.<=0.) ) {
			Y[23] = 3.;
			return(1);
		}
		if( !( (Y[24]==0.) || (Y[24]==1.) ) ) {
			Y[23] = 4.;
			return(1);
		}
		if( !( (Y[25]==0.) || (Y[25]==1.) ) ) {
			Y[23] = 5.;
			return(1);
		}
		if( !( (Y[26]==0.) || (Y[26]==1.) ) ) {
			Y[23] = 6.;
			return(1);
		}
		if( !( (Y[27]==0.) || (Y[27]==1.) ) ) {
			Y[23] = 7.;
			return(1);
		}
	}
	return(0);
}

static int_T cpr(real_T T, real_T *Y)
{
	real_T v;
	int_T k;

	UNUSED(T);
	k = 0;
	v = Y[22];
	if( Y[3]!=v ) {
		k = 1;
		Y[3] = v;
	}
	if( Y[4]<0. )
		v = 1.;
	else
		v = 0.;
	if( Y[24]!=v ) {
		Y[24] = v;
		k = 1;
	}
	if( Y[5]<0. )
		v = 1.;
	else
		v = 0.;
	if( Y[25]!=v ) {
		Y[25] = v;
		k = 1;
	}
	if( Y[6]<0. )
		v = 1.;
	else
		v = 0.;
	if( Y[26]!=v ) {
		Y[26] = v;
		k = 1;
	}
	if( Y[7]<0. )
		v = 1.;
	else
		v = 0.;
	if( Y[27]!=v ) {
		Y[27] = v;
		k = 1;
	}
	if( Y[8]>1000. )
		v = 1.;
	else
		v = 0.;
	if( Y[28]!=v ) {
		Y[28] = v;
		k = 1;
	}
	if( Y[8]<-1000. )
		v = 1.;
	else
		v = 0.;
	if( Y[29]!=v ) {
		Y[29] = v;
		k = 1;
	}
	return(k);
}

static void terminate(SimStruct *S, real_T T, real_T *Y, int_T j)
{
	if(j==1) ssSetErrorStatus(S,"Modelica assertion (0 <= 0.999999999999999 + alpha * (T_heatPort - T_ref)) failed in Main.AC120VPFC1.R_BusCap1: Temperature outside scope of model!");
	if(j==2) ssSetErrorStatus(S,"Modelica assertion (0 <= 0.999999999999999 + alpha * (T_heatPort - T_ref)) failed in Main.AC120VPFC1.R_BusCap2: Temperature outside scope of model!");
	if(j==3) ssSetErrorStatus(S,"Modelica assertion (0 <= 0.999999999999999 + alpha * (T_heatPort - T_ref)) failed in Main.AC120VPFC1.R_PFC: Temperature outside scope of model!");
	if(j==4) ssSetErrorStatus(S,"variable `Main.AC120VPFC1.ID1.off`(t) must be boolean valued");
	if(j==5) ssSetErrorStatus(S,"variable `Main.AC120VPFC1.ID2.off`(t) must be boolean valued");
	if(j==6) ssSetErrorStatus(S,"variable `Main.AC120VPFC1.ID3.off`(t) must be boolean valued");
	if(j==7) ssSetErrorStatus(S,"variable `Main.AC120VPFC1.ID4.off`(t) must be boolean valued");
}

static int_T RunEvents(SimStruct *S, real_T *w, int_T *modes, int_T first, int_T termvar, int_T maxiter)
{
	real_T t,*y,*yp,*ypre,*tval;
	int_T *m=NULL,*oldmodes,*inc,*req;
	int_T i,flag,iter,evt,rc,failskip;

	/* Transfer data to approp. named arrays */
	t=w[0]; y=&w[1]; yp=&y[NEQ+NPAR]; ypre=&yp[NDFA]; tval=&ypre[NEQ];
	oldmodes=&modes[NZC]; inc=&oldmodes[NZC]; req=&inc[NEVT];
	/* Verify that no y values are undefined */
	for(i=0;i<NEQ;i++) if(IS_UNDEF(y[i])) {
		ssSetErrorStatus(S,"undefined value encountered on entry to RunEvents");
		if (fptr) {
			writeErrorToFile(fptr,ssGetErrorStatus(S));
			fptr = NULL;
		}
		return(-3);
	}

	/* Set 'm' to mode vector if we are variable step */
	if(ssGetNumNonsampledZCs(S)>0)
		m=ssGetModeVector(S);

	/* Set the old modes to the new and ypre to y */
	for(i=0;i<NZC;i++) oldmodes[i]=modes[i];
	for(i=0;i<NEQ;i++) ypre[i]=y[i];

	if(!first) {
		/* Check for events */
		eev(t,y,ypre,tval);
		flag=0;
		for(i=0;i<NEVT;i++) {
#ifdef EVTHYST
			if( tval[i]>EVTHYST && modes[2*i]==0 ) {
				modes[2*i]=1;
				if(req[i]>0 && y[req[i]-1]==1.0) oldmodes[2*i]=1;
				else flag=1;
			}
			else if( tval[i]<EVTHYST && modes[2*i]==1 ) {
				modes[2*i]=0; oldmodes[2*i]=0;
			}
			if( tval[i]>-EVTHYST && modes[2*i+1]==0) {
				modes[2*i+1]=1; oldmodes[2*i+1]=1;
			}
			else if( tval[i]<-EVTHYST && modes[2*i+1]==1 ) {
				modes[2*i+1]=0;
				if(inc[i] || (req[i]>0 && y[req[i]-1]==0.0)) oldmodes[2*i+1]=0;
				else flag=1;
			}
#else
			if( tval[i]>0.0 && modes[i]==0 ) {
				modes[i]=1;
				if(req[i]>0 && y[req[i]-1]==1.0) oldmodes[i]=1;
				else flag=1;
			}
			else if( tval[i]<0.0 && modes[i]==1 ) {
				modes[i]=0;
				if(inc[i] || (req[i]>0 && y[req[i]-1]==0.0)) oldmodes[i]=0;
				else flag=1;
			}
#endif
		}
		/* If no events, return, but still need to update modes as we may
			have a sign change for a decrease on an increase-only trigger */
		if(!flag) {
			if(m) for(i=0;i<NZC;i++) m[i]=modes[i];
			return(0);
		}
	}

	/* Iteration loop */
	failskip=0;
	for(iter=0;;iter++) {
		if( !first || iter>0 )
			/* Event loop */
			for(evt=0;evt<NEVT;evt++)
#ifdef EVTHYST
				if(modes[2*evt]!=oldmodes[2*evt] || modes[2*evt+1]!=oldmodes[2*evt+1]) {
#else
				if(modes[evt]!=oldmodes[evt]) {
#endif
					rc=eex(evt+1,t,y,ypre);
					if(termvar>=0 && y[termvar]>0.0) {
						i=(int_T)y[termvar];
						terminate(S,t,y,i);
						return(i);
					}
					/* Handle RC */
#ifdef EVTHYST
					oldmodes[2*evt]=modes[2*evt]; oldmodes[2*evt+1]=modes[2*evt+1];
#else
					oldmodes[evt]=modes[evt];
#endif
				}

		/* Discrete equations */
		rc=eex(NEVT+1,t,y,ypre);
		/* Fail skip */
		if(rc==8 && !failskip) {
			failskip=1;
			iter--;
			if(termvar>=0) y[termvar]=0.0;
		}
		else
			failskip=0;
		if(termvar>=0 && y[termvar]>0.0) {
			i=(int_T)y[termvar];
			terminate(S,t,y,i);
			return(i);
		}
		/* Handle RC */

		/* Check for termination */
		for(i=0;i<NEQ;i++) if(y[i]!=ypre[i]) break;
		if( !failskip && i==NEQ ) {
			/* Update modes and return */
			if(m) for(i=0;i<NZC;i++) m[i]=modes[i];
			return(0);
		}

		/* Check iter limit */
		if( iter>=maxiter ) {
			ssSetErrorStatus(S,"event iteration limit exceeded");
			if (fptr) {
				writeErrorToFile(fptr,ssGetErrorStatus(S));
				fptr = NULL;
			}
			return(-1);
		}

		/* Update index-1 equations */
		if(!failskip && NIX1>0) {
			fp(NEQ,t,y,yp);
			if( IS_UNDEF(yp[0]) ) {
				ssSetErrorStatus(S,"index-1 and derivative evaluation failure");
				if (fptr) {
					writeErrorToFile(fptr,ssGetErrorStatus(S));
					fptr = NULL;
				}
				return(-2);
			}
		}
		/* Verify that no y values are undefined */
		for(i=0;i<NEQ;i++) if(IS_UNDEF(y[i])) {
			ssSetErrorStatus(S,"undefined value encountered during event iteration");
			if (fptr) {
				writeErrorToFile(fptr,ssGetErrorStatus(S));
				fptr = NULL;
			}
			return(-4);
		}

		/* Update pre */
		for(i=0;i<NEQ;i++) ypre[i]=y[i];
		if(failskip) continue;

		/* Evaluate event triggers, and update modes */
		eev(t,y,ypre,tval);
		for(i=0;i<NEVT;i++) {
#ifdef EVTHYST
			if( tval[i]>EVTHYST && modes[2*i]==0 ) {
				modes[2*i]=1;
				if(req[i]>0 && y[req[i]-1]==1.0) oldmodes[2*i]=1;
			}
			else if( tval[i]<EVTHYST && modes[2*i]==1 ) {
				modes[2*i]=0; oldmodes[2*i]=0;
			}
			if( tval[i]>-EVTHYST && modes[2*i+1]==0) {
				modes[2*i+1]=1; oldmodes[2*i+1]=1;
			}
			else if( tval[i]<-EVTHYST && modes[2*i+1]==1 ) {
				modes[2*i+1]=0;
				if(inc[i] || (req[i]>0 && y[req[i]-1]==0.0)) oldmodes[2*i+1]=0;
			}
#else
			if( tval[i]>0.0 && modes[i]==0 ) {
				modes[i]=1;
				if(req[i]>0 && y[req[i]-1]==1.0) oldmodes[i]=1;
			}
			else if( tval[i]<0.0 && modes[i]==1 ) {
				modes[i]=0;
				if(req[i]>0 && y[req[i]-1]==0.0) oldmodes[i]=0;
				if(inc[i]) oldmodes[i]=0;
			}
#endif
		}
	}
	return(0);
}

static void numdiffinp(real_T *w, int_T initial)
{
	real_T dt1,dt2,idt1,idt2,idt12,*nd1,*nd2;

	nd1=w+1+2*NEQ+NPAR+NDFA+NEVT;
	nd2=nd1+3;
	if(!initial && w[0]-nd1[0]==0.0) {
		nd1[1]=w[22];
		nd1[2]=w[23];
	}
	if(!initial && w[0]-nd1[0]>0.0) {
		dt1=w[0]-nd1[0]; idt1=1.0/dt1;
		if(nd1[0]-nd2[0]>0.0) {
			dt2=w[0]-nd2[0]; idt2=1.0/dt2;
			idt12=1.0/(nd2[0]-nd1[0]);
			w[20]=(idt1+idt2)*w[22]+idt12*(dt2*idt1*nd1[1]-dt1*idt2*nd2[1]);
			w[21]=(idt1+idt2)*w[23]+idt12*(dt2*idt1*nd1[2]-dt1*idt2*nd2[2]);
		}
		else {
			w[20]=idt1*(w[22]-nd1[1]);
			w[21]=idt1*(w[23]-nd1[2]);
		}
	}
	if(initial || w[0]-nd1[0]>1e-10) {
		nd2[0]=nd1[0]; nd1[0]=w[0];
		nd2[1]=nd1[1]; nd1[1]=w[22];
		nd2[2]=nd1[2]; nd1[2]=w[23];
	}
}

static void mdlCheckParameters(SimStruct *S)
{
	const mxArray *dpar1 = ssGetSFcnParam(S,1);

	if ( mxGetNumberOfElements(ssGetSFcnParam(S,1))!=1 || !IS_PARAM_DOUBLE(dpar1) ) {
		ssSetErrorStatus(S, "Minimum sample step must be a scalar");
		return;
	}
	else if (mxGetPr(ssGetSFcnParam(S,1))[0]<0) {
		ssSetErrorStatus(S, "Minimum sample step must be non-negative");
		return;
	}
}

static void mdlInitializeSizes(SimStruct *S)
{
	ssSetNumSFcnParams(S, NDPAR);
	if( ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S) ) {
		return;
	}
	else {
		mdlCheckParameters(S);
		if (ssGetErrorStatus(S) != NULL) return;
	}
	ssSetNumContStates(S, 0);
	ssSetNumDiscStates(S, NDIFF);

	if( !ssSetNumInputPorts(S, 3) ) return;
	ssSetInputPortWidth(S, 0, NSDIFF);
	ssSetInputPortDirectFeedThrough(S, 0, 1);
	ssSetInputPortWidth(S, 1, NPAR);
	ssSetInputPortDirectFeedThrough(S, 1, 1);
	ssSetInputPortWidth(S, 2, NINP);
	ssSetInputPortDirectFeedThrough(S, 2, 1);

	if( !ssSetNumOutputPorts(S, 1) ) return;
	ssSetOutputPortWidth(S, 0, NOUT);

	ssSetNumSampleTimes(S, 1);
	ssSetNumRWork(S, 7+2*NEQ+NPAR+NDFA+NEVT);
	ssSetNumIWork(S, 2*NEVT+2*NZC+2);
	ssSetNumPWork(S, 0);
	ssSetNumModes(S, DYNAMICALLY_SIZED);
	ssSetNumNonsampledZCs(S, DYNAMICALLY_SIZED);

	ssSetOptions(S, SS_OPTION_EXCEPTION_FREE_CODE);
}

#define MDL_SET_WORK_WIDTHS
static void mdlSetWorkWidths(SimStruct *S)
{
	if( ssIsVariableStepSolver(S) &&
		 ssGetSampleTime(S,0) == TIMESTEP &&
		 ssGetOffsetTime(S,0) == 0.0 ) {
		ssSetNumModes(S,NZC);
		ssSetNumNonsampledZCs(S,NZC);
	}
	else {
		ssSetNumModes(S,0);
		ssSetNumNonsampledZCs(S,0);
	}
}

static void mdlInitializeSampleTimes(SimStruct *S)
{
	ssSetSampleTime(S, 0, TIMESTEP);
	ssSetOffsetTime(S, 0, 0.0);
	ssSetModelReferenceSampleTimeDefaultInheritance(S);
}

static void InitializeConditions(SimStruct *S)
{
	real_T *w = ssGetRWork(S);
	int_T *iw = ssGetIWork(S);
	real_T *x = ssGetDiscStates(S);
	InputRealPtrsType i = ssGetInputPortRealSignalPtrs(S,2);
	InputRealPtrsType p = ssGetInputPortRealSignalPtrs(S,1);
	int_T j, k;

	if (fptr) {
		fclose(fptr);
		fptr = NULL;
	}
	mxGetString(ssGetSFcnParam(S,0),fstr,MAXSTRLENGTH);
	if (fstr!="\0")
		fptr = fopen(fstr,"wb");
	minsamplestep = (mxGetPr(ssGetSFcnParam(S,1)))[0];
	lastsampletime = -1e10;
	numpts = 0;

    TIMESTEP = (mxGetPr(ssGetSFcnParam(S,2)))[0]; // Get TIMESTEP value from the S-Function mask

	w[0] =  0.0;
	w[1] =  1.86676190233248550e+02;
	w[2] =  1.86676190233248550e+02;
	w[3] =  0.00000000000000000e+00;
	w[4] =  0.00000000000000000e+00;
	w[5] = -1.86675886189848800e+02;
	w[6] = -1.86675886189848800e+02;
	w[7] = -1.86675886189848800e+02;
	w[8] = -1.86675886189848800e+02;
	w[9] =  0.00000000000000000e+00;
	w[10] = -1.54940985537574510e-06;
	w[11] = -1.54940985537574510e-06;
	w[12] = -1.54940985537574510e-06;
	w[13] =  1.86675886189848740e+02;
	w[14] =  1.86675886189848770e+02;
	w[15] =  3.73351772379697590e+02;
	w[16] = -3.04043399774498680e-03;
	w[17] =  1.86675886189848800e+02;
	w[18] = -1.54940985537554460e-06;
	w[19] = -3.04043399694872060e-03;
	w[20] =  0.00000000000000000e+00;
	w[21] =  0.00000000000000000e+00;
	w[22] =  0.00000000000000000e+00;
	w[23] =  0.00000000000000000e+00;
	w[24] =  0.00000000000000000e+00;
	w[25] =  1.00000000000000000e+00;
	w[26] =  1.00000000000000000e+00;
	w[27] =  1.00000000000000000e+00;
	w[28] =  1.00000000000000000e+00;
	w[29] =  0.00000000000000000e+00;
	w[30] =  0.00000000000000000e+00;
	w[31] =  1.00000000000000000e-03;
	w[32] =  8.29999999999999990e-09;
	w[33] =  5.00000000000000020e-05;
	w[34] =  3.00000000000000010e-03;
	w[35] =  1.00000000000000010e-01;
	w[36] =  5.00000000000000010e-03;
	w[37] =  5.99999999999999980e-01;
	w[38] =  4.03000000000000020e-01;
	w[39] =  2.98149999999999980e+02;
	w[40] =  0.00000000000000000e+00;
	w[41] =  2.98149999999999980e+02;
	w[42] =  0.00000000000000000e+00;
	w[43] =  2.98149999999999980e+02;
	w[44] =  0.00000000000000000e+00;
	w[45] =  2.98149999999999980e+02;
	w[46] =  0.00000000000000000e+00;
	w[47] =  1.00000000000000000e-02;
	w[48] =  2.98149999999999980e+02;
	w[49] =  2.98149999999999980e+02;
	w[50] =  1.00000000000000000e+07;
	w[51] =  2.98149999999999980e+02;
	w[52] =  2.98149999999999980e+02;
	w[53] =  2.98149999999999980e+02;
	w[54] =  2.98149999999999980e+02;
	w[55] =  4.04100000000000030e-03;
	w[56] =  2.98149999999999980e+02;
	w[57] =  2.98149999999999980e+02;
	w[58] =  4.04100000000000030e-03;
	w[59] =  2.98149999999999980e+02;
	w[60] =  2.98149999999999980e+02;
	w[61] =  2.98149999999999980e+02;
	w[62] =  2.98149999999999980e+02;
	w[63] =  4.04100000000000030e-03;
	w[64] =  1.00000000000000000e+00;
	w[65] =  1.00000000000000000e+00;
	w[66] =  3.00000000000000010e-03;
	w[67] =  1.00000000000000000e+03;
	w[68] =  6.25000000000000010e-05;
	iw[2*NZC+0] = 0; iw[2*NZC+NEVT+0] = 25;
	iw[2*NZC+1] = 0; iw[2*NZC+NEVT+1] = 26;
	iw[2*NZC+2] = 0; iw[2*NZC+NEVT+2] = 27;
	iw[2*NZC+3] = 0; iw[2*NZC+NEVT+3] = 28;
	iw[2*NZC+4] = 0; iw[2*NZC+NEVT+4] = 29;
	iw[2*NZC+5] = 0; iw[2*NZC+NEVT+5] = 30;
	eev(w[0],&w[1],&w[1],&w[2*NEQ+NPAR+NDFA+1]);
#ifdef EVTHYST
	for(j=0;j<NEVT;j++) {
		if(iw[2*NZC+NEVT+j]>0) {
			if(w[iw[2*NZC+NEVT+j]]==0.0) { iw[2*j]=0; iw[2*j+1]=0; }
			else                         { iw[2*j]=1; iw[2*j+1]=1; }
		}
		else {
			iw[2*j]=(w[2*NEQ+NPAR+NDFA+1+j]>EVTHYST ? 1 : 0);
			iw[2*j+1]=(w[2*NEQ+NPAR+NDFA+1+j]>-EVTHYST ? 1 : 0);
		}
	}
#else
	for(j=0;j<NEVT;j++)
		if(iw[2*NZC+NEVT+j]>0) {
			if(w[iw[2*NZC+NEVT+j]]==0.0) iw[j]=0; else iw[j]=1;
		}
		else
			iw[j]=(w[2*NEQ+NPAR+NDFA+1+j]>0.0 ? 1 : 0);
#endif

	for(j=0;j<NDIFF;j++) w[NEQ+NPAR+j+1]=0.0;

	for(j=0;j<NINP;j++) w[j+NDIFF+NIX1-NINP+1]=i[j][0];
	numdiffinp(w,1);
	numdiffinp(w,1);
	for(j=0;j<NDIFF;j++) w[j+1]=x[j];
	for(j=0;j<NPAR;j++) w[j+NEQ+1]=p[j][0];
	if (fptr) {
		fwrite(nData,sizeof(real_T),2,fptr);
		fwrite(&w[NEQ+1],sizeof(real_T),NPAR,fptr);
	}

	j=cpr(w[0],&w[1]);
	w[NEQ+NPAR+1]=0.0;
	if(NIX1>0) {
		fp(NEQ,w[0],&w[1],&w[NEQ+NPAR+1]);
		if( IS_UNDEF(w[NEQ+NPAR+1]) ) {
			ssSetErrorStatus(S,"index-1 and derivative evaluation failure");
			if (fptr) {
				writeErrorToFile(fptr,ssGetErrorStatus(S));
				fptr = NULL;
			}
			return;
		}
	}
	if(RunEvents(S,w,iw,1,23,EVTITER)) return;
	j=cpr(w[0],&w[1]);
	if(j>0 && NIX1>0) {
		fp(NEQ,w[0],&w[1],&w[NEQ+NPAR+1]);
		if( IS_UNDEF(w[NEQ+NPAR+1]) ) {
			ssSetErrorStatus(S,"index-1 and derivative evaluation failure");
			if (fptr) {
				writeErrorToFile(fptr,ssGetErrorStatus(S));
				fptr = NULL;			}
			return;
		}
	}
	eev(w[0],&w[1],&w[1],&w[2*NEQ+NPAR+NDFA+1]);
	if(RunEvents(S,w,iw,0,23,EVTITER)) return;
	for(j=0;j<NDIFF;j++) x[j]=w[j+1];
}

#define MDL_INITIALIZE_CONDITIONS
static void mdlInitializeConditions(SimStruct *S)
{
	InputRealPtrsType ic = ssGetInputPortRealSignalPtrs(S,0);
	real_T *x = ssGetDiscStates(S);
	int_T *iw = ssGetIWork(S);
	int_T j, k;

	iw[INIDREF]=0;
	iw[DODERREF]=0;
	for(j=0,k=0;j<NDIFF;j++) if(icvis[j]) x[j]=ic[k++][0];
}

static real_T *GetUpdatedWork(SimStruct *S, int_T getnofeed)
{
	int_T j,flag;

	real_T *w = ssGetRWork(S);
	real_T t = ssGetT(S);
	real_T *x = ssGetDiscStates(S);
	InputRealPtrsType i;
	InputRealPtrsType p = ssGetInputPortRealSignalPtrs(S,1);

	flag=0;
	if( fabs(w[0]-t)>1e-6*TIMESTEP ) flag=1;
	w[0]=t;
	for(j=0;j<NDIFF;j++) if( w[j+1]!=x[j] ) { flag=1; w[j+1]=x[j]; }
	i = ssGetInputPortRealSignalPtrs(S,2);
	for(j=0;j<NINP;j++) if( w[j+NDIFF+NIX1-NINP+1]!=i[j][0] ) { flag=1; w[j+NDIFF+NIX1-NINP+1]=i[j][0]; }
	for(j=0;j<NPAR;j++) if( w[j+NEQ+1]!=p[j][0] ) { flag=1; w[j+NEQ+1]=p[j][0]; }
	if(flag) numdiffinp(w,0);

	if(flag) {
		fp(NEQ,w[0],&w[1],&w[NEQ+NPAR+1]);
		if( IS_UNDEF(w[NEQ+NPAR+1]) ) {
			if( NDIFF>0 && ssIsVariableStepSolver(S) )
				for(j=1;j<NDIFF;j++) w[NEQ+NPAR+1+j] = w[NEQ+NPAR+1];
			else
			{
				ssSetErrorStatus(S,"index-1 and derivative evaluation failure");
				if (fptr) {
					writeErrorToFile(fptr,ssGetErrorStatus(S));
					fptr = NULL;				}
			}
		}
	}

	return(w);
}

static void StepWithEvents(SimStruct *S)
{
	real_T *ws0,*ws1,*y,*yp,*ypre,*zc,*y0,*yp0,*zc0,*w=ssGetRWork(S);
	real_T t0,tf,h,vl,vr,ept,cpt,vle,vre,hrel,qa,qb;
	int_T *modes=ssGetIWork(S),*oldmodes,*inc,*req;
	int_T iter,i,flag,evt;
	InputRealPtrsType in=ssGetInputPortRealSignalPtrs(S,2);
	real_T tol,delta,ft[NDFA],fy[NDFA*NDFA],ft0[NDFA],fy0[NDFA*NDFA];
	M_INT ip[NDFA],j;
#ifdef MIDSTEPEVENTDEBUG
	int_T gottime;
#endif

	/* Allocate memory for both vectors and split it up */
	if( (ws0=(real_T *)malloc(2*(1+2*NEQ+NPAR+NDFA+NEVT)*sizeof(double)))==NULL )
		ssSetErrorStatus(S,"unable to allocate memory");

	ws1=&ws0[1+2*NEQ+NPAR+NDFA+NEVT];

	/* Setup pointers into current and backup w vectors */
	y=&w[1]; yp=&y[NEQ+NPAR]; ypre=&yp[NDFA]; zc=&ypre[NEQ];
	y0=&ws0[1]; yp0=&y0[NEQ+NPAR]; zc0=&yp0[NDFA+NEQ];
	oldmodes=&modes[NZC]; inc=&oldmodes[NZC]; req=&inc[NEVT];

	tf=w[0]+TIMESTEP;
	/* Evaluate triggers at start of interval */
	eev(w[0],y,y,zc);
	for(iter=0;;iter++) {
#ifdef MIDSTEPEVENTDEBUG
		gottime=0;
#endif
		/* Back up all values into backup w vector */
		t0=w[0];
		for(i=0;i<1+2*NEQ+NPAR+NDFA+NEVT;i++) ws0[i]=w[i];
		/* Set step size and new time */
		h=tf-t0;
		w[0]=tf;
		/* Take Implicit Euler step */
		Dfp(t0,y,ft0,fy0);
		for(i=0;i<NDIFF;i++) {
			for(j=0;j<NDIFF;j++) fy[i*NDIFF+j]=-fy0[i*NDIFF+j];
			fy[i*(NDIFF+1)]+=1.0/h;
			ft[i]=yp[i]+h*ft0[i];
		}
		DecompCInc(NDIFF,fy,NDIFF,ip);
		SolveCInc(NDIFF,fy,NDIFF,ip,ft);
		for(i=0;i<NDIFF;i++) y[i]+=ft[i];
		/* Update: populate the inputs */
		for(i=0;i<NINP;i++) w[NDIFF+NIX1-NINP+1+i]=in[i][0];
		/* Compute the new fp */
		fp(NEQ,w[0],y,yp);
		if( IS_UNDEF(yp[0]) ) {
			ssSetErrorStatus(S,"index-1 and derivative evaluation failure");
			w[0]=tf;
			free(ws0);
			return;
		}

		/* Early termination for no internal events in step */
		if( MAXEVENTPERSTEP==0 ) break;
		/* Check iteration limit */
		if(iter==MAXEVENTPERSTEP) break;

		/* Compute zero crossings at end of step */
		eev(tf,y,y,zc);

		/* Back up all values */
		for(i=0;i<1+2*NEQ+NPAR+NDFA+NEVT;i++) ws1[i]=w[i];

		/* Find event */
		evt=-1;
		ept=tf;
		vle=tf;
		vre=tf;
		for(i=0;i<NEVT;i++) {
			flag=0;
#ifdef EVTHYST
			if( zc[i]>EVTHYST && modes[2*i]==0 && (!req[i] || y[req[i]-1]==0.0)) {
				vl=zc0[i]-EVTHYST; vr=zc[i]-EVTHYST; flag=1;
#ifdef MIDSTEPEVENTDEBUG
				if(!gottime && !iter) printf("\n");
				if(!gottime) printf("###%li### Checking interval %e..%e\n",iter+1,t0,tf); gottime=1;
				if(vl*vr>0.0)
					printf("Event %li +hyst: left=%e, right=%e, diff=%e #######\n",i,vl,vr,vl-vr);
				else
					printf("Event %li +hyst: left=%e, right=%e, diff=%e\n",i,vl,vr,vl-vr);
#endif
			}
			else if( zc[i]<-EVTHYST && modes[2*i+1]==1 && !inc[i]
				&& (!req[i] || y[req[i]-1]==1.0)) {
#ifdef MIDSTEPEVENTDEBUG
				if(!gottime && !iter) printf("\n");
				if(!gottime) printf("###%li### Checking interval %e..%e\n",iter+1,t0,tf); gottime=1;
				if(vl*vr>0.0)
					printf("Event %li -hyst: left=%e, right=%e, diff=%e #######\n",i,vl,vr,vl-vr);
				else
					printf("Event %li -hyst: left=%e, right=%e, diff=%e\n",i,vl,vr,vl-vr);
#endif
				vl=zc0[i]+EVTHYST; vr=zc[i]+EVTHYST; flag=1;
			}
#else
			if( (zc[i]>0.0 && modes[i]==0 && !req[i] || y[req[i]-1]==0.0) ||
				( zc[i]<0.0 && modes[i]==1 && !inc[i]
					&& (!req[i] || y[req[i]-1]==1.0)) ) {
#ifdef MIDSTEPEVENTDEBUG
				if(!gottime && !iter) printf("\n");
				if(!gottime) printf("###%li### Checking interval %e..%e\n",iter+1,t0,tf); gottime=1;
				if(vl*vr>0.0)
					printf("Event %li: left=%e, right=%e, diff=%e #######\n",i,vl,vr,vl-vr);
				else
					printf("Event %li: left=%e, right=%e, diff=%e\n",i,vl,vr,vl-vr);
#endif
				vl=zc0[i]; vr=zc[i]; flag=1;
			}
#endif
			if(flag) {
				/* Find zero crossing using linear approx */
				if(vl*vr>0.0) vl=0.0;
				cpt = vl/(vl-vr);
				if(cpt<0.0) cpt=t0;
				if(cpt>1.0) cpt=tf;
				else cpt=t0+h*cpt;
				/* Only take earliest */
				if( cpt<ept ) {
					ept=cpt;
					evt=i;
					vle=vl; vre=vr;
				}
			}
		}

		/* Check if we are done: no events or event very close to end
			of step - note we need to add a 'bit' to make sure the event
			will trigger */
		ept+=SHORTEVENTRATIO*TIMESTEP;
		if( evt<0 || ept>=tf ) break;
#ifdef MIDSTEPEVENTDEBUG
		printf("Have event %li in interval %e..%e at %e\n",evt,t0,tf,ept);
		printf("Trigger values: %e..%e\n",vle,vre);
#endif

		/* Step to where we suspect the event is, and check */
		h=ept-t0;
		w[0]=t0+h;
		/* Take Implicit Euler step */
		for(i=0;i<NDIFF;i++) {
			for(j=0;j<NDIFF;j++) fy[i*NDIFF+j]=-fy0[i*NDIFF+j];
			fy[i*(NDIFF+1)]+=1.0/h;
			ft[i]=yp0[i]+h*ft0[i];
		}
		DecompCInc(NDIFF,fy,NDIFF,ip);
		SolveCInc(NDIFF,fy,NDIFF,ip,ft);
		for(i=0;i<NDIFF;i++) y[i]=y0[i]+ft[i];
		/* Interpolate inputs */
		vr=h/(tf-t0);
		for(i=NDIFF+NIX1-NINP;i<NDIFF+NIX1;i++) y[i]=y0[i]+vr*(y[i]-y0[i]);
		/* Re-evaluate index-1 and derivatives */
		fp(NEQ,w[0],y,yp);
		if( IS_UNDEF(yp[0]) ) {
			ssSetErrorStatus(S,"index-1 and derivative evaluation failure");
			w[0]=tf;
			free(ws0);
			return;
		}
		eev(w[0],y,y,zc);
#ifdef EVTHYST
		if( vre>0.0 && modes[2*evt]==0 )
			cpt=zc[evt]-EVTHYST;
		else if( vre<0.0 && modes[2*evt+1]==1 )
			cpt=zc[evt]+EVTHYST;
#else
		cpt=zc[evt];
#endif
#ifdef MIDSTEPEVENTDEBUG
		printf("Value at event (t=%e) is %e\n",w[0],cpt);
#endif
		if( cpt*vre<0.0 ) {
			/* Failed, just restore w and give up ... */
#ifdef MIDSTEPEVENTDEBUG
			printf("############Event root failure in step t=%e..%e\n",t0,tf);
#endif
			for(i=0;i<1+2*NEQ+NPAR+NDFA+NEVT;i++) w[i]=ws1[i];
			break;
		}
		/* Run events */
		if(RunEvents(S,w,modes,0,23,EVTITER)) {
			w[0]=tf;
			free(ws0);
			return;
		}
	}
	free(ws0);
	RunEvents(S,w,modes,0,23,EVTITER);
}

#define MDL_UPDATE
static void mdlUpdate(SimStruct *S, int_T tid)
{
	real_T *w=ssGetRWork(S), *x = ssGetDiscStates(S);
	int_T i;

	UNUSED_ARG(tid);

	for(i=0;i<NDIFF;i++) x[i]=w[i+1]+TIMESTEP*w[NEQ+NPAR+1+i];
}

static void mdlOutputs(SimStruct *S, int_T tid)
{
	real_T *w, *y = ssGetOutputPortRealSignal(S,0);
	int_T *iw = ssGetIWork(S);
	int_T i;
	real_T *x;
	InputRealPtrsType p;

	UNUSED_ARG(tid);

	if(!iw[INIDREF]) {
		InitializeConditions(S);
		iw[INIDREF]=1;
	}
	if( ssIsVariableStepSolver(S) ) {
		ssSetErrorStatus(S,"code generated for fixed step, cannot be used with variable step");
		if (fptr) {
			writeErrorToFile(fptr,ssGetErrorStatus(S));
			fptr = NULL;
		}
		return;
	}
	if( !iw[DODERREF] ) {
		w=GetUpdatedWork(S,0);
		iw=ssGetIWork(S);
		if(RunEvents(S,w,iw,0,23,EVTITER)) return;
		if(MAXEVENTPERSTEP>0) iw[DODERREF]=1;
	}
	else {
		w=ssGetRWork(S);
		p = ssGetInputPortRealSignalPtrs(S,1);
		for(i=0;i<NPAR;i++) w[1+NEQ+i]=p[i][0];
		StepWithEvents(S);
	}
	x=ssGetDiscStates(S);
	for(i=0;i<NDIFF;i++) x[i]=w[i+1];
	otp(w[0],&w[1],&w[NEQ+NPAR+1]);
	y[ 0]=w[15];
	y[ 1]=w[19];
	y[ 2]=w[16];
	y[ 3]=w[18];
	y[ 4]=w[10];
	y[ 5]=w[11];
	y[ 6]=w[12];
	y[ 7]=w[ 3];
 	if ( fptr && ssIsMajorTimeStep(S) )
		if ( w[0]>=(lastsampletime+minsamplestep)*(1-1e-15) ) {
			fwrite(w,sizeof(real_T),NEQ+1,fptr);
			lastsampletime=w[0];
			if ( numpts++ == WARNNUMDATPTS )
				ssPrintf("Warning: At time t=%.16g, %d data points were written into file %s; consider increasing the minimum sample step, %.16g, to limit file size.\n",
						w[0],WARNNUMDATPTS,fstr,minsamplestep);
		}
}

static void mdlTerminate(SimStruct *S) {
	if (fptr) {
		fclose(fptr);
		fptr = NULL;
	}
}

#ifdef  MATLAB_MEX_FILE    /* Being compiled as a MEX-file? */
#include "simulink.c"      /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"       /* Code generation registration function */
#endif
