/***************************************************
 *Model source version: 2.4
 ***************************************************/

/***************************************************
 * DO NOT EDIT MANUALLY!
 * Automatically generated by Maple.
 * Created On: Thu May 05 14:28:15 2022.
***************************************************/

/* PLATFORM SPECIFICATION (Both commented out for Linux/Mac) */
/* 32-bit Windows */
/*#define WMI_WINNT 1*/
/* 64-bit Windows */
#define X86_64_WINDOWS 1

#define S_FUNCTION_NAME cbpm_dq_S_noH_D_RL_HA_Spin_16k
#define S_FUNCTION_LEVEL 2

#include "simstruc.h"
#include "math.h"

/***************************************************
* Variable Definition for System:

* Discrete state variable(s):
*    x[ 0] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.bPM_motor_complete.mechanical_Dynamics_flange.omega_m`(t)
*    x[ 1] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.oid`(t)
*    x[ 2] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.oiq`(t)
*    x[ 3] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.otheta_e`(t)
*    x[ 4] = diff(`Main.bpm_dq_S_noH_D_RL_HA_Spin.otheta_e`(t),t)
*
* Output variable(s):
*    y[ 0] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.bPM_motor_complete.bpm_core_model.iLd_var`(t)
*    y[ 1] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.bPM_motor_complete.bpm_core_model.iLq_var`(t)
*    y[ 2] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.oea`(t)
*    y[ 3] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.oeb`(t)
*    y[ 4] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.oec`(t)
*    y[ 5] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.oia`(t)
*    y[ 6] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.oib`(t)
*    y[ 7] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.oic`(t)
*    y[ 8] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.oid`(t)
*    y[ 9] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.oiq`(t)
*    y[10] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.oomega_e`(t)
*    y[11] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.bPM_motor_complete.mechanical_Dynamics_flange.omega_m`(t)
*    y[12] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.op_e_b`(t)
*    y[13] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.op_e_dq`(t)
*    y[14] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.op_rot_loss`(t)
*    y[15] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.op_shaft`(t)
*    y[16] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.ot_rot_loss`(t)
*    y[17] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.ot_shaft`(t)
*    y[18] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.ote`(t)
*    y[19] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.otheta_e`(t)
*    y[20] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.otheta_m`(t)
*
* Input variable(s):
*    u[ 0] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.iJDrum`(t)
*    u[ 1] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.iTr`(t)
*    u[ 2] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.iTs`(t)
*    u[ 3] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.im_unb`(t)
*    u[ 4] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.iva`(t)
*    u[ 5] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.ivb`(t)
*    u[ 6] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.ivc`(t)
*
* Parameter(s):
*    p[ 0] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.B` (default = .1e-3)
*    p[ 1] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.I_pk0` (default = 0.)
*    p[ 2] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.I_pk1` (default = 1.)
*    p[ 3] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.I_pk2` (default = 2.)
*    p[ 4] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.I_pk3` (default = 3.)
*    p[ 5] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.I_pk4` (default = 4.)
*    p[ 6] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.I_pk5` (default = 5.)
*    p[ 7] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.I_pk6` (default = 6.)
*    p[ 8] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.I_pk7` (default = 7.)
*    p[ 9] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Jrotor` (default = .515e-3)
*    p[10] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Ld0` (default = .884e-1)
*    p[11] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Ld_a0` (default = .2117e-1)
*    p[12] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Ld_a1` (default = .2117e-1)
*    p[13] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Ld_a2` (default = .2117e-1)
*    p[14] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Ld_a3` (default = .2117e-1)
*    p[15] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Ld_a4` (default = .2117e-1)
*    p[16] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Ld_a5` (default = .2117e-1)
*    p[17] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Ld_a6` (default = .2117e-1)
*    p[18] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Ld_a7` (default = .2117e-1)
*    p[19] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Lq0` (default = .972e-1)
*    p[20] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Lq_b0` (default = .2744e-1)
*    p[21] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Lq_b1` (default = .2777e-1)
*    p[22] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Lq_b2` (default = .2742e-1)
*    p[23] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Lq_b3` (default = .2646e-1)
*    p[24] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Lq_b4` (default = .2426e-1)
*    p[25] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Lq_b5` (default = .2329e-1)
*    p[26] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Lq_b6` (default = .2241e-1)
*    p[27] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Lq_b7` (default = .2241e-1)
*    p[28] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.NPP` (default = 3.)
*    p[29] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Rot_Loss_Power0` (default = 0.)
*    p[30] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Rot_Loss_Power1` (default = 1.)
*    p[31] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Rot_Loss_Power2` (default = 12.)
*    p[32] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Rot_Loss_Power3` (default = 19.)
*    p[33] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Rot_Loss_Power4` (default = 26.)
*    p[34] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Rot_Loss_Power5` (default = 35.)
*    p[35] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Rot_Loss_Power6` (default = 41.)
*    p[36] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Rot_Loss_Power7` (default = 56.)
*    p[37] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Rot_Loss_Speed0` (default = 0.)
*    p[38] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Rot_Loss_Speed1` (default = .5e3)
*    p[39] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Rot_Loss_Speed2` (default = .3e4)
*    p[40] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Rot_Loss_Speed3` (default = .4e4)
*    p[41] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Rot_Loss_Speed4` (default = .5e4)
*    p[42] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Rot_Loss_Speed5` (default = .7e4)
*    p[43] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Rot_Loss_Speed6` (default = .12e5)
*    p[44] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Rot_Loss_Speed7` (default = .18e5)
*    p[45] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Rot_Loss_enable` (default = 1.)
*    p[46] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Rot_Loss_omega_th` (default = .1e2)
*    p[47] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Rs0` (default = 9.15)
*    p[48] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.TrRef` (default = 22.)
*    p[49] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.TsRef` (default = 22.)
*    p[50] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.Ts` (default = .2e-3)
*    p[51] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.alpha_s` (default = .4e-2)
*    p[52] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.d_magnet` (default = .206e-2)
*    p[53] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.phiPM1` (default = .1151)
*    p[54] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.HA_Spin_Mechanics.CF` (default = 1.)
*    p[55] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.HA_Spin_Mechanics.TR` (default = 1.)
*    p[56] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.HA_Spin_Mechanics.damp` (default = 1.)
*    p[57] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.HA_Spin_Mechanics.damper3_1.B` (default = 0.)
*    p[58] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.HA_Spin_Mechanics.damper3_1.C` (default = 0.)
*    p[59] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.HA_Spin_Mechanics.fixed.phi0` (default = 0., unit = [rad])
*    p[60] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.HA_Spin_Mechanics.gain11.k` (default = -9.8, unit = [1])
*    p[61] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.HA_Spin_Mechanics.gain21.k` (default = -1., unit = [1])
*    p[62] = `Main.bpm_dq_S_noH_D_RL_HA_Spin.HA_Spin_Mechanics.r_unb` (default = 1.)
*
* Options:
* Table handling:
*    Export lookup as csv: false
* Optimization:
*    Code optimization level: 3
* Constraint handling:
*    Max projection iterations: 50
*    Error tolerance: .1e-4
*    Apply during events: true
* Event handling:
*    Max event iter: 100
*    Width of event hysteresis band: .1e-6
* Baumgarte constraint stabilization:
*    Apply Baumgarte: false
* Fixed-step integrator:
*    Optimize for fixed-step: true
*    Add failure handling: false
* Discretization:
*    Export as discrete: true
*    Embedded solver: RK4
*    Discrete step size: .625e-4
*    Allow intermediate steps: false
* Diagnostics:
*    Add outputs for log: false
*
* MapleSim version: 1539851
*
************************************************/

/* Set up fixed initial condition mask */
int_T icmask[5] = {
	1,0,0,0,0};

/* Configurable parameters */
#define TIMESTEP 6.250000e-05
#define CONITER 50
#define CONTOL 1.000000e-05
#define INITCONITER 100
#define INITCONTOL 1.000000e-10
#define INITITER 50
#define INITTOL 1.000000e-08
#define INITWEIGHT 2.000000e+01
#define EVTITER 100
#define EVTPROJ 1
#define EVTHYST 1.000000e-07
#define INCONTOL 1e200

/* Fixed parameters */
#define NDIFF 5
#define NDFA 5
#define NEQ 71
#define NPAR 63
#define NDPAR 2
#define NINP 7
#define NDISC 13
#define NIX1 53
#define NOUT 21
#define NCON 1
#define NEVT 2
#ifdef EVTHYST
#define NZC 2*NEVT
#else
#define NZC NEVT
#endif
#define INIDREF (2*NEVT+2*NZC)

#define MAXSTRLENGTH 1000
#define WARNNUMDATPTS 100000
#define IS_PARAM_DOUBLE(pVal) (mxIsNumeric(pVal) && !mxIsLogical(pVal) &&\
!mxIsEmpty(pVal) && !mxIsSparse(pVal) && !mxIsComplex(pVal) && mxIsDouble(pVal))

static FILE *fptr = NULL;
static char_T fstr[MAXSTRLENGTH];
static real_T nData[2] = {1.0*NEQ,1.0*NPAR};
static real_T lastsampletime;
static real_T minsamplestep;
static int_T numpts;

static void writeErrorToFile(FILE *fptr, const char_T *errstr)
{
	const char_T *err, uerr[]="unknown error";
	int_T i;
	real_T d;

	if (errstr)
		err = errstr;
	else
	err = uerr;

	d = -1e10; /*terminate value*/
	fwrite(&d,sizeof(real_T),1,fptr);
	for(i=0;;i++) {
		d = (real_T)err[i];
		fwrite(&d,sizeof(real_T),1,fptr);
		if (!err[i]) break;
	}

	fclose(fptr);
}

static real_T dsn_zero=0.0;
static unsigned char dsn_undefC[8] = { 0, 0, 0, 0, 0, 0, 0xF8, 0x7F };
static real_T *dsn_undef = (real_T *)&dsn_undefC;
static unsigned char dsn_posinfC[8] = { 0, 0, 0, 0, 0, 0, 0xF0, 0x7F };
static real_T *dsn_posinf = (real_T *)&dsn_posinfC;
static unsigned char dsn_neginfC[8] = { 0, 0, 0, 0, 0, 0, 0xF0, 0xFF };
static real_T *dsn_neginf = (real_T *)&dsn_neginfC;
#define trunc(v) ( (v>0.0) ? floor(v) : ceil(v) )
#define IS_UNDEF(a) (a-a!=0. || (a!=0. && a-2.*a==0.))
#define UNUSED(a) ((void)(a))
static double avoidcompilerwarn() { return(dsn_zero+*dsn_undef+*dsn_posinf+*dsn_neginf); }
#ifndef M_INT
# if defined _MINGW64 || defined X86_64_WINDOWS
#  define M_INT long long
# elif defined __x86_64__ || defined __ppc64__
#  define M_INT long
# elif defined _M_X64
#  define M_INT long long
# else
#  define M_INT long
# endif
#endif

static real_T dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_LUT_U_46_U_LUT_U_row_U_selector_U_46_U_proc(real_T ix, real_T x0, real_T x1, real_T x2, real_T x3, real_T x4, real_T x5, real_T x6, real_T x7, real_T y0, real_T y1, real_T y2, real_T y3, real_T y4, real_T y5, real_T y6, real_T y7, real_T *_U_ox0_U_out, real_T *_U_ox1_U_out, real_T *_U_oy0_U_out, real_T *_U_oy1_U_out);

static real_T dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_Rotational_U_Losses_U_46_U_Rot_U_Loss_U_tau_U_46_U_proc(real_T omega_U_m, real_T omega_U_m_U_th, real_T P_U_rot_U_loss);



#ifdef MSVC
#pragma optimize( "gty", on)
#endif
#ifndef INCONTOL
#define INCONTOL 1e-14
#endif

static void LSQDecompSolve(M_INT n, real_T *A, M_INT Ainc, M_INT *ip, real_T *b)
{
	M_INT i,j,k,r,c,lsq,cp;
	real_T s,t;

	for(i=0;i<n;i++) {
		if(b[i]-b[i]!=0.0 || (b[i]!=0. && b[i]-2.*b[i]==0.)) { ip[n-1]=0; A[0]=1.; for(j=0;j<n;j++) b[j]=*dsn_undef; return; }
		t = fabs(A[i*Ainc]);
		for(j=1;j<n;j++) {
			s = fabs(A[i*Ainc+j]);
			if(s>t) t = s;
		}
		if( t==0.0 )
			A[i*Ainc+n] = 1.0;
		else {
			t = 1.0/t;
			for(j=0;j<n;j++) A[i*Ainc+j] *= t;
			b[i] *= t;
			A[i*Ainc+n] = t;
		}
	}

	for(j=0;j<n;j++) {
		t = fabs(A[j]);
		for(i=1;i<n;i++) {
			s = fabs(A[i*Ainc+j]);
			if(s>t) t = s;
		}
		if( t==0.0 )
			A[n*Ainc+j] = 1.0;
		else {
			t = 1.0/t;
			for(i=0;i<n;i++) A[i*Ainc+j] *= t;
			A[n*Ainc+j] = t;
		}
	}

	ip[n-1] = 0;
	lsq = 0;
	cp = 0;
	for(k=0;k<n;k++) {
		r = 0; c = 0; t = 0.0;
		if( cp<n ) {
			for(cp=cp+1;cp<n;cp++) {
				for(i=k;i<n;i++) {
					s = fabs(A[i*Ainc+cp]);
					if(s>t) { r = i; c = cp; t = s; }
				}
				if( t>0.5 ) break;
			}
		}
		if( cp>=n ) {
			for(i=k;i<n;i++)
				for(j=k;j<n;j++) {
					s = fabs(A[i*Ainc+j]);
					if(s>t) { r = i; c = j; t = s; }
				}
		}
		if( t<1e-10 ) {
			if( k==0 ) { ip[n-1]=0; A[0]=2.; for(j=0;j<n;j++) b[j]=*dsn_undef; return; }
			if( lsq ) { ip[n-1]=0; A[0]=3.; for(j=0;j<n;j++) b[j]=*dsn_undef; return; }
			lsq = 1;
			t = 1e-16;
			for(i=0;i<k;i++) {
				s = fabs(b[i]);
				if(s>t) t = s;
			}
			for(i=k;i<n;i++) {
				if( fabs(b[i])/t>INCONTOL*n ) { ip[n-1]=0; A[0]=4.; for(j=0;j<n;j++) b[j]=*dsn_undef; return; }
				b[i] = 0.0;
			}

			for(r=k;r<n;r++) {
				for(i=k;i<n;i++) A[i*Ainc+n+r] = 0.0;
				A[r*Ainc+n+r] = 1.0;
				A[(k-1)*Ainc+n+r] = -A[(k-1)*Ainc+r]/A[(k-1)*Ainc+k-1];
				for(i=k-1;i>=0;i--) {
					A[i*Ainc+n+r] = A[i*Ainc+r];
					for(j=i+1;j<k;j++)
						A[i*Ainc+n+r] += A[i*Ainc+j]*A[j*Ainc+n+r];
					A[i*Ainc+n+r] = -A[i*Ainc+n+r]/A[i*(Ainc+1)];
				}
			}
			for(r=0;r<k;r++) {
				s = -1.0/A[r*(Ainc+1)];
				for(i=k;i<n;i++)
					if( A[r*Ainc+n+i]!=0.0 ) {
						t = s*A[r*Ainc+n+i];
						A[i*Ainc+r] += t;
						for(j=r+1;j<n;j++)
							A[j*Ainc+n+i] += t*A[r*Ainc+j];
						b[i] += t*b[r];
					}
			}
			for(i=k;i<n;i++)
				for(j=k;j<n;j++)
					A[i*Ainc+j] = A[j*Ainc+n+i];
			r = 0; c = 0; t = 0.0;
			for(i=k;i<n;i++)
				for(j=k;j<n;j++) {
					s = fabs(A[i*Ainc+j]);
					if(s>t) { r = i; c = j; t = s; }
				}
			if( t<1e-10 ) { ip[n-1]=0; A[0]=3.; for(j=0;j<n;j++) b[j]=*dsn_undef; return; }
		}
		if( !lsq ) ip[n-1]++;
		if( k==n-1 ) break;
		ip[k] = r;
		ip[n+k] = c;
		if( r>k ) {
			for(j=0;j<n;j++) {
				t = A[r*Ainc+j]; A[r*Ainc+j] = A[k*Ainc+j]; A[k*Ainc+j] = t;
			}
			t = b[r]; b[r] = b[k]; b[k] = t;
		}
		if( c>k )
			for(i=0;i<n;i++) {
				t = A[i*Ainc+c]; A[i*Ainc+c] = A[i*Ainc+k]; A[i*Ainc+k] = t;
			}
		s = -1.0/A[k*(Ainc+1)];
		for(i=k+1;i<n;i++)
			if( A[i*Ainc+k]!=0.0 ) {
				t = s*A[i*Ainc+k];
				A[i*Ainc+k] = t;
				for(j=k+1;j<n;j++)
					A[i*Ainc+j] += t*A[k*Ainc+j];
				b[i] += t*b[k];
			}
	}
	for(j=n-1;j>0;j--) {
		b[j] = b[j]/A[j*(Ainc+1)];
		t = -b[j];
		for(i=0;i<j;i++)
			b[i] += t*A[i*Ainc+j];
	}
	b[0] = b[0]/A[0];
	for(j=n-2;j>=0;j--) {
		i = ip[n+j];
		if(i!=j) {
			t = b[i]; b[i] = b[j]; b[j] = t;
		}
	}
	for(j=0;j<n;j++) b[j] *= A[n*Ainc+j];
}
#ifdef MSVC
#pragma optimize( "", on)
#endif

#ifdef MSVC
#pragma optimize( "gty", on)
#endif
static void DecompCInc(M_INT n, real_T *A, M_INT Ainc, M_INT *ip)
{
	M_INT i,j,k,m;
	real_T t;

	ip[n-1]=1;
	for(k=0;k<n-1;k++) {
		m=k;
		for(i=k+1;i<n;i++)
			if( fabs(A[i*Ainc+k])>fabs(A[m*Ainc+k]) ) m=i;
		ip[k]=m;
		if( m!=k ) ip[n-1]=-ip[n-1];
		t=A[m*Ainc+k]; A[m*Ainc+k]=A[(Ainc+1)*k]; A[(Ainc+1)*k]=t;
		if( t==0.0 ) { ip[n-1]=0; return; }
		t=-1.0/t;
		for(i=k+1;i<n;i++) A[i*Ainc+k]=A[i*Ainc+k]*t;
		for(j=k+1;j<n;j++) {
			t=A[m*Ainc+j]; A[m*Ainc+j]=A[k*Ainc+j]; A[k*Ainc+j]=t;
			if( t!=0.0 )
				for(i=k+1;i<n;i++) A[i*Ainc+j]+=A[i*Ainc+k]*t;
		}
	}
	if(A[(n-1)*(Ainc+1)]==0.0) ip[n-1]=0;
}
#ifdef MSVC
#pragma optimize( "", on)
#endif

#ifdef MSVC
#pragma optimize( "gty", on)
#endif
static void MultiSolveCInc(M_INT n, real_T *A, M_INT Ainc, M_INT *ip, M_INT nb, real_T *b, M_INT binc)
{
	M_INT i,j,k,m;
	real_T t;

	if( n>1 ) {
		for(j=0;j<n-1;j++) {
			m=ip[j];
			for(k=0;k<nb;k++) {
				t=b[m*binc+k]; b[m*binc+k]=b[j*binc+k]; b[j*binc+k]=t;
				for(i=j+1;i<n;i++) b[i*binc+k]+=A[i*Ainc+j]*t;
			}
		}
		for(j=n-1;j>0;j--) {
			for(k=0;k<nb;k++) {
				b[j*binc+k]=b[j*binc+k]/A[(Ainc+1)*j];
				t=-b[j*binc+k];
				for(i=0;i<=j-1;i++) b[i*binc+k]+=A[i*Ainc+j]*t;
			}
		}
	}
	for(k=0;k<nb;k++)
		b[k]=b[k]/A[0];
}
#ifdef MSVC
#pragma optimize( "", on)
#endif

static real_T dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_LUT_U_46_U_LUT_U_row_U_selector_U_46_U_proc(real_T ix, real_T x0, real_T x1, real_T x2, real_T x3, real_T x4, real_T x5, real_T x6, real_T x7, real_T y0, real_T y1, real_T y2, real_T y3, real_T y4, real_T y5, real_T y6, real_T y7, real_T *_U_ox0_U_out, real_T *_U_ox1_U_out, real_T *_U_oy0_U_out, real_T *_U_oy1_U_out)
{
	real_T row, ox0, ox1, oy0, oy1;

	if( ( (ix==x0) || (x0<ix) ) && (ix<x1) ) {
		row = 1.;
		ox0 = x0;
		ox1 = x1;
		oy0 = y0;
		oy1 = y1;
	}
	else if( ( (ix==x1) || (x1<ix) ) && (ix<x2) ) {
		row = 2.;
		ox0 = x1;
		ox1 = x2;
		oy0 = y1;
		oy1 = y2;
	}
	else if( ( (ix==x2) || (x2<ix) ) && (ix<x3) ) {
		row = 3.;
		ox0 = x2;
		ox1 = x3;
		oy0 = y2;
		oy1 = y3;
	}
	else if( ( (ix==x3) || (x3<ix) ) && (ix<x4) ) {
		row = 4.;
		ox0 = x3;
		ox1 = x4;
		oy0 = y3;
		oy1 = y4;
	}
	else if( ( (ix==x4) || (x4<ix) ) && (ix<x5) ) {
		row = 5.;
		ox0 = x4;
		ox1 = x5;
		oy0 = y4;
		oy1 = y5;
	}
	else if( ( (ix==x5) || (x5<ix) ) && (ix<x6) ) {
		row = 6.;
		ox0 = x5;
		ox1 = x6;
		oy0 = y5;
		oy1 = y6;
	}
	else if( ( (ix==x6) || (x6<ix) ) && ( (ix<x7) || (ix==x7) ) ) {
		row = 7.;
		ox0 = x6;
		ox1 = x7;
		oy0 = y6;
		oy1 = y7;
	}
	else {
		row = 8.;
		ox0 = x7;
		ox1 = x7+0.1;
		oy0 = y7;
		oy1 = y7+0.1;
	}
	*_U_ox0_U_out = ox0;
	*_U_ox1_U_out = ox1;
	*_U_oy0_U_out = oy0;
	*_U_oy1_U_out = oy1;
	return(row);
}

static real_T dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_Rotational_U_Losses_U_46_U_Rot_U_Loss_U_tau_U_46_U_proc(real_T omega_U_m, real_T omega_U_m_U_th, real_T P_U_rot_U_loss)
{
	real_T t_U_rot_U_loss;

	if( fabs(omega_U_m)<=omega_U_m_U_th )
		t_U_rot_U_loss = 0.;
	else
		t_U_rot_U_loss = P_U_rot_U_loss/omega_U_m;
	return(t_U_rot_U_loss);
}

static void fp(int_T N, real_T T, real_T *Y, real_T *YP)
{
	real_T M[12], V[2], Z[11], td1;
	int_T ti1, ti2, ti3;
	M_INT P[3];

	UNUSED(N);
	UNUSED(T);
	YP[3] = Y[4];
	if( Y[59]>=0. )
		Y[25] = Y[59];
	else
		Y[25] = -Y[59];
	if( Y[79]<Y[25] )
		Y[26] = Y[79];
	else if( Y[25]<Y[72] )
		Y[26] = Y[72];
	else
		Y[26] = Y[25];
	Y[9] = dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_LUT_U_46_U_LUT_U_row_U_selector_U_46_U_proc(Y[26],Y[72],Y[73],Y[74],Y[75],Y[76],Y[77],Y[78],Y[79],Y[82],Y[83],Y[84],Y[85],Y[86],Y[87],Y[88],Y[89],&Y[5],&Y[6],&Y[7],&Y[8]);
	if( Y[58]>=0. )
		Y[27] = Y[58];
	else
		Y[27] = -Y[58];
	Z[0] = Y[5]-Y[6];
	Z[0] = 1.0/Z[0];
	Y[29] = (Y[7]-Y[8])*Z[0]*(Y[26]-Y[5])+Y[7];
	if( Y[79]<Y[27] )
		Y[28] = Y[79];
	else if( Y[27]<Y[72] )
		Y[28] = Y[72];
	else
		Y[28] = Y[27];
	Y[14] = dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_LUT_U_46_U_LUT_U_row_U_selector_U_46_U_proc(Y[28],Y[72],Y[73],Y[74],Y[75],Y[76],Y[77],Y[78],Y[79],Y[91],Y[92],Y[93],Y[94],Y[95],Y[96],Y[97],Y[98],&Y[10],&Y[11],&Y[12],&Y[13]);
	Z[0] = Y[10]-Y[11];
	Z[0] = 1.0/Z[0];
	Y[30] = (Y[12]-Y[13])*Z[0]*(Y[28]-Y[10])+Y[12];
	Y[32] = Y[30]*Y[2];
	Z[0] = Y[60];
	Z[1] = Y[61];
	Z[2] = cos(Z[1]);
	Z[3] = Y[55];
	Z[4] = Y[56];
	Z[1] = sin(Z[1]);
	Z[5] = Y[57];
	Z[6] = 1.0/Y[29];
	Z[7] = (Y[53]-Y[120])*Y[122]+1.;
	Z[8] = Z[4]+Z[5];
	Z[9] = Z[2]*Z[6];
	Z[4] = Z[4]-Z[5];
	Z[5] = 0.3333333333333333333;
	Z[10] = 0.577350269189625763;
	YP[1] = Z[10]*Z[1]*Z[6]*Z[4]-Z[5]*Z[9]*Z[8]-Z[6]*(Z[7]*Y[1]*Y[118]-Z[0]*Y[32])+0.6666666666666666667*Z[9]*Z[3];
	Y[31] = Y[124]*(Y[123]*(Y[119]-Y[52])+1.)+Y[29]*Y[1];
	Z[6] = 1.0/Y[30];
	Z[1] = Z[1]*Z[6];
	YP[2] = Z[5]*Z[1]*Z[8]+Z[10]*Z[2]*Z[6]*Z[4]-Z[6]*(Z[7]*Y[2]*Y[118]+Z[0]*Y[31])-0.6666666666666666667*Z[1]*Z[3];
	if( Y[0]>=0. )
		td1 = Y[0];
	else
		td1 = -Y[0];
	Y[34] = 9.5493*td1;
	Y[38] = 1.5*Y[99]*(Y[2]*Y[31]-Y[1]*Y[32]);
	if( Y[115]<Y[34] )
		Y[35] = Y[115];
	else if( Y[34]<Y[108] )
		Y[35] = Y[108];
	else
		Y[35] = Y[34];
	Y[19] = dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_LUT_U_46_U_LUT_U_row_U_selector_U_46_U_proc(Y[35],Y[108],Y[109],Y[110],Y[111],Y[112],Y[113],Y[114],Y[115],Y[100],Y[101],Y[102],Y[103],Y[104],Y[105],Y[106],Y[107],&Y[15],&Y[16],&Y[17],&Y[18]);
	Z[0] = Y[15]-Y[16];
	Z[0] = 1.0/Z[0];
	Y[37] = -((Y[16]-Y[35])*Y[17]+(Y[35]-Y[15])*Y[18])*Z[0]*Y[116];
	if( Y[68]==1. ) {
		Z[0] = fabs((9.54929658551372013*Y[4])/(Y[99]*Y[126]));
		Y[21] = Z[0]*(Z[0]*Y[129]+Y[128])+Y[127];
	}
	else
		Y[21] = 0.0156;
	if( Y[4]/(Y[99]*Y[126])>0. )
		ti1 = 1;
	else if( Y[4]/(Y[99]*Y[126])<0. )
		ti1 = -1;
	else
		ti1 = 0;
	Y[24] = ((real_T)ti1)*Y[125]*Y[132];
	Y[20] = (dsn_U_BPM_U_release_U_46_U_Source_U_development_U_46_U_BPM_U_2022_U_46_U_Integrated_U_Electrical_U_46_U_CrossModules_U_46_U_Rotational_U_Losses_U_46_U_Rot_U_Loss_U_tau_U_46_U_proc(Y[0],Y[117],Y[37]));
	Y[23] = -(Y[21]*Y[4])/(Y[99]*Y[126]);
	Y[36] = Y[4];
	for(ti2=0;ti2<=1;ti2++)
		for(ti3=0;ti3<=1;ti3++)
			M[ti2*4+ti3] = 0.;
	for(ti2=0;ti2<=1;ti2++)
		V[ti2] = 0.;
	Z[0] = 1.0/Y[99];
	M[0] = -Z[0];
	Z[1] = 1.0/Y[80];
	M[1] = Z[1];
	V[0] = (Y[0]*Y[71]-Y[38])*Z[1];
	Z[1] = 1.0/Y[126];
	M[4] = Y[51]*Z[0]*Z[1];
	M[5] = Y[126];
	V[1] = Y[23]+Y[24]+Y[133]*Y[131]*sin(Z[0]*Z[1]*Y[3])*Y[54]-Y[126]*Y[20];
	LSQDecompSolve(2,M,4,P,V);
	if( P[1]==0 ) {
		YP[0] = (*dsn_undef);
		return;
	}
	YP[4] = V[0];
	Y[33] = V[1];
	YP[0] = (Y[33]+Y[38]-Y[0]*Y[71])/Y[80];
	Y[22] = (Y[51]*YP[4])/(Y[99]*Y[126])-Y[23];
	Y[39] = YP[4];
}

static void otp(real_T T, real_T *Y, real_T *YP)
{
	real_T Z[11];

	UNUSED(T);
	Y[40] = 0.;
	Y[41] = 0.;
	Y[42] = 0.;
	Z[0] = Y[61];
	Z[1] = sin(Z[0]);
	Z[0] = cos(Z[0]);
	Z[2] = Y[2]*Z[1];
	Z[3] = Y[1]*Z[0];
	Z[4] = Z[2]-Z[3];
	Y[43] = -Z[4];
	Z[0] = Z[0]*Y[2];
	Z[1] = Y[1]*Z[1];
	Z[5] = 0.866025403784438645;
	Z[6] = Z[5]*(Z[1]+Z[0]);
	Z[7] = 0.5*Z[4];
	Y[44] = Z[6]+Z[7];
	Y[45] = Z[7]-Z[6];
	Z[6] = Y[20]-Y[38];
	Z[7] = Y[2]*Y[2];
	Z[8] = Y[1]*Y[1];
	Z[9] = Y[122]*(Z[8]+Z[7]);
	Z[10] = Z[6]*Y[0];
	Y[46] = Y[37]-Z[10]+1.5*Y[118]*(Z[9]*Y[53]+Z[7]+Z[8]-Z[9]*Y[120]);
	Z[7] = Y[56];
	Z[8] = Y[57];
	Z[9] = Z[7]-Z[8];
	Z[7] = Z[8]+Z[7];
	Y[47] = Z[5]*(Z[0]*Z[9]+Z[1]*Z[9])-Y[55]*Z[4]+0.5*(Z[2]*Z[7]-Z[3]*Z[7]);
	Y[48] = -Z[10];
	Y[49] = -Z[6];
	Y[50] = Y[3]/Y[99];
}

static void Rblkp(real_T T, real_T *Y, real_T *R, int_T prb, int_T code)
{
	UNUSED(T);
	if( prb==0 )
		R[0] = 1.;
	else if( prb==1 ) {
		if( code==1 ) {
			R[0] = 1.;
			R[1] = 2.;
		}
		else if( code==2 ) {
			R[0] = 1.;
			R[1] = 5.;
		}
		else if( code==3 )
			R[0] = Y[0]-Y[4]/Y[99];
	}
}

static void Jblkp(real_T T, real_T *Y, real_T *J, int_T prb)
{
	int_T ti1, ti2;

	UNUSED(T);
	if( prb==1 ) {
		for(ti1=0;ti1<=0;ti1++)
			for(ti2=0;ti2<=1;ti2++)
				J[ti1*5+ti2] = 0.;
		J[0] = 1.;
		J[1] = -1/Y[99];
	}
}

static void eev(real_T T, real_T *Y, real_T *Ypre, real_T *EA)
{
	UNUSED(Ypre);
	EA[0] = 20000.+(-9.54929658551372013*Y[4])/(Y[99]*Y[126]);
	EA[1] = T-Y[70];
}

static int_T eex(int_T N, real_T T, real_T *Y, real_T *Ypre)
{
	if( N==1 )
		Y[68] = 1.-Y[68];
	else if( N==2 ) {
		Y[69] = 1.;
		Y[70] = Y[70]+Y[121];
	}
	else if( N==3 ) {
		if( Y[66]==1. )
			Y[70] = Y[121]*( (((int_T)trunc(ceil(T/Y[121])))<0) ? 0. : ceil(T/Y[121]) )+1e-20;
		if( !(Y[72]<=Y[79]) ) {
			Y[67] = 1.;
			return(1);
		}
		if( !(Y[72]<=Y[79]) ) {
			Y[67] = 2.;
			return(1);
		}
		if( !(Y[108]<=Y[115]) ) {
			Y[67] = 3.;
			return(1);
		}
		if( (Y[69]==1.) && (Y[69]!=Ypre[69]) )
			Y[58] = Ypre[2];
		if( (Y[69]==1.) && (Y[69]!=Ypre[69]) )
			Y[59] = Ypre[1];
		if( (Y[69]==1.) && (Y[69]!=Ypre[69]) )
			Y[60] = Ypre[36];
		if( (Y[69]==1.) && (Y[69]!=Ypre[69]) )
			Y[61] = Ypre[3];
		if( (Y[69]==1.) && (Y[69]!=Ypre[69]) ) {
			if( T<=0.5*Y[121] )
				Y[62] = 1.;
			else
				Y[62] = 0.;
		}
		if( (Y[69]==1.) && (Y[69]!=Ypre[69]) ) {
			if( T<=0.5*Y[121] )
				Y[63] = 1.;
			else
				Y[63] = 0.;
		}
		if( (Y[69]==1.) && (Y[69]!=Ypre[69]) ) {
			if( T<=0.5*Y[121] )
				Y[64] = 1.;
			else
				Y[64] = 0.;
		}
		if( (Y[69]==1.) && (Y[69]!=Ypre[69]) ) {
			if( T<=0.5*Y[121] )
				Y[65] = 1.;
			else
				Y[65] = 0.;
		}
		if( !( (Y[62]==0.) || (Y[62]==1.) ) ) {
			Y[67] = 4.;
			return(1);
		}
		if( !( (Y[69]==0.) || (Y[69]==1.) ) ) {
			Y[67] = 5.;
			return(1);
		}
		if( !( (Y[63]==0.) || (Y[63]==1.) ) ) {
			Y[67] = 6.;
			return(1);
		}
		if( !( (Y[64]==0.) || (Y[64]==1.) ) ) {
			Y[67] = 7.;
			return(1);
		}
		if( !( (Y[65]==0.) || (Y[65]==1.) ) ) {
			Y[67] = 8.;
			return(1);
		}
		if( Y[66]==1. )
			Y[66] = 0.;
		if( Y[69]==1. )
			Y[69] = 0.;
	}
	return(0);
}

static int_T cpr(real_T T, real_T *Y)
{
	real_T v;
	int_T k;

	UNUSED(T);
	k = 0;
	if( (9.54929658551372013*Y[4])/(Y[99]*Y[126])<=20000. )
		v = 1.;
	else
		v = 0.;
	if( Y[68]!=v ) {
		Y[68] = v;
		k = 1;
	}
	return(k);
}

/*
	Projection: Use Rblkp,Jblkp constraint residual and Jacobian functions to
	project the input solution x back onto the constraint manfold.

	Return codes:
	0 - Successful completion
	1 - Entry of Residual or Jacobian is undefined/infinity
	2 - Row of Jacobian is zero, but residual is nonzero
	3 - Iteration limit reached
*/
#define JERR 1

static int_T Projection(
	real_T t,		/* Current time */
	real_T *x,		/* Current solution (updated) */
	real_T tol,		/* Tolerance limit for iteration */
	int_T maxiter,	/* Max iteration limit */
	real_T *w		/* Weight vector */
)
{
	int_T i, j, k, r, c, cb, iter, nc2;
	M_INT n, nblk, nc, ip[NDIFF],per[NDIFF],varmap[NDIFF];
	real_T scl, resmag, val, val2, R[NDIFF],J[NCON*NDIFF],A[NDIFF*NDIFF],
#ifdef JERR
				Rerr[NCON],Jerr[NCON*NDIFF],
#endif
				ULP=4.440223e-16;
#if NCON*NCON>NDIFF
	real_T iA[NCON*NCON];
#else
	real_T iA[NDIFF];
#endif

	/* Get number of blocks */
	Rblkp(t, x, R, 0, 0);
	nblk = (M_INT)(R[0]);
	for(cb=1;cb<=nblk;cb++) {
		/* Get problem size */
		Rblkp(t, x, R, cb, 1);
		nc = (M_INT)(R[0]);
		n = (M_INT)(R[1]);
		/* Get dep. variable mapping */
		Rblkp(t, x, R, cb, 2);
		for(i=0;i<n;i++) varmap[i]=(M_INT)(R[i])-1;

		for(iter=0;iter<maxiter;iter++) {

			/* Reset var. mapping */
			for(i=0;i<n;i++) per[i]=varmap[i];
			/* Compute the Jacobian and Residual at the current solution */
			Rblkp(t, x, R, cb, 3);
			Jblkp(t, x, J, cb);
#ifdef JERR
			for(i=0;i<nc;i++) {
				Rerr[i]=ULP*fabs(R[i]);
				for(j=0;j<n;j++) Jerr[i*NDIFF+j]=ULP*fabs(J[i*NDIFF+j]);
			}
#endif

			/* Scale the columns by the weight factor */
			if( w ) {
				for(j=0;j<n;j++) {
					for(i=0;i<nc;i++)
						J[NDIFF*i+j] /= w[per[j]];
#ifdef JERR
					for(i=0;i<nc;i++)
						Jerr[NDIFF*i+j] /= w[per[j]];
#endif
				}
			}

			/* Rescale rows of Jacobian so that maximum coeff is 1, validating */
			resmag = 0.0;
			for(i=0;i<nc;i++) {
				if( IS_UNDEF(R[i]) ) return(1);
				val = 0.0;
				for(j=0;j<n;j++) {
					if( IS_UNDEF(J[i*NDIFF+j]) ) return(1);
					val2 = fabs(J[i*NDIFF+j]);
					if( val2>val ) val = val2;
				}
				if( val==0. ) {
					if( R[i]!=0. )
						return(2);
				}
				else {
					val = 1.0/val;
					for(j=0;j<n;j++) J[i*NDIFF+j] *= val;
					R[i] *= val;
#ifdef JERR
					val = fabs(val);
					for(j=0;j<n;j++) Jerr[i*NDIFF+j] *= val;
					Rerr[i] *= val;
#endif
					resmag += R[i]*R[i];
				}
			}

			/* Compute J_hat from J
				The solving process will select the row with the largest residual,
				then choose the largest coeff, computing an approx.  of the condition
				as we go, stopping when the condition becomes too poor. */
			nc2 = nc;
			scl = 1.0;
			i = 0;
			while( i<nc2 ) {
				/* Search for row with largest residual */
				resmag = fabs(R[i]); r = i;
				for(j=i+1;j<nc2;j++) {
					val2 = fabs(R[j]);
					if( val2>resmag ) { resmag = val2; r = j; }
				}
				/* Check for termination on the first row of this iteration */
				if( i==0 && ( resmag<=tol || iter>=maxiter )) {
					nc2 = n+1; break;
				}

				/* Row 'r' has largest residual 'val', locate column with
					largest coeff */
				val = fabs(J[r*NDIFF+i]); c = i;
				for(j=i+1;j<n;j++) {
					val2 = fabs(J[r*NDIFF+j]);
					if( val2>val ) { val = val2; c = j; }
				}

#ifdef JERR
				if( (val+Jerr[r*NDIFF+c])*scl-val>=val*pow(fabs(tol),0.75) ) {
#else
				if( scl*val<sqrt(tol) ) {
#endif
					/* Coefficient is too small - remove row */
					if( r!=nc2-1 ) {
						for(j=0;j<n;j++) J[r*NDIFF+j] = J[(nc2-1)*NDIFF+j];
						R[r] = R[nc2-1];
#ifdef JERR
						for(j=0;j<n;j++) Jerr[r*NDIFF+j] = Jerr[(nc2-1)*NDIFF+j];
						Rerr[r] = Rerr[nc2-1];
#endif
					}
					nc2--;
				}
				else {
					/* Adjust condition estimate */
					scl *= val;
					/* Row/Column exchanges */
					if( c!=i ) {
						for(j=0;j<nc2;j++) { val=J[j*NDIFF+i]; J[j*NDIFF+i]=J[j*NDIFF+c]; J[j*NDIFF+c]=val; }
#ifdef JERR
						for(j=0;j<nc2;j++) { val=Jerr[j*NDIFF+i]; Jerr[j*NDIFF+i]=Jerr[j*NDIFF+c]; Jerr[j*NDIFF+c]=val; }
#endif
						j=per[i]; per[i]=per[c]; per[c]=j;
					}
					if( r!=i ) {
						for(j=i;j<n;j++) { val=J[i*NDIFF+j]; J[i*NDIFF+j]=J[r*NDIFF+j]; J[r*NDIFF+j]=val; }
						val=R[i]; R[i]=R[r]; R[r]=val;
#ifdef JERR
						for(j=i;j<n;j++) { val=Jerr[i*NDIFF+j]; Jerr[i*NDIFF+j]=Jerr[r*NDIFF+j]; Jerr[r*NDIFF+j]=val; }
						val=Rerr[i]; Rerr[i]=Rerr[r]; Rerr[r]=val;
#endif
					}
					/* Rescale if necessary */
					if( J[i*NDIFF+i]!=1.0 ) {
						val = 1.0/J[i*NDIFF+i];
						J[i*NDIFF+i] = 1.0;
						for(j=i+1;j<n;j++) J[i*NDIFF+j] = J[i*NDIFF+j]*val;
						R[i] *= val;
#ifdef JERR
						val = fabs(val);
						for(j=i;j<n;j++) Jerr[i*NDIFF+j] = Jerr[i*NDIFF+j]*val;
						Rerr[i] *= val;
#endif
					}
					/* Backsub */
					for(r=0;r<nc2;r++)
						if( r!=i && J[r*NDIFF+i]!=0.0 ) {
							for(c=i+1;c<n;c++) J[r*NDIFF+c] -= J[r*NDIFF+i]*J[i*NDIFF+c];
							R[r] -= J[r*NDIFF+i]*R[i];
#ifdef JERR
							val = fabs(J[r*NDIFF+i]);
							for(c=i+1;c<n;c++) Jerr[r*NDIFF+c] += val*Jerr[i*NDIFF+c];
							Rerr[r] += val*Rerr[i];
#endif
							J[r*NDIFF+i] = 0.0;
						}
					if( i==n-1 ) {
						nc2=n;
						break;
					}
					else
						i++;
				}
			}
			if( nc2==n+1 )
				/* Termination: residual within bound on first row */
				break;

			/* Compute A = J_hat * J_hat^T */
			for(j=0;j<nc2;j++)
				for(i=0;i<=j;i++) {
					A[i*nc2+j] = 0.0;
					for(k=0;k<n;k++) A[i*nc2+j]+=J[i*NDIFF+k]*J[j*NDIFF+k];
				}
			for(i=0;i<nc2;i++)
				for(j=0;j<i;j++)
					A[i*nc2+j]=A[j*nc2+i];

			/* Construct (J_hat * J_hat^T)^(-1) in iA */
			for(i=0;i<nc2*nc2;i++) iA[i]=0.0;
			for(i=0;i<nc2;i++) iA[i*(1+nc2)]=1.0;
			DecompCInc(nc2, A, nc2, ip);
			MultiSolveCInc(nc2, A, nc2, ip, nc2, iA, nc2);

			/* Multiply iA (nc2 x nc2) with R (nc2 x 1) to A (nc2 x 1)
				A = (J_hat * J_hat^T)^(-1) * R */
			for(i=0;i<nc2;i++) {
				A[i] = 0.0;
				for(k=0;k<nc2;k++) A[i] += iA[i*nc2+k]*R[k];
			}

			/* Multiply J_hat^T (NDIFF x nc2) with A (nc2 x 1) to iA (NDIFF x 1)
				 iA = J_hat^T * (J_hat * J_hat^T)^(-1) * R */
			for(i=0;i<n;i++) {
				iA[i] = 0.0;
				for(k=0;k<nc2;k++) iA[i] += J[k*NDIFF+i]*A[k];
			}

			val=0.0; for(i=0;i<n;i++) val+=x[per[i]]*x[per[i]]; val=sqrt(val);
			val2=0.0; for(i=0;i<n;i++) val2+=iA[i]*iA[i]; val2=sqrt(val2);
			val = val2/((val>0.1*val2)?val:(0.1*val2));
			if( val>0.1 ) {
				/* Solution is very far off - Use relaxed */
				val2 = ( tol>0.1/val )?tol:(0.1/val);
				if( w )
					for(i=0;i<n;i++) x[per[i]]-=val2*iA[i]/w[per[i]];
				else
					for(i=0;i<n;i++) x[per[i]]-=val2*iA[i];
			}
			else {
				/* Direct newton */
				if( w )
					for(i=0;i<n;i++) x[per[i]]-=iA[i]/w[per[i]];
				else
					for(i=0;i<n;i++) x[per[i]]-=iA[i];
			}
		}
		if( iter==maxiter ) return(3);
	}
	return(0);
}

/*
	ProjectInitial: Use weighted projection to find consistent initial
	data with fixed initial values.

	Return codes:
	0 - Successful completion
	2 - Projection not converging
	3 - Iteration limit reached
*/
static int_T ProjectInitial(
	real_T t,			/* t0 */
	real_T *x,			/* Current solution (updated) */
	real_T ptol,		/* Tolerance limit for iteration for projection */
	int_T pmaxiter,	/* Max iteration limit for projection */
	int_T *icmask,	/* Fixed IC mask vector */
	real_T tol,		/* Convergence tolerance */
	int_T maxiter,	/* Max limit for number of calls to projection */
	real_T W			/* Default fixed IC weight */
)
{
	int_T i, ip, iter;
	real_T delta1, delta2, val, w[NDIFF], ic[NDIFF];

	for(i=0;i<NDIFF;i++) {
		if( icmask[i]==0 ) {
			w[i] = 1.0;
			ic[i] = 0.0;
		}
		else {
			w[i] = W;
			ic[i] = x[i];
		}
	}

	delta1 = 1.0;
	for(iter=0;iter<maxiter;iter++) {
		/* Do weighted projection and check fixed IC deviation */
		ip=Projection(t,x,ptol,pmaxiter,w);
		if( ip>0 && ip!=3 ) return(2);

		delta2 = 0.0;
		for(i=0;i<NDIFF;i++)
			if( w[i]!=1.0 ) {
				val = 0.5*(fabs(x[i])+fabs(ic[i]));
				val = ( val > 1.0e-3 ) ? val : 1.0e-3;
				delta2+=fabs((x[i]-ic[i]))/(val);
			}

		/* Return if projection converged */
		if( delta2<=tol ) break;
		/* Check for adequate convergence rate */
		if( iter>2 && (delta2/delta1 > 0.9) ) return(2);
		/* Check iteration limit */
		if( iter==maxiter-1 ) { iter++; break; }

		/* Overwrite the solution vector with fixed IC values,
		   for next pass. */
		for(i=0;i<NDIFF;i++)
			if( w[i]!=1.0 ) x[i]=ic[i];

		delta1 = delta2;
	}
	/* Check iteration limit */
	if( iter==maxiter ) return(3); else return(0);
}

static void terminate(SimStruct *S, real_T T, real_T *Y, int_T j)
{
	char buf[10000];

	if(j==1) {
		sprintf(buf,"Modelica assertion (Main.bpm_dq_S_noH_D_RL_HA_Spin.I_pk0 <= Main.bpm_dq_S_noH_D_RL_HA_Spin.I_pk7) failed in Main.bpm_dq_S_noH_D_RL_HA_Spin.bPM_motor_complete.Inductance_saturation.LUT_Ld.limiter: Limiter: Limits must be consistent. However, uMax (=%0.6g) < uMin (=%0.6g)",Y[79],Y[72]);
		ssSetErrorStatus(S,buf);
	}
	if(j==2) {
		sprintf(buf,"Modelica assertion (Main.bpm_dq_S_noH_D_RL_HA_Spin.I_pk0 <= Main.bpm_dq_S_noH_D_RL_HA_Spin.I_pk7) failed in Main.bpm_dq_S_noH_D_RL_HA_Spin.bPM_motor_complete.Inductance_saturation.LUT_Lq.limiter: Limiter: Limits must be consistent. However, uMax (=%0.6g) < uMin (=%0.6g)",Y[79],Y[72]);
		ssSetErrorStatus(S,buf);
	}
	if(j==3) {
		sprintf(buf,"Modelica assertion (Main.bpm_dq_S_noH_D_RL_HA_Spin.Rot_Loss_Speed0 <= Main.bpm_dq_S_noH_D_RL_HA_Spin.Rot_Loss_Speed7) failed in Main.bpm_dq_S_noH_D_RL_HA_Spin.bPM_motor_complete.rot_loss_power.LUT_Rot_Loss.limiter: Limiter: Limits must be consistent. However, uMax (=%0.6g) < uMin (=%0.6g)",Y[115],Y[108]);
		ssSetErrorStatus(S,buf);
	}
	if(j==4) ssSetErrorStatus(S,"variable `Main.bpm_dq_S_noH_D_RL_HA_Spin.bPM_motor_complete.delay_Id_Iq.delay_omega.firstTrigger`(t) must be boolean valued");
	if(j==5) ssSetErrorStatus(S,"variable `Main.bpm_dq_S_noH_D_RL_HA_Spin.bPM_motor_complete.delay_Id_Iq.delay_omega.sampleTrigger`(t) must be boolean valued");
	if(j==6) ssSetErrorStatus(S,"variable `Main.bpm_dq_S_noH_D_RL_HA_Spin.bPM_motor_complete.delay_Id_Iq.delay_theta.firstTrigger`(t) must be boolean valued");
	if(j==7) ssSetErrorStatus(S,"variable `Main.bpm_dq_S_noH_D_RL_HA_Spin.bPM_motor_complete.delay_mech.delay_omega.firstTrigger`(t) must be boolean valued");
	if(j==8) ssSetErrorStatus(S,"variable `Main.bpm_dq_S_noH_D_RL_HA_Spin.bPM_motor_complete.delay_mech.delay_theta.firstTrigger`(t) must be boolean valued");
}

static int_T RunEvents(SimStruct *S, real_T *w, int_T *modes, int_T first, int_T termvar, int_T maxiter)
{
	real_T t,*y,*yp,*ypre,*tval;
	int_T *m=NULL,*oldmodes,*inc,*req;
	int_T i,flag,iter,evt,rc,failskip;

	/* Transfer data to approp. named arrays */
	t=w[0]; y=&w[1]; yp=&y[NEQ+NPAR]; ypre=&yp[NDFA]; tval=&ypre[NEQ];
	oldmodes=&modes[NZC]; inc=&oldmodes[NZC]; req=&inc[NEVT];
	/* Verify that no y values are undefined */
	for(i=0;i<NEQ;i++) if(IS_UNDEF(y[i])) {
		ssSetErrorStatus(S,"undefined value encountered on entry to RunEvents");
		if (fptr) {
			writeErrorToFile(fptr,ssGetErrorStatus(S));
			fptr = NULL;
		}
		return(-3);
	}

	/* Set 'm' to mode vector if we are variable step */
	if(ssGetNumNonsampledZCs(S)>0)
		m=ssGetModeVector(S);

	/* Set the old modes to the new and ypre to y */
	for(i=0;i<NZC;i++) oldmodes[i]=modes[i];
	for(i=0;i<NEQ;i++) ypre[i]=y[i];

	if(!first) {
		/* Check for events */
		eev(t,y,ypre,tval);
		flag=0;
		for(i=0;i<NEVT;i++) {
#ifdef EVTHYST
			if( tval[i]>EVTHYST && modes[2*i]==0 ) {
				modes[2*i]=1;
				if(req[i]>0 && y[req[i]-1]==1.0) oldmodes[2*i]=1;
				else flag=1;
			}
			else if( tval[i]<EVTHYST && modes[2*i]==1 ) {
				modes[2*i]=0; oldmodes[2*i]=0;
			}
			if( tval[i]>-EVTHYST && modes[2*i+1]==0) {
				modes[2*i+1]=1; oldmodes[2*i+1]=1;
			}
			else if( tval[i]<-EVTHYST && modes[2*i+1]==1 ) {
				modes[2*i+1]=0;
				if(inc[i] || (req[i]>0 && y[req[i]-1]==0.0)) oldmodes[2*i+1]=0;
				else flag=1;
			}
#else
			if( tval[i]>0.0 && modes[i]==0 ) {
				modes[i]=1;
				if(req[i]>0 && y[req[i]-1]==1.0) oldmodes[i]=1;
				else flag=1;
			}
			else if( tval[i]<0.0 && modes[i]==1 ) {
				modes[i]=0;
				if(inc[i] || (req[i]>0 && y[req[i]-1]==0.0)) oldmodes[i]=0;
				else flag=1;
			}
#endif
		}
		/* If no events, return, but still need to update modes as we may
			have a sign change for a decrease on an increase-only trigger */
		if(!flag) {
			if(m) for(i=0;i<NZC;i++) m[i]=modes[i];
			return(0);
		}
	}

	/* Iteration loop */
	failskip=0;
	for(iter=0;;iter++) {
		if( !first || iter>0 )
			/* Event loop */
			for(evt=0;evt<NEVT;evt++)
#ifdef EVTHYST
				if(modes[2*evt]!=oldmodes[2*evt] || modes[2*evt+1]!=oldmodes[2*evt+1]) {
#else
				if(modes[evt]!=oldmodes[evt]) {
#endif
					rc=eex(evt+1,t,y,ypre);
					if(termvar>=0 && y[termvar]>0.0) {
						i=(int_T)y[termvar];
						terminate(S,t,y,i);
						return(i);
					}
					/* Handle RC */
#ifdef EVTHYST
					oldmodes[2*evt]=modes[2*evt]; oldmodes[2*evt+1]=modes[2*evt+1];
#else
					oldmodes[evt]=modes[evt];
#endif
				}

		/* Discrete equations */
		rc=eex(NEVT+1,t,y,ypre);
		/* Fail skip */
		if(rc==8 && !failskip) {
			failskip=1;
			iter--;
			if(termvar>=0) y[termvar]=0.0;
		}
		else
			failskip=0;
		if(termvar>=0 && y[termvar]>0.0) {
			i=(int_T)y[termvar];
			terminate(S,t,y,i);
			return(i);
		}
		/* Handle RC */

		/* Check for termination */
		for(i=0;i<NEQ;i++) if(y[i]!=ypre[i]) break;
		if( !failskip && i==NEQ ) {
			/* Update modes and return */
			if(m) for(i=0;i<NZC;i++) m[i]=modes[i];
			return(0);
		}

		/* Check iter limit */
		if( iter>=maxiter ) {
			ssSetErrorStatus(S,"event iteration limit exceeded");
			if (fptr) {
				writeErrorToFile(fptr,ssGetErrorStatus(S));
				fptr = NULL;
			}
			return(-1);
		}

		/* Update index-1 equations */
		if(!failskip && NIX1>0) {
			fp(NEQ,t,y,yp);
			if( IS_UNDEF(yp[0]) ) {
				ssSetErrorStatus(S,"index-1 and derivative evaluation failure");
				if (fptr) {
					writeErrorToFile(fptr,ssGetErrorStatus(S));
					fptr = NULL;
				}
				return(-2);
			}
		}
		/* Verify that no y values are undefined */
		for(i=0;i<NEQ;i++) if(IS_UNDEF(y[i])) {
			ssSetErrorStatus(S,"undefined value encountered during event iteration");
			if (fptr) {
				writeErrorToFile(fptr,ssGetErrorStatus(S));
				fptr = NULL;
			}
			return(-4);
		}

		/* Projection */
		if(!first && !failskip && EVTPROJ) i=Projection(t,y,CONTOL,CONITER,NULL);

		/* Update pre */
		for(i=0;i<NEQ;i++) ypre[i]=y[i];
		if(failskip) continue;

		/* Evaluate event triggers, and update modes */
		eev(t,y,ypre,tval);
		for(i=0;i<NEVT;i++) {
#ifdef EVTHYST
			if( tval[i]>EVTHYST && modes[2*i]==0 ) {
				modes[2*i]=1;
				if(req[i]>0 && y[req[i]-1]==1.0) oldmodes[2*i]=1;
			}
			else if( tval[i]<EVTHYST && modes[2*i]==1 ) {
				modes[2*i]=0; oldmodes[2*i]=0;
			}
			if( tval[i]>-EVTHYST && modes[2*i+1]==0) {
				modes[2*i+1]=1; oldmodes[2*i+1]=1;
			}
			else if( tval[i]<-EVTHYST && modes[2*i+1]==1 ) {
				modes[2*i+1]=0;
				if(inc[i] || (req[i]>0 && y[req[i]-1]==0.0)) oldmodes[2*i+1]=0;
			}
#else
			if( tval[i]>0.0 && modes[i]==0 ) {
				modes[i]=1;
				if(req[i]>0 && y[req[i]-1]==1.0) oldmodes[i]=1;
			}
			else if( tval[i]<0.0 && modes[i]==1 ) {
				modes[i]=0;
				if(req[i]>0 && y[req[i]-1]==0.0) oldmodes[i]=0;
				if(inc[i]) oldmodes[i]=0;
			}
#endif
		}
	}
	return(0);
}

static void mdlCheckParameters(SimStruct *S)
{
	const mxArray *dpar1 = ssGetSFcnParam(S,1);

	if ( mxGetNumberOfElements(ssGetSFcnParam(S,1))!=1 || !IS_PARAM_DOUBLE(dpar1) ) {
		ssSetErrorStatus(S, "Minimum sample step must be a scalar");
		return;
	}
	else if (mxGetPr(ssGetSFcnParam(S,1))[0]<0) {
		ssSetErrorStatus(S, "Minimum sample step must be non-negative");
		return;
	}
}

static void mdlInitializeSizes(SimStruct *S)
{
	ssSetNumSFcnParams(S, NDPAR);
	if( ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S) ) {
		return;
	}
	else {
		mdlCheckParameters(S);
		if (ssGetErrorStatus(S) != NULL) return;
	}
	ssSetNumContStates(S, 0);
	ssSetNumDiscStates(S, NDIFF);

	if( !ssSetNumInputPorts(S, 3) ) return;
	ssSetInputPortWidth(S, 0, NDIFF);
	ssSetInputPortDirectFeedThrough(S, 0, 1);
	ssSetInputPortWidth(S, 1, NPAR);
	ssSetInputPortDirectFeedThrough(S, 1, 1);
	ssSetInputPortWidth(S, 2, NINP);
	ssSetInputPortDirectFeedThrough(S, 2, 1);

	if( !ssSetNumOutputPorts(S, 1) ) return;
	ssSetOutputPortWidth(S, 0, NOUT);

	ssSetNumSampleTimes(S, 1);
	ssSetNumRWork(S, 1+2*NEQ+NPAR+NDFA+NEVT);
	ssSetNumIWork(S, 2*NEVT+2*NZC+1);
	ssSetNumPWork(S, 0);
	ssSetNumModes(S, DYNAMICALLY_SIZED);
	ssSetNumNonsampledZCs(S, DYNAMICALLY_SIZED);

	ssSetOptions(S, SS_OPTION_EXCEPTION_FREE_CODE);
	ssSetOptions(S, SS_OPTION_CALL_TERMINATE_ON_EXIT);
}

#define MDL_SET_WORK_WIDTHS
static void mdlSetWorkWidths(SimStruct *S)
{
	if( ssIsVariableStepSolver(S) &&
		 ssGetSampleTime(S,0) == TIMESTEP &&
		 ssGetOffsetTime(S,0) == 0.0 ) {
		ssSetNumModes(S,NZC);
		ssSetNumNonsampledZCs(S,NZC);
	}
	else {
		ssSetNumModes(S,0);
		ssSetNumNonsampledZCs(S,0);
	}
    
    /*Enabling multiple execution instances*/
    ssSupportsMultipleExecInstances(S, true);
}

static void mdlInitializeSampleTimes(SimStruct *S)
{
	ssSetSampleTime(S, 0, TIMESTEP);
	ssSetOffsetTime(S, 0, 0.0);
	ssSetModelReferenceSampleTimeDefaultInheritance(S);
}

static void InitializeConditions(SimStruct *S)
{
	real_T *w = ssGetRWork(S);
	int_T *iw = ssGetIWork(S);
	real_T *x = ssGetDiscStates(S);
	InputRealPtrsType i = ssGetInputPortRealSignalPtrs(S,2);
	InputRealPtrsType p = ssGetInputPortRealSignalPtrs(S,1);
	int_T j, k;

	if (fptr) {
		fclose(fptr);
		fptr = NULL;
	}
	mxGetString(ssGetSFcnParam(S,0),fstr,MAXSTRLENGTH);
	if (fstr!="\0")
		fptr = fopen(fstr,"wb");
	minsamplestep = (mxGetPr(ssGetSFcnParam(S,1)))[0];
	lastsampletime = -1e10;
	numpts = 0;

	w[0] =  0.0;
	w[1] =  0.00000000000000000e+00;
	w[2] =  0.00000000000000000e+00;
	w[3] =  0.00000000000000000e+00;
	w[4] =  2.99999999999999960e+00;
	w[5] =  0.00000000000000000e+00;
	w[6] =  0.00000000000000000e+00;
	w[7] =  1.00000000000000000e+00;
	w[8] =  2.11700000000000010e-02;
	w[9] =  2.11700000000000010e-02;
	w[10] =  1.00000000000000000e+00;
	w[11] =  0.00000000000000000e+00;
	w[12] =  1.00000000000000000e+00;
	w[13] =  2.74399999999999990e-02;
	w[14] =  2.77700000000000000e-02;
	w[15] =  1.00000000000000000e+00;
	w[16] =  0.00000000000000000e+00;
	w[17] =  5.00000000000000000e+02;
	w[18] =  0.00000000000000000e+00;
	w[19] =  1.00000000000000000e+00;
	w[20] =  1.00000000000000000e+00;
	w[21] =  0.00000000000000000e+00;
	w[22] =  1.00000000000000000e+00;
	w[23] = -8.24217093308684310e+00;
	w[24] = -0.00000000000000000e+00;
	w[25] = -0.00000000000000000e+00;
	w[26] =  0.00000000000000000e+00;
	w[27] =  0.00000000000000000e+00;
	w[28] =  0.00000000000000000e+00;
	w[29] =  0.00000000000000000e+00;
	w[30] =  2.11700000000000010e-02;
	w[31] =  2.74399999999999990e-02;
	w[32] =  1.20079226000000000e-01;
	w[33] =  0.00000000000000000e+00;
	w[34] = -4.24471803053972590e-03;
	w[35] =  0.00000000000000000e+00;
	w[36] =  0.00000000000000000e+00;
	w[37] =  0.00000000000000000e+00;
	w[38] =  0.00000000000000000e+00;
	w[39] =  0.00000000000000000e+00;
	w[40] = -2.47265127992605330e+01;
	w[41] =  0.00000000000000000e+00;
	w[42] =  0.00000000000000000e+00;
	w[43] =  0.00000000000000000e+00;
	w[44] = -0.00000000000000000e+00;
	w[45] =  0.00000000000000000e+00;
	w[46] =  0.00000000000000000e+00;
	w[47] =  0.00000000000000000e+00;
	w[48] =  0.00000000000000000e+00;
	w[49] = -0.00000000000000000e+00;
	w[50] = -0.00000000000000000e+00;
	w[51] =  1.00000000000000000e+00;
	w[52] =  1.00000000000000000e+00;
	w[53] =  1.00000000000000000e+00;
	w[54] =  1.00000000000000000e+00;
	w[55] =  1.00000000000000000e+00;
	w[56] =  1.00000000000000000e+00;
	w[57] =  1.00000000000000000e+00;
	w[58] =  1.00000000000000000e+00;
	w[59] =  0.00000000000000000e+00;
	w[60] =  0.00000000000000000e+00;
	w[61] =  0.00000000000000000e+00;
	w[62] =  0.00000000000000000e+00;
	w[63] =  0.00000000000000000e+00;
	w[64] =  0.00000000000000000e+00;
	w[65] =  0.00000000000000000e+00;
	w[66] =  0.00000000000000000e+00;
	w[67] =  1.00000000000000000e+00;
	w[68] =  0.00000000000000000e+00;
	w[69] =  1.00000000000000000e+00;
	w[70] =  0.00000000000000000e+00;
	w[71] =  0.00000000000000000e+00;
	w[72] =  1.00000000000000000e-04;
	w[73] =  0.00000000000000000e+00;
	w[74] =  1.00000000000000000e+00;
	w[75] =  2.00000000000000000e+00;
	w[76] =  3.00000000000000000e+00;
	w[77] =  4.00000000000000000e+00;
	w[78] =  5.00000000000000000e+00;
	w[79] =  6.00000000000000000e+00;
	w[80] =  7.00000000000000000e+00;
	w[81] =  5.15000000000000050e-04;
	w[82] =  8.84000000000000060e-02;
	w[83] =  2.11700000000000010e-02;
	w[84] =  2.11700000000000010e-02;
	w[85] =  2.11700000000000010e-02;
	w[86] =  2.11700000000000010e-02;
	w[87] =  2.11700000000000010e-02;
	w[88] =  2.11700000000000010e-02;
	w[89] =  2.11700000000000010e-02;
	w[90] =  2.11700000000000010e-02;
	w[91] =  9.71999999999999950e-02;
	w[92] =  2.74399999999999990e-02;
	w[93] =  2.77700000000000000e-02;
	w[94] =  2.74200000000000000e-02;
	w[95] =  2.64600000000000010e-02;
	w[96] =  2.42600000000000000e-02;
	w[97] =  2.32900000000000020e-02;
	w[98] =  2.24099999999999990e-02;
	w[99] =  2.24099999999999990e-02;
	w[100] =  3.00000000000000000e+00;
	w[101] =  0.00000000000000000e+00;
	w[102] =  1.00000000000000000e+00;
	w[103] =  1.20000000000000000e+01;
	w[104] =  1.90000000000000000e+01;
	w[105] =  2.60000000000000000e+01;
	w[106] =  3.50000000000000000e+01;
	w[107] =  4.10000000000000000e+01;
	w[108] =  5.60000000000000000e+01;
	w[109] =  0.00000000000000000e+00;
	w[110] =  5.00000000000000000e+02;
	w[111] =  3.00000000000000000e+03;
	w[112] =  4.00000000000000000e+03;
	w[113] =  5.00000000000000000e+03;
	w[114] =  7.00000000000000000e+03;
	w[115] =  1.20000000000000000e+04;
	w[116] =  1.80000000000000000e+04;
	w[117] =  1.00000000000000000e+00;
	w[118] =  1.00000000000000000e+01;
	w[119] =  9.15000000000000040e+00;
	w[120] =  2.20000000000000000e+01;
	w[121] =  2.20000000000000000e+01;
	w[122] =  2.00000000000000010e-04;
	w[123] =  4.00000000000000010e-03;
	w[124] =  2.06000000000000020e-03;
	w[125] =  1.15099999999999990e-01;
	w[126] =  1.00000000000000000e+00;
	w[127] =  1.00000000000000000e+00;
	w[128] =  1.00000000000000000e+00;
	w[129] =  0.00000000000000000e+00;
	w[130] =  0.00000000000000000e+00;
	w[131] =  0.00000000000000000e+00;
	w[132] = -9.80000000000000070e+00;
	w[133] = -1.00000000000000000e+00;
	w[134] =  1.00000000000000000e+00;
	iw[2*NZC+0] = 0; iw[2*NZC+NEVT+0] = 69;
	iw[2*NZC+1] = 1; iw[2*NZC+NEVT+1] = 0;
	eev(w[0],&w[1],&w[1],&w[2*NEQ+NPAR+NDFA+1]);
#ifdef EVTHYST
	for(j=0;j<NEVT;j++) {
		if(iw[2*NZC+NEVT+j]>0) {
			if(w[iw[2*NZC+NEVT+j]]==0.0) { iw[2*j]=0; iw[2*j+1]=0; }
			else                         { iw[2*j]=1; iw[2*j+1]=1; }
		}
		else {
			iw[2*j]=(w[2*NEQ+NPAR+NDFA+1+j]>EVTHYST ? 1 : 0);
			iw[2*j+1]=(w[2*NEQ+NPAR+NDFA+1+j]>-EVTHYST ? 1 : 0);
		}
	}
#else
	for(j=0;j<NEVT;j++)
		if(iw[2*NZC+NEVT+j]>0) {
			if(w[iw[2*NZC+NEVT+j]]==0.0) iw[j]=0; else iw[j]=1;
		}
		else
			iw[j]=(w[2*NEQ+NPAR+NDFA+1+j]>0.0 ? 1 : 0);
#endif

	for(j=0;j<NDIFF;j++) w[NEQ+NPAR+j+1]=0.0;

	for(j=0;j<NINP;j++) w[j+NDIFF+NIX1-NINP+1]=i[j][0];
	for(j=0;j<NDIFF;j++) w[j+1]=x[j];
	for(j=0;j<NPAR;j++) w[j+NEQ+1]=p[j][0];
	if (fptr) {
		fwrite(nData,sizeof(real_T),2,fptr);
		fwrite(&w[NEQ+1],sizeof(real_T),NPAR,fptr);
	}

	w[NEQ+NPAR+1]=0.0;
	if(NIX1>0) {
		fp(NEQ,w[0],&w[1],&w[NEQ+NPAR+1]);
		if( IS_UNDEF(w[NEQ+NPAR+1]) ) {
			ssSetErrorStatus(S,"index-1 and derivative evaluation failure");
			if (fptr) {
				writeErrorToFile(fptr,ssGetErrorStatus(S));
				fptr = NULL;
			}
			return;
		}
	}
	if(RunEvents(S,w,iw,1,67,EVTITER)) return;
#if INITCONITER>0
	for(k=0;k<20;k++) {
#endif
#if INITCONITER>0
		j=ProjectInitial(w[0],&w[1],INITCONTOL,INITCONITER,icmask,INITTOL,INITITER,INITWEIGHT);
		if(j>0 && j!=3) {
			ssSetErrorStatus(S,"constraint projection failure");
			if (fptr) {
			writeErrorToFile(fptr,ssGetErrorStatus(S));
			fptr = NULL;		}
		return;
		}
		if(NIX1>0) {
			fp(NEQ,w[0],&w[1],&w[NEQ+NPAR+1]);
			if( IS_UNDEF(w[NEQ+NPAR+1]) ) {
				ssSetErrorStatus(S,"index-1 and derivative evaluation failure");
				if (fptr) {
				writeErrorToFile(fptr,ssGetErrorStatus(S));
				fptr = NULL;			}
			return;
			}
		}
#endif
		j=cpr(w[0],&w[1]);
		if(j>0 && NIX1>0) {
			fp(NEQ,w[0],&w[1],&w[NEQ+NPAR+1]);
			if( IS_UNDEF(w[NEQ+NPAR+1]) ) {
				ssSetErrorStatus(S,"index-1 and derivative evaluation failure");
				if (fptr) {
				writeErrorToFile(fptr,ssGetErrorStatus(S));
				fptr = NULL;			}
			return;
			}
		}
#if INITCONITER>0
		if(j<1) break;
	}
#endif
	eev(w[0],&w[1],&w[1],&w[2*NEQ+NPAR+NDFA+1]);
	if(RunEvents(S,w,iw,0,67,EVTITER)) return;
	for(j=0;j<NDIFF;j++) x[j]=w[j+1];
}

#define MDL_INITIALIZE_CONDITIONS
static void mdlInitializeConditions(SimStruct *S)
{
	InputRealPtrsType ic = ssGetInputPortRealSignalPtrs(S,0);
	real_T *x = ssGetDiscStates(S);
	int_T *iw = ssGetIWork(S);
	int_T j;

	iw[INIDREF]=0;
	for(j=0;j<NDIFF;j++) x[j]=ic[j][0];
}

static real_T *GetUpdatedWork(SimStruct *S, int_T getnofeed)
{
	int_T j,flag;

	real_T *w = ssGetRWork(S);
	real_T t = ssGetT(S);
	real_T *x = ssGetDiscStates(S);
	InputRealPtrsType i;
	InputRealPtrsType p = ssGetInputPortRealSignalPtrs(S,1);

	flag=0;
	if( fabs(w[0]-t)>1e-6*TIMESTEP ) flag=1;
	w[0]=t;
	for(j=0;j<NDIFF;j++) if( w[j+1]!=x[j] ) { flag=1; w[j+1]=x[j]; }
	i = ssGetInputPortRealSignalPtrs(S,2);
	for(j=0;j<NINP;j++) if( w[j+NDIFF+NIX1-NINP+1]!=i[j][0] ) { flag=1; w[j+NDIFF+NIX1-NINP+1]=i[j][0]; }
	for(j=0;j<NPAR;j++) if( w[j+NEQ+1]!=p[j][0] ) { flag=1; w[j+NEQ+1]=p[j][0]; }

	if(flag) {
		fp(NEQ,w[0],&w[1],&w[NEQ+NPAR+1]);
		if( IS_UNDEF(w[NEQ+NPAR+1]) ) {
			if( NDIFF>0 && ssIsVariableStepSolver(S) )
				for(j=1;j<NDIFF;j++) w[NEQ+NPAR+1+j] = w[NEQ+NPAR+1];
			else
			{
				ssSetErrorStatus(S,"index-1 and derivative evaluation failure");
				if (fptr) {
					writeErrorToFile(fptr,ssGetErrorStatus(S));
					fptr = NULL;				}
			}
		}
	}

	return(w);
}

static void RK4Step(real_T *w)
{
	int_T i;
	real_T y[NEQ+1],yp1[NDFA],yp2[NDFA],yp3[NDFA];

	for(i=0;i<NEQ+1;i++) y[i]=w[i];
	for(i=0;i<NDIFF;i++) yp1[i]=w[1+NEQ+NPAR+i];
	w[0]+=0.5*TIMESTEP;
	for(i=0;i<NDIFF;i++) w[i+1]+=0.5*TIMESTEP*w[1+NEQ+NPAR+i];
	fp(NEQ,w[0],&w[1],&w[NEQ+NPAR+1]);
	for(i=0;i<NDIFF;i++) yp2[i]=w[1+NEQ+NPAR+i];
	for(i=0;i<NDIFF;i++) w[i+1]=y[i+1]+0.5*TIMESTEP*w[1+NEQ+NPAR+i];
	fp(NEQ,w[0],&w[1],&w[NEQ+NPAR+1]);
	for(i=0;i<NDIFF;i++) yp3[i]=w[1+NEQ+NPAR+i];
	w[0]=y[0]+TIMESTEP;
	for(i=0;i<NDIFF;i++) w[i+1]=y[i+1]+TIMESTEP*w[1+NEQ+NPAR+i];
	fp(NEQ,w[0],&w[1],&w[NEQ+NPAR+1]);
	for(i=0;i<NDIFF;i++) w[i+1]=y[i+1]+TIMESTEP/6.0*(yp1[i]+2.0*(yp2[i]+yp3[i])+w[1+NEQ+NPAR+i]);
}


#define MDL_UPDATE
static void mdlUpdate(SimStruct *S, int_T tid)
{
	real_T *w, *x = ssGetDiscStates(S);
	int_T i;

	UNUSED_ARG(tid);

	w=GetUpdatedWork(S,1);
	RK4Step(w);

#if CONITER>0
	i=Projection(w[0],&w[1],CONTOL,CONITER,NULL);
#endif
	fp(NEQ,w[0],&w[1],&w[NEQ+NPAR+1]);
	if( IS_UNDEF(w[NEQ+NPAR+1]) )
		{
			ssSetErrorStatus(S,"index-1 and derivative evaluation failure");
			if (fptr) {
				writeErrorToFile(fptr,ssGetErrorStatus(S));
				fptr = NULL;
			}
			return;
		}
	for(i=0;i<NDIFF;i++) x[i]=w[i+1];
}

static void mdlOutputs(SimStruct *S, int_T tid)
{
	real_T *w, *y = ssGetOutputPortRealSignal(S,0);
	int_T *iw = ssGetIWork(S);
	int_T i;
	real_T *x;

	UNUSED_ARG(tid);

	if(!iw[INIDREF]) {
		InitializeConditions(S);
		iw[INIDREF]=1;
	}
	if( ssIsVariableStepSolver(S) ) {
		ssSetErrorStatus(S,"code generated for fixed step, cannot be used with variable step");
		if (fptr) {
			writeErrorToFile(fptr,ssGetErrorStatus(S));
			fptr = NULL;
		}
		return;
	}
	w=GetUpdatedWork(S,0);
	if( ssIsMajorTimeStep(S) ) {
		if(RunEvents(S,w,iw,0,67,EVTITER)) return;
		x=ssGetDiscStates(S);
		for(i=0;i<NDIFF;i++) x[i]=w[i+1];
	}
	otp(w[0],&w[1],&w[NEQ+NPAR+1]);
	y[ 0]=w[30];
	y[ 1]=w[31];
	y[ 2]=w[41];
	y[ 3]=w[42];
	y[ 4]=w[43];
	y[ 5]=w[44];
	y[ 6]=w[45];
	y[ 7]=w[46];
	y[ 8]=w[ 2];
	y[ 9]=w[ 3];
	y[10]=w[37];
	y[11]=w[ 1];
	y[12]=w[47];
	y[13]=w[48];
	y[14]=w[38];
	y[15]=w[49];
	y[16]=w[21];
	y[17]=w[50];
	y[18]=w[39];
	y[19]=w[ 4];
	y[20]=w[51];
 	if ( fptr && ssIsMajorTimeStep(S) )
		if ( w[0]>=(lastsampletime+minsamplestep)*(1-1e-15) ) {
			fwrite(w,sizeof(real_T),NEQ+1,fptr);
			lastsampletime=w[0];
			if ( numpts++ == WARNNUMDATPTS )
				ssPrintf("Warning: At time t=%.16g, %d data points were written into file %s; consider increasing the minimum sample step, %.16g, to limit file size.\n",
						w[0],WARNNUMDATPTS,fstr,minsamplestep);
		}
}

static void mdlTerminate(SimStruct *S) {
	if (fptr) {
		fclose(fptr);
		fptr = NULL;
	}
}

#ifdef  MATLAB_MEX_FILE    /* Being compiled as a MEX-file? */
#include "simulink.c"      /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"       /* Code generation registration function */
#endif
