/**
 *    @file
 *    @brief    It implements the Zero Cross Detection Logic
 *
 *    @details  This module handles zero cross signal and generates events based on the rise, fall or no edge as
 *              "ZC_FALL_EDGE_EVENT", "ZC_RISE_EDGE_EVENT", "ZC_BLACKOUT_EVENT" & ZC_NO_EVENT, it provides the last event
 *              & current state of zero cross signal, it provides duty cycle & frequency of zero cross signal
 *
 *  $Header: ZeroCross.c 1.6 2015/07/24 11:46:15EDT Dasar Hanumanth (DASARHB) Exp  $
 *
 *  @copyright  Copyright 2011-$Date: 2015/07/24 11:46:15EDT $. Whirlpool Corporation. All rights reserved - CONFIDENTIAL
 */
//---------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------
//-------------------------------------- Include Files ----------------------------------------------------------------
/*
#include "SystemConfig.h"
#include "ZeroCross.h"
//#include "SRTimerReference.h"
#include "Micro.h"
//#include "Log.h"
#include "string.h"
#if (ZC_FAST_HANDLER_CALL == ENABLED)
//#include "SRMain.h"
#endif

//-------------------------------------- PRIVATE (Variables, Constants & Defines) -------------------------------------
#if (ZC_HANDLER_TIMING_US > 0)
#define ZC_FREQUENCE_DEBOUNCE                   4
#define ZC_DEBOUNCE_MASK                        7
#define ZC_60HZ_50HZ_BOUNDARIE                  (18000/ ZC_HANDLER_TIMING_US)
#define ZC_KEEP_OUT_WINDOW                      (6250/ ZC_HANDLER_TIMING_US)
#define ZC_FULL_CYCLE_COUNT_LIMIT               (10000/ ZC_HANDLER_TIMING_US)
#define ZC_COUNTER_BLACKOUT                     (60000/ ZC_HANDLER_TIMING_US)
#define ZC_BASE_PERIOD                         	(1000000/ZC_HANDLER_TIMING_US)
#else
#define ZC_60HZ_50HZ_BOUNDARIE                  (18000)
#define ZC_BASE_PERIOD                         	(1000000)
#ifndef 	ZC_DEBOUNCE_CYCLE
    #define ZC_DEBOUNCE_CYCLE                   4
#endif
#ifndef		ZC_MAX_CYCLE_TIMEOUT
	#define ZC_MAX_CYCLE_TIMEOUT		(ZC_DEBOUNCE_CYCLE * 4)
#endif
#endif

#ifndef ZC_ANGLE_EVENT
    #define ZC_ANGLE_EVENT(angle)
#endif

//! The name of this module for use by the Log module.
#define MODULE_NAME MODULE_ZEROCROSS

// -- Private Type Declarations --

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_ZEROCROSS_LOG_MESSAGE_ID_ENUM
{
    INVALID_ZEROCROSS_RANGE = 1,
} MODULE_ZEROCROSS_LOG_MESSAGE_ID_TYPE;

PACKED typedef struct
{
	uint16 			Gpio_Id;
	GPIO_PORT_TYPE	Port;
	uint8			Pin;
} ZEROCROSS_GPIO_CONFIG_TYPE;

PACKED typedef struct
{
	uint16 			Atod_Id;
    ATOD_CHANNEL_DEF Channel;
    ATOD_CHANNEL_RESOLUTION_DEF Resolution;
} ZEROCROSS_ATOD_CONFIG_TYPE;

#define			GPIO_ID_INDEX(x)				((x) & 0xFF)

static uint16 Zc_Last_Period;
static uint16 Zc_Angle;
static ZEROCROSS_EVENT_TYPE Zc_Last_Event;
#if (ZC_HANDLER_TIMING_US > 0)
static GPIO_PORT_TYPE ZC_Port;
static uint8 ZC_Pin;
static uint16 Zc_Full_Cycle_Count;
static uint8 Zc_Keepout_Counter;
static uint8 Zc_Sample;
static uint8 Zc_Previous_State;
static uint8 Zc_Semi_Cycle_Counter;
static uint8 Zc_Semi_Cycle;
static uint8 Zc_Semi_Pos_Cycle;
static uint8 Zc_Semi_Neg_Cycle;
#else
static uint8 Zc_Debounce_Cycle;
static uint8 Zc_Timeout;
static BOOL_TYPE Zc_Event_Trigger;
static sint16 Zc_Time_Compensation;
static uint16 Zc_Angle_Duration;
static uint16 Zc_Signal_Elapsed_us;
#endif
uint16 ZC_Angle_Elapsed_us;
static sint16 Zc_Last_Latency;
static uint16 Zc_Last_Timing;
static uint8 Stop_Timer;
static TIMER_PARAMETER_TYPE ZC_Timer_Parameter;

#if (ZC_HANDLER_TIMING_US > 0)

#if (ZC_NUM_GPIO_REQUESTS > 0)
static ZEROCROSS_GPIO_CONFIG_TYPE	ZeroCross_Gpio_Pin_Configuration[ZC_NUM_GPIO_REQUESTS];
static ZEROCROSS_GPIO_REQUEST_TYPE	ZeroCross_Gpio_Requests[ZC_NUM_GPIO_REQUESTS];
static ZEROCROSS_GPIO_REQUEST_TYPE	ZeroCross_Gpio_Processing[ZC_NUM_GPIO_REQUESTS];
#endif

#if (ZC_NUM_ATOD_REQUESTS > 0)
#define	ZEROCROSS_ATOD_BUFFER_SIZE		((ZC_ATOD_BUFFER_US+ZC_HANDLER_TIMING_US-1)/ZC_HANDLER_TIMING_US)

static ZEROCROSS_ATOD_CONFIG_TYPE	ZeroCross_Atod_Pin_Configuration[ZC_NUM_ATOD_REQUESTS];
static uint16 ZeroCross_Atod_Buffer[ZC_NUM_ATOD_REQUESTS][ZEROCROSS_ATOD_BUFFER_SIZE];
static uint16 ZeroCross_Atod_Read_Index[ZC_NUM_ATOD_REQUESTS];
static uint16 ZeroCross_Atod_Write_Index[ZC_NUM_ATOD_REQUESTS];
static BOOL_TYPE ZeroCross_Atod_Overrun[ZC_NUM_ATOD_REQUESTS];
#endif

static void GpioRequestInitialize(void);
static void AtodRequestInitialize(void);
static void ServiceRequest(ZEROCROSS_EVENT_TYPE zc_event);
#endif
*/
//=====================================================================================================================
//-------------------------------------- Public Functions -------------------------------------------------------------
//=====================================================================================================================
//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief     It initializes ZeroCross module and variables associated with it
 * @details - It Configures the external interrupt connected to the zero cross hardware and initializes the timer module for generating the angle event
 * @param ext_chnl
 * @param ext_port
 * @param ext_pin
 * @param ext_remap
 * @param tim
 * @param tim_chnl
 * @return
 */
/*
PASS_FAIL_TYPE ZeroCross__Config(EXTINT_CHNL_TYPE ext_chnl, GPIO_PORT_TYPE ext_port, uint8 ext_pin, uint8 ext_remap, TIMER_TYPE tim, TIMER_CHANNEL_TYPE tim_chnl)
{
    PASS_FAIL_TYPE status = FAIL;

    ZC_Timer_Parameter.Timer      = tim;
    ZC_Timer_Parameter.Channel    = tim_chnl;
    ZC_Timer_Parameter.Mode       = TIMER_MODE_OUTPUT_COMPARE;
    ZC_Timer_Parameter.Port       = PORT_NULL;
    ZC_Timer_Parameter.Pin        = 0;
    ZC_Timer_Parameter.Pin_ReMap  = 0;
    ZC_Timer_Parameter.Polarity   = TIMER_POLARITY_ACTIVE_HIGH;

    Zc_Last_Period          = ZC_60HZ_50HZ_BOUNDARIE;
    Zc_Last_Event           = ZEROCROSS_BLACKOUT_EVENT;
    Stop_Timer              = 0xFF;
    Zc_Last_Timing          = 0;
    Zc_Last_Latency         = 0;
    ZC_Angle_Elapsed_us   = 0;
    #if (ZC_HANDLER_TIMING_US > 0)
    Zc_Full_Cycle_Count     = ZC_60HZ_50HZ_BOUNDARIE;
    Zc_Keepout_Counter      = 0;
    Zc_Sample               = 1;
    Zc_Previous_State       = 0;
    Zc_Semi_Cycle_Counter   = 0;
    Zc_Semi_Cycle           = 0;
    ZC_Port					= ext_port;
    ZC_Pin					= ext_pin;
	GpioRequestInitialize();
	AtodRequestInitialize();
    #else
	Zc_Signal_Elapsed_us    = 0;
    Zc_Angle_Duration       = 0;
    Zc_Time_Compensation    = 0;
    Zc_Debounce_Cycle       = ZC_DEBOUNCE_CYCLE;
    Zc_Timeout              = 0;
    Zc_Event_Trigger		= FALSE;
    #endif

    if (Timer__Config(&ZC_Timer_Parameter) == PASS)
    {
    	Stop_Timer      = Timer__StartCount(&ZC_Timer_Parameter);
	    #if (ZC_HANDLER_TIMING_US > 0)
    	    status = Timer__OutputCompareStart(&ZC_Timer_Parameter, TIMER_ONCOMPARE_INTERRUPT, ZC_HANDLER_TIMING_US);
    	#else
    	    status = ExtInterrupt__Config(ext_chnl, ext_port, ext_pin, ext_remap, ZC_TRIGGER_EDGE);
  	    #endif
    }

    return status;
}
*/
//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief - This API handles the ZeroCross signal event
 * @details - On ZeroCross event ExtInterrupt module generates the interrupt
 *//*
void ZeroCross__SignalEvent(void)
{
#if (ZC_HANDLER_TIMING_US == 0)
    MICRO_DECLARE_INTERRUPT_CONTEXT_LOCAL();
    uint32 elapsed_count;

    MICRO_SAVE_INTERRUPT_CONTEXT_LOCAL();

    elapsed_count = Timer__ReStartCount(Stop_Timer);

    if ((elapsed_count >= (ZC_BASE_PERIOD / ZC_ALLOWED_MAX_FREQUENCY)) &&
    		(elapsed_count <= (ZC_BASE_PERIOD / ZC_ALLOWED_MIN_FREQUENCY)))
    {
        Zc_Timeout = ZC_MAX_CYCLE_TIMEOUT;
        Zc_Last_Period = (Zc_Last_Period + elapsed_count) / 2;

    	//skip the de-bounce cycle
        if (Zc_Debounce_Cycle == 0)
        {
            if (Zc_Last_Event == ZEROCROSS_ANGLE_270_EVENT)
            {
                Zc_Time_Compensation = Zc_Last_Timing + Zc_Angle_Duration + Zc_Last_Latency - (elapsed_count + ZC_ADVANCE_PULSE_DELAY);
                if (Zc_Time_Compensation > 0)
                {
                    Zc_Angle_Duration = Zc_Time_Compensation;
                }
                else
                {
                    Zc_Angle_Duration = 0;
                }
            }
            else
            {
                Timer__OutputCompareStart(&ZC_Timer_Parameter, TIMER_ONCOMPARE_INTERRUPT, (Zc_Last_Period/4) - ZC_ADVANCE_PULSE_DELAY);
                Zc_Angle_Duration = (Zc_Last_Period/4) - ZC_ADVANCE_PULSE_DELAY;
                Zc_Time_Compensation = 0;
                Zc_Last_Event = ZEROCROSS_ANGLE_0_EVENT;
                Zc_Angle = ZEROCROSS_MINIMUM_ANGLE;
            }

            Zc_Last_Latency = 0;
            Zc_Last_Timing = 0;
            Zc_Event_Trigger = TRUE;
        }
        else
        {
            Zc_Debounce_Cycle--;
        }
    }
    else
    {
    	LOG_ADD_EXCEPTION(INVALID_ZEROCROSS_RANGE, (uint16) elapsed_count);
    }
    Zc_Signal_Elapsed_us = Timer__GetCount(Stop_Timer);
    MICRO_RESTORE_INTERRUPT_CONTEXT_LOCAL();
	#endif
}
*/
//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief - This API handles the ZeroCross Asynchronous handler
 * @details - This function is called in Hbl__AsyncHandler to check timeout and restart Zc_Debounce_Cycle when ZC signal is lost
 *//*
void ZeroCross__AsyncHandler(void)
{
#if (ZC_HANDLER_TIMING_US == 0)
	MICRO_DECLARE_INTERRUPT_CONTEXT_LOCAL();

	if (Zc_Debounce_Cycle == 0)
	{
		MICRO_SAVE_INTERRUPT_CONTEXT_LOCAL();
		if (Zc_Timeout > 0)
		{
			Zc_Timeout--;
		}
		else
		{
            Zc_Last_Event = ZEROCROSS_BLACKOUT_EVENT;
			Zc_Debounce_Cycle = ZC_DEBOUNCE_CYCLE;
            Zc_Angle = 0;
		}
		MICRO_RESTORE_INTERRUPT_CONTEXT_LOCAL();
	}
#endif
}
*/
//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief - This API handles the ZeroCross Angle event
 * @details - Timer Output compare calls this function on compare match
 * @return
 *//*

ZEROCROSS_EVENT_TYPE ZeroCross__AngleEvent(void)
{
    ZEROCROSS_EVENT_TYPE event = ZEROCROSS_NO_EVENT;
    uint32 handler_timing;
	MICRO_DECLARE_INTERRUPT_CONTEXT_LOCAL();

    #if (ZC_HANDLER_TIMING_US > 0)
	    uint8 pin_value;
    #endif

    MICRO_SAVE_INTERRUPT_CONTEXT_LOCAL();

	#if (ZC_HANDLER_TIMING_US == 0)

    handler_timing = Timer__GetCount(Stop_Timer);

    if (Zc_Last_Event != ZEROCROSS_BLACKOUT_EVENT)
    {
        Zc_Last_Timing += Zc_Angle_Duration + Zc_Last_Latency;
        Zc_Last_Latency = handler_timing - Zc_Last_Timing;

        switch(Zc_Last_Event)
        {
        case ZEROCROSS_ANGLE_90_EVENT:
            event = ZEROCROSS_ANGLE_180_EVENT;
            Zc_Angle = 180;
            Zc_Event_Trigger = FALSE;
            break;
        case ZEROCROSS_ANGLE_180_EVENT:
            event = ZEROCROSS_ANGLE_270_EVENT;
            Zc_Angle = 270;
            break;
        case ZEROCROSS_ANGLE_270_EVENT:
            event = ZEROCROSS_ANGLE_0_EVENT;
            Zc_Angle = 0;
            break;
        case ZEROCROSS_ANGLE_0_EVENT:
        default:
            event = ZEROCROSS_ANGLE_90_EVENT;
            Zc_Angle = 90;
            break;
        }

        if ((Zc_Last_Event != ZEROCROSS_ANGLE_0_EVENT) ||
            (Zc_Event_Trigger == TRUE))
        {
            Zc_Angle_Duration = (Zc_Last_Period/4) - Zc_Time_Compensation  - Zc_Last_Latency;
            Timer__OutputCompareStart(&ZC_Timer_Parameter, TIMER_ONCOMPARE_INTERRUPT, Zc_Angle_Duration);
            Zc_Time_Compensation = 0;
        }
    }

	if (event != ZEROCROSS_NO_EVENT)
	{
		Zc_Last_Event = event;
	}

	ZC_Angle_Elapsed_us = Timer__GetCount(Stop_Timer) - handler_timing;

	#else
    	handler_timing = Timer__ReStartCount(Stop_Timer);
		Zc_Last_Latency = handler_timing + Zc_Last_Latency - ZC_HANDLER_TIMING_US;
		Timer__OutputCompareStart(&ZC_Timer_Parameter, TIMER_ONCOMPARE_INTERRUPT, ZC_HANDLER_TIMING_US - Zc_Last_Latency);

		pin_value = (uint8) Gpio__PinRead(ZC_Port,ZC_Pin);
		if (ZC_TRIGGER_EDGE == EXTINT_TRG_FALL)
		{
			pin_value ^= 0x01;
		}

		Zc_Sample <<= 1;
		Zc_Sample |= pin_value;
		Zc_Sample &= ZC_DEBOUNCE_MASK;                  //It is done to check for valid signal or a noise

		if (((Zc_Sample ^ Zc_Previous_State) == ZC_DEBOUNCE_MASK) &&
			 (Zc_Keepout_Counter == 0))
		{
			Zc_Previous_State = Zc_Sample;
			Zc_Keepout_Counter = ZC_KEEP_OUT_WINDOW;

			if (Zc_Previous_State != 0)
			{
				// ensure the rising edge even if the counter didn't reach the rising edge limit.
				if (Zc_Full_Cycle_Count < (Zc_Last_Period- ZC_ADVANCE_PULSE_DELAY - 3))
				{
					//It generates event when rise edge of 60Hz zero cross signal is detected
					event = ZEROCROSS_ANGLE_0_EVENT;
				}

				if (Zc_Full_Cycle_Count > ZC_FULL_CYCLE_COUNT_LIMIT)
				{
					Zc_Last_Period = (Zc_Last_Period + Zc_Full_Cycle_Count + 2) >> 1;
				}
				Zc_Full_Cycle_Count = 0;
			}
		}
		else
		{
			if (Zc_Keepout_Counter > 0)
			{
				Zc_Keepout_Counter--;
			}

			if (Zc_Full_Cycle_Count < 0xFFFF)
			{
				Zc_Full_Cycle_Count++;                  //It provides the value of full cycle count for the full cycle of zero cross signal
			}


			if (Zc_Full_Cycle_Count == ((Zc_Last_Period >> 1)- ZC_ADVANCE_PULSE_DELAY - 2))
			{
				//It generates event when fall edge of 50Hz zero cross signal is detected
				event = ZEROCROSS_ANGLE_180_EVENT;
			}

			if (Zc_Full_Cycle_Count == (Zc_Last_Period- ZC_ADVANCE_PULSE_DELAY - 3))
			{
				//It generates event when rise edge of 60Hz zero cross signal is detected
				event = ZEROCROSS_ANGLE_0_EVENT;
			}


			if (Zc_Full_Cycle_Count >= ZC_COUNTER_BLACKOUT)
			{
				//It generates black out event edge when no zero cross signal is detected till specified time has elapsed
				event = ZEROCROSS_BLACKOUT_EVENT;
			}
		}

		if (event == ZEROCROSS_ANGLE_0_EVENT)
		{
			Zc_Semi_Cycle = Zc_Semi_Cycle_Counter;
			Zc_Semi_Neg_Cycle = Zc_Semi_Cycle_Counter;
			Zc_Semi_Cycle_Counter = 0;
		}
		else if (event == ZEROCROSS_ANGLE_180_EVENT)
		{
			Zc_Semi_Cycle = Zc_Semi_Cycle_Counter;
			Zc_Semi_Pos_Cycle = Zc_Semi_Cycle_Counter;
			Zc_Semi_Cycle_Counter = 0;
		}
		else
		{
			Zc_Semi_Cycle_Counter++;                //It provides the value of semi cycle count for the semi cycle of zero cross signal

			if ((Zc_Last_Event == ZEROCROSS_ANGLE_0_EVENT) &&
				(Zc_Semi_Cycle_Counter > (Zc_Semi_Neg_Cycle / 2)))
			{
				event = ZEROCROSS_ANGLE_90_EVENT;
			}
			else if ((Zc_Last_Event == ZEROCROSS_ANGLE_180_EVENT) &&
					(Zc_Semi_Cycle_Counter > (Zc_Semi_Pos_Cycle / 2)))
			{
				event = ZEROCROSS_ANGLE_270_EVENT;
			}

		}

		if (event != ZEROCROSS_NO_EVENT)
		{
		    Zc_Last_Event = event;
		    Zc_Last_Timing = Zc_Semi_Cycle_Counter;
		}

		// It translates the duty to degree angle
		if (Zc_Semi_Cycle > 0)                          // added protection against division by 0
		{
			uint16 cur_zc_angle = ((uint16)Zc_Semi_Cycle_Counter * (ZEROCROSS_MAXIMUM_ANGLE/2));
			cur_zc_angle /= Zc_Semi_Cycle;

			if (cur_zc_angle > (ZEROCROSS_MAXIMUM_ANGLE/2))
			{
				cur_zc_angle = (ZEROCROSS_MAXIMUM_ANGLE/2);
			}

			if ((Zc_Last_Event == ZEROCROSS_ANGLE_180_EVENT) ||
				(Zc_Last_Event == ZEROCROSS_ANGLE_270_EVENT))
			{
				cur_zc_angle += (ZEROCROSS_MAXIMUM_ANGLE/2);
			}

			Zc_Angle = cur_zc_angle;
		}

		//Service GPIO and Analog Activity handling
		ServiceRequest(event);
		#if (ZC_FAST_HANDLER_CALL == ENABLED)
			SRMain__FastTimerISR();
		#endif
		ZC_Angle_Elapsed_us = Timer__GetCount(Stop_Timer);
	#endif


    MICRO_RESTORE_INTERRUPT_CONTEXT_LOCAL();

    ZC_ANGLE_EVENT(event);

    return (event);
}
*/
//---------------------------------------------------------------------------------------------------------------------
/**
 *    @brief    It provides the frequency of zero cross signal
 *
 *    @details  This method provides the frequency of zero cross signal
 *    @return   Frequency of zero cross signal being received
 *//*
uint8 ZeroCross__GetFrequency(void)
{
    uint8 freq;

    freq = 0;

    if (Zc_Last_Event != ZEROCROSS_BLACKOUT_EVENT)
    {
        freq = ZC_BASE_PERIOD / Zc_Last_Period;

        if ((freq < ZC_ALLOWED_MIN_FREQUENCY) ||
            (freq > ZC_ALLOWED_MAX_FREQUENCY))
        {
            freq = 0;
        }
    }

    return freq;
}
*/
//---------------------------------------------------------------------------------------------------------------------
/**
 *    @brief    It provides the cycle count of zero cross signal
 *
 *    @details  This method provides the cycle_count of zero cross signal
 *    @return   cycle_count of zero cross signal being received
 *//*
uint32 ZeroCross__GetCycleCount(void)
{
    uint32 cycle_count;

    cycle_count = 0;
    if (Zc_Last_Event != ZEROCROSS_BLACKOUT_EVENT)
    {
		#if (ZC_HANDLER_TIMING_US == 0)
	    	cycle_count = Zc_Last_Period;
		#else
	    	cycle_count = Zc_Last_Period * ZC_HANDLER_TIMING_US;
    	#endif
    }
    return cycle_count;
}

*/
//---------------------------------------------------------------------------------------------------------------------
/**
 *    @brief    It provides the current angle of zero cross signal
 *
 *    @details
 *    @return   Current angle of zero cross signal
 *//*
uint16 ZeroCross__GetAngle(void)
{
    return(Zc_Angle);
}
*/
//---------------------------------------------------------------------------------------------------------------------
/**
 *    @brief    It provides last ZeroCross event
 *
 *    @details
 *    @return   Last ZeroCross event
 *//*
ZEROCROSS_EVENT_TYPE ZeroCross__GetLastEvent(void)
{
    return(Zc_Last_Event);
}

uint16 ZeroCross__GetTimeFromLastEvent(void)
{
    uint32 handler_timing = 0;

    if (Zc_Last_Event != ZEROCROSS_BLACKOUT_EVENT)
    {
        MICRO_DECLARE_INTERRUPT_CONTEXT_LOCAL();
        uint32 last_timing;

        MICRO_SAVE_INTERRUPT_CONTEXT_LOCAL();
        handler_timing = Timer__GetCount(Stop_Timer);
        handler_timing += Zc_Last_Latency;
        #if (ZC_HANDLER_TIMING_US == 0)
            last_timing = Zc_Last_Timing;
        #else
            handler_timing += (Zc_Semi_Cycle_Counter * ZC_HANDLER_TIMING_US);
            last_timing = (Zc_Last_Timing * ZC_HANDLER_TIMING_US);
        #endif
        MICRO_RESTORE_INTERRUPT_CONTEXT_LOCAL();

        if (handler_timing > last_timing)
        {
            handler_timing -= last_timing;
        }
        else
        {
            handler_timing = 0;
        }
    }

    return((uint16) handler_timing);
}
*/
//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief       Get function to provide value of an AnalogLLI instance
 * @param input     pointer to HBL_LLI_TYPE structure instance
 * @param status
 * @return  pointer to value
 *//*
uint16 ZeroCross__RegisterGpioActivity(GPIO_PORT_TYPE port, uint8 pin)
{
    uint16 gpio_id = ZEROCROSS_ID_INVALID;

#if (ZC_HANDLER_TIMING_US > 0) && (ZC_NUM_GPIO_REQUESTS > 0)
    BOOL_TYPE already_registered = FALSE;

    //Handle the Duplicate requests
    for(uint8 index = 0; index < ZC_NUM_GPIO_REQUESTS; index++)
    {
    	ZEROCROSS_GPIO_CONFIG_TYPE *cfg_ptr = &ZeroCross_Gpio_Pin_Configuration[index];

    	if (cfg_ptr->Gpio_Id == ZEROCROSS_ID_INVALID)
    	{
    		uint8 high_id = SRTimerReference__GetTimer() & 0xFF;
    		gpio_id = index | (high_id << 8);
    		break;
    	}
    	else if ((port == cfg_ptr->Port) &&
    			(pin == cfg_ptr->Pin))
        {
    		already_registered = TRUE;
    		break;
        }
    }

    //
    if ((already_registered == FALSE) &&
    	(gpio_id != ZEROCROSS_ID_INVALID))
    {
    	uint8 index = GPIO_ID_INDEX(gpio_id);
    	ZEROCROSS_GPIO_CONFIG_TYPE *cfg_ptr = &ZeroCross_Gpio_Pin_Configuration[index];

    	cfg_ptr->Gpio_Id = gpio_id;
    	cfg_ptr->Port = port;
    	cfg_ptr->Pin = pin;
    }
#endif

    return(gpio_id);
}

PASS_FAIL_TYPE ZeroCross__ReleaseGpioActivity(uint16 gpio_id)
{
	PASS_FAIL_TYPE result = FAIL;
#if (ZC_HANDLER_TIMING_US > 0) && (ZC_NUM_GPIO_REQUESTS > 0)
	uint8 index = GPIO_ID_INDEX(gpio_id);
	if ((index < ZC_NUM_GPIO_REQUESTS) &&
		(ZeroCross_Gpio_Pin_Configuration[index].Gpio_Id == gpio_id))
	{
		ZeroCross_Gpio_Pin_Configuration[index].Gpio_Id = ZEROCROSS_ID_INVALID;
		result = PASS;
	}
#endif
	return(result);
}
*/
//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief       Get function to provide value of an AnalogLLI instance
 * @param input     pointer to HBL_LLI_TYPE structure instance
 * @param status
 * @return  pointer to value
 *//*
BOOL_TYPE ZeroCross__RequestGpioActivity(ZEROCROSS_GPIO_REQUEST_TYPE *gpio_activity)
{
    BOOL_TYPE request_accepted = FALSE;

#if (ZC_HANDLER_TIMING_US > 0) && (ZC_NUM_GPIO_REQUESTS > 0)
	uint8 index = GPIO_ID_INDEX(gpio_activity->Gpio_Id);
	if ((index < ZC_NUM_GPIO_REQUESTS) &&
		(ZeroCross_Gpio_Pin_Configuration[index].Gpio_Id == gpio_activity->Gpio_Id))
	{
    	ZEROCROSS_GPIO_REQUEST_TYPE *req_ptr = &ZeroCross_Gpio_Requests[index];
    	memcpy(req_ptr, gpio_activity, sizeof(ZEROCROSS_GPIO_REQUEST_TYPE));
        request_accepted = TRUE;
	}
#endif

    return(request_accepted);
}
*/
//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief       Get function to provide value of an AnalogLLI instance
 * @param input     pointer to HBL_LLI_TYPE structure instance
 * @param status
 * @return  pointer to value
 *//*
uint16 ZeroCross__RegisterAtodActivity(ATOD_CHANNEL_DEF channel, ATOD_CHANNEL_RESOLUTION_DEF resolution)
{
    uint16 atod_id = ZEROCROSS_ID_INVALID;

#if (ZC_HANDLER_TIMING_US > 0) && (ZC_NUM_ATOD_REQUESTS > 0)
    BOOL_TYPE already_registered = FALSE;

    //Handle the Duplicate requests
    for(uint8 index = 0; index < ZC_NUM_ATOD_REQUESTS; index++)
    {
    	ZEROCROSS_ATOD_CONFIG_TYPE *cfg_ptr = &ZeroCross_Atod_Pin_Configuration[index];

    	if (cfg_ptr->Atod_Id == ZEROCROSS_ID_INVALID)
    	{
    		uint8 high_id = SRTimerReference__GetTimer() & 0xFF;
    		atod_id = index | (high_id << 8);
    		break;
    	}
    	else if (channel == cfg_ptr->Channel)
        {
    		already_registered = TRUE;
    		break;
        }
    }

    //
    if ((already_registered == FALSE) &&
    	(atod_id != ZEROCROSS_ID_INVALID))
    {
    	uint8 index = GPIO_ID_INDEX(atod_id);
    	ZEROCROSS_ATOD_CONFIG_TYPE *cfg_ptr = &ZeroCross_Atod_Pin_Configuration[index];

    	cfg_ptr->Atod_Id = atod_id;
    	cfg_ptr->Channel = channel;
    	cfg_ptr->Resolution = resolution;

		ZeroCross_Atod_Read_Index[index] = 0;
		ZeroCross_Atod_Write_Index[index] = 0;
		ZeroCross_Atod_Overrun[index] = FALSE;
    }
#endif

    return(atod_id);
}

PASS_FAIL_TYPE ZeroCross__ReleaseAtodActivity(uint16 atod_id)
{
	PASS_FAIL_TYPE result = FAIL;
#if (ZC_HANDLER_TIMING_US > 0) && (ZC_NUM_ATOD_REQUESTS > 0)
	uint8 index = GPIO_ID_INDEX(atod_id);
	if ((index < ZC_NUM_ATOD_REQUESTS) &&
		(ZeroCross_Atod_Pin_Configuration[index].Atod_Id == atod_id))
	{
		ZeroCross_Atod_Pin_Configuration[index].Atod_Id = ZEROCROSS_ID_INVALID;
		result = PASS;
	}
#endif
	return(result);
}

BOOL_TYPE ZeroCross__IsAtodReadOverrun(uint16 atod_id)
{
	BOOL_TYPE is_overrun = FALSE;
#if (ZC_HANDLER_TIMING_US > 0) && (ZC_NUM_ATOD_REQUESTS > 0)
	uint8 index = GPIO_ID_INDEX(atod_id);
	if ((index < ZC_NUM_ATOD_REQUESTS) &&
		(ZeroCross_Atod_Pin_Configuration[index].Atod_Id == atod_id))
	{
		is_overrun = ZeroCross_Atod_Overrun[index];
	}
#endif
	return(is_overrun);
}

uint16 ZeroCross__CopyAtodSamples(uint16 atod_id, uint16 *buffer, uint16 max_items)
{
	uint16 num_items = 0;

#if (ZC_HANDLER_TIMING_US > 0) && (ZC_NUM_ATOD_REQUESTS > 0)
	uint8 index = GPIO_ID_INDEX(atod_id);
	if ((index < ZC_NUM_ATOD_REQUESTS) &&
		(ZeroCross_Atod_Pin_Configuration[index].Atod_Id == atod_id))
	{
		uint16 buffer_index;
    	uint16 current_read_sample_index = ZeroCross_Atod_Read_Index[index];
		sint16 available_items = ZeroCross_Atod_Write_Index[index] - current_read_sample_index;
		if (available_items < 0)
		{
			available_items += ZEROCROSS_ATOD_BUFFER_SIZE;
		}

		num_items = max_items;

		if (num_items > available_items)
		{
			num_items = available_items;
		}

		for(buffer_index = 0; buffer_index < num_items; buffer_index++)
		{
			buffer[buffer_index] = ZeroCross_Atod_Buffer[index][current_read_sample_index];
			current_read_sample_index++;
			if (current_read_sample_index >= ZEROCROSS_ATOD_BUFFER_SIZE)
			{
				current_read_sample_index = 0;
			}
		}
		ZeroCross_Atod_Overrun[index] = FALSE;
		ZeroCross_Atod_Read_Index[index] = current_read_sample_index;
	}
#endif

	return(num_items);
}


//=====================================================================================================================
//-------------------------------------- Private Functions ------------------------------------------------------------
//=====================================================================================================================
#if (ZC_HANDLER_TIMING_US > 0)
*/
//---------------------------------------------------------------------------------------------------------------------
/**
 * @brief   Service the GPIO requestd
 *
 * @param zc_event
 * @param zc_state
 * @param zc_degree
 *//*
static void ServiceRequest(ZEROCROSS_EVENT_TYPE zc_event)
{
    //Zero Cross Event happens
    if ((zc_event == ZEROCROSS_ANGLE_0_EVENT) ||
        (zc_event == ZEROCROSS_ANGLE_180_EVENT))
    {
        #if (ZC_NUM_GPIO_REQUESTS > 0)
    	for (uint8 index = 0; index < ZC_NUM_GPIO_REQUESTS; index++)
    	{
    		ZEROCROSS_GPIO_REQUEST_TYPE *req_ptr = &ZeroCross_Gpio_Requests[index];
	    	ZEROCROSS_GPIO_REQUEST_TYPE *processing_ptr = &ZeroCross_Gpio_Processing[index];

    		if (req_ptr->Gpio_Id == ZEROCROSS_ID_INVALID)
    		{
    			processing_ptr->Gpio_Id = ZEROCROSS_ID_INVALID;
    		}
    		else
    		{
                //copy the requests from request to process buffer
                memcpy((void *)processing_ptr, (void *)req_ptr, sizeof(ZEROCROSS_GPIO_REQUEST_TYPE));
        		req_ptr->Gpio_Id = ZEROCROSS_ID_INVALID;
        		req_ptr->Active_Degree = 0;
        		req_ptr->Deactive_Degree = 0;
        		req_ptr->Active_value = FALSE;
    		}
    	}
        #endif
    }

#if (ZC_NUM_GPIO_REQUESTS > 0)
    //Process the Gpio requests
    if (Zc_Last_Event != ZEROCROSS_BLACKOUT_EVENT)
    {
        uint8 half_wave_angle = Zc_Angle;

    	if (half_wave_angle >= ZEROCROSS_HALF_WAVE_ANGLE)
    	{
    	    half_wave_angle -= ZEROCROSS_HALF_WAVE_ANGLE;
    	}

    	for (uint8 index = 0; index < ZC_NUM_GPIO_REQUESTS; index++)
    	{
        	ZEROCROSS_GPIO_CONFIG_TYPE *cfg_ptr = &ZeroCross_Gpio_Pin_Configuration[index];
	    	ZEROCROSS_GPIO_REQUEST_TYPE *processing_ptr = &ZeroCross_Gpio_Processing[index];

    		if ((processing_ptr->Gpio_Id == cfg_ptr->Gpio_Id) &&
    		    (processing_ptr->Gpio_Id != ZEROCROSS_ID_INVALID))
    		{
    		    BOOL_TYPE gpio_value = processing_ptr->Active_value;

    		    if ((half_wave_angle < processing_ptr->Active_Degree) ||
    		    (half_wave_angle >= processing_ptr->Deactive_Degree))
                {
    		        gpio_value = (BOOL_TYPE) ((~gpio_value) & 0x01);
                }

                Gpio__PinWrite(cfg_ptr->Port, cfg_ptr->Pin, gpio_value);
            }
    	}
    }
#endif

    #if (ZC_NUM_ATOD_REQUESTS > 0)
        for(uint8 index = 0; index < ZC_NUM_ATOD_REQUESTS; index++)
        {
        	ZEROCROSS_ATOD_CONFIG_TYPE *cfg_ptr = &ZeroCross_Atod_Pin_Configuration[index];
            if (cfg_ptr->Atod_Id != ZEROCROSS_ID_INVALID)
            {
            	uint16 current_write_sample_index = ZeroCross_Atod_Write_Index[index]+1;
            	uint16 current_read_sample_index = ZeroCross_Atod_Read_Index[index];

            	if (current_write_sample_index >= ZEROCROSS_ATOD_BUFFER_SIZE)
            	{
            		current_write_sample_index = 0;
            	}

            	if (current_write_sample_index == current_read_sample_index)
            	{
            		ZeroCross_Atod_Overrun[index] = TRUE;
            		current_read_sample_index++;
                	if (current_read_sample_index >= ZEROCROSS_ATOD_BUFFER_SIZE)
                	{
                		current_read_sample_index = 0;
                	}
                	ZeroCross_Atod_Read_Index[index] = current_read_sample_index;
            	}

            	ZeroCross_Atod_Buffer[index][current_write_sample_index] = Atod__Convert(cfg_ptr->Channel, cfg_ptr->Resolution);
            	ZeroCross_Atod_Write_Index[index] = current_write_sample_index;
            }
        }
    #endif

}
 
static void GpioRequestInitialize(void)
{
#if (ZC_NUM_GPIO_REQUESTS > 0)
	uint8 index;

	for(index = 0; index < ZC_NUM_GPIO_REQUESTS; index++)
	{
		ZeroCross_Gpio_Pin_Configuration[index].Gpio_Id = ZEROCROSS_ID_INVALID;
		ZeroCross_Gpio_Pin_Configuration[index].Port = PORT_NULL;
		ZeroCross_Gpio_Pin_Configuration[index].Pin = 0;

		ZeroCross_Gpio_Requests[index].Gpio_Id = ZEROCROSS_ID_INVALID;
		ZeroCross_Gpio_Requests[index].Active_Degree = 0;
		ZeroCross_Gpio_Requests[index].Deactive_Degree = 0;
		ZeroCross_Gpio_Requests[index].Active_value = FALSE;

		ZeroCross_Gpio_Processing[index].Gpio_Id = ZEROCROSS_ID_INVALID;
		ZeroCross_Gpio_Processing[index].Active_Degree = 0;
		ZeroCross_Gpio_Processing[index].Deactive_Degree = 0;
		ZeroCross_Gpio_Processing[index].Active_value = FALSE;
	}
#endif
}

static void AtodRequestInitialize(void)
{
#if (ZC_NUM_ATOD_REQUESTS > 0)
	uint8 index;

	memset(ZeroCross_Atod_Buffer, 0, sizeof(ZeroCross_Atod_Buffer));

	for(index = 0; index < ZC_NUM_ATOD_REQUESTS; index++)
	{
		ZeroCross_Atod_Pin_Configuration[index].Atod_Id = ZEROCROSS_ID_INVALID;
		ZeroCross_Atod_Pin_Configuration[index].Channel = (ATOD_CHANNEL_DEF) ZEROCROSS_ID_INVALID;
		ZeroCross_Atod_Pin_Configuration[index].Resolution = ATOD_RESOLUTION_04BITS;

		ZeroCross_Atod_Read_Index[index] = 0;
		ZeroCross_Atod_Write_Index[index] = 0;
		ZeroCross_Atod_Overrun[index] = FALSE;
	}
#endif
}

#endif
    */
